### ISSUE TITLE
Reject invalid type names at compile time

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#101]
As discovered in #72  and implemented for the registry in #78 , we should reject invalid time names with a good error message at compile time.

This includes the custom derive implementations and the macros.

@srijs would you like to tackle this?

**Comment by piperRyan** [comment]
@theduke I could take a look at this post finals, so May if you want assign it to me. I'll also try to add a better error message for void types as well (if possible) as hinted in #161.

**Comment by piperRyan** [comment]
As for the macros themselves it seems like compile_error! won't be the answer as far as I can tell, but we can leverage [static assertions](https://github.com/nvzqz/static-assertions-rs) to check compile time invariants, but the downside is this isn't a stable crate yet, but I suspect it may be the only choice for the macros.

**Comment by piperRyan** [comment]
@theduke , @mhallin  or @LegNeato  would you prefer I just sit on my hands for the time being or should I go ahead and try to get this working with the macros?

**Comment by LegNeato** [comment]
Let's close this now that it has landed. Please open another issue (or just a straight PR) if you intend to add the optional more intensive checks!
