### ISSUE TITLE
Allow blocking clients in query contexts

### ISSUE THREAD

**Issue by awkure** [graphql-rust/juniper#1015]
**Is your feature request related to a problem? Please describe.**
Imagine we have a context that stores some clients that send blocking requests.

```rust
pub struct Context {
    pub rpc_client: RpcClient,
}
```

And we want to it from mutation queries via actix runtime

```
pub struct Mutation;

#[Object]
impl Mutation {
    pub async fn some_func(
        &self,
        ctx: &Context<'_>,
    ) -> FieldResult<Value> { 
      let result = actix_rt::task::spawn_blocking(move || { call_the_client(&ctx.rpc_client) }).await?;
      result
    }
}
```

The problem though is that the context cannot outlive `'static` lifetime forced by `spawn_blocking` call. Is there a way to work around it without making an asynchronous wrapper for the rpc client crate?

**Comment by tyranron** [comment]
The problem may be resolved by putting the `RpcClient` into an `Arc` inside `Context`.
