### ISSUE TITLE
Please Add Mutation Example

### ISSUE THREAD

**Issue by alresarena2021** [graphql-rust/juniper#1018]
I saw the examples for juniper but only for query and I don't see any mutation example

**Comment by tyranron** [comment]
@alresarena2021 it's not much difference between declaring query and mutations. The only difference is that a mutation should be declared in a `Mutation` root object.

**Comment by tyranron** [comment]
See an example here: https://graphql-rust.github.io/juniper/master/quickstart.html#schema-example
