### ISSUE TITLE
juniper_warp semver breaking release

### ISSUE THREAD

**Issue by Visic** [graphql-rust/juniper#1036]
The juniper_warp release 0.6.5 includes the update of tokio from 0.2 to version 1 which was introduced in the juniper_warp 0.7.0 release. The end result being that anyone using a 0.6 version of juniper_warp along with a version of tokio compatible with that release (e.g. tokio 0.2), will not be able to build due to mismatched tokio requirements.

**Comment by LegNeato** [comment]
This task is a year old, and the ecosystem has moved on to 1.0.
