### ISSUE TITLE
Is it possible to override `resolve_async`?

### ISSUE THREAD

**Issue by KennethGomez** [graphql-rust/juniper#1046]
I am currently trying to implement custom functionality for my Query type `resolve_async` method, but as far as I can see, this is only being called on the `RootNode`  and I can't replace its implementation, is there any way that I can override `resolve_async` method for just the Query type, instead of `resolve_field_async` getting called? 

Thank you very much in advance.

**Comment by ilslv** [comment]
@KennethGomez I guess you can use [`cargo expand`](https://github.com/dtolnay/cargo-expand) to replace GraphQL object macro with the actual generated code and expand blanket impl of a `resolve_async` method, but this solution seems far from being ergonomic. 
Maybe if you can provide more details on what do you want to achieve, I may be able to help find a better solution.

**Comment by KennethGomez** [comment]
Hey, sorry, I should have given more information about my specific case, well I am not using the GraphQL object macro, I am directly using the GraphQLType and GraphQLValue traits. Either way, my specific problem was that I wanted Query type to get resolve_async method executed instead of the resolve_field_async method. What I've done to solve this issue is add:

```rust


impl<S> GraphQLValueAsync<S> for Query
where
	S: ScalarValue + Send + Sync,
{
	fn resolve_field_async<'b>(
		&'b self,
		info: &'b Self::TypeInfo,
		field_name: &'b str,
		arguments: &'b Arguments<S>,
		executor: &'b Executor<Self::Context, S>,
	) -> BoxFuture<'b, ExecutionResult<S>> {
		Box::pin(async move {
			executor
				.resolve_async(&(), &QueryFieldFactory::new_resolver(field_name, arguments))
				.await
		})
	}
}
```

So now I have another GraphQLValue on which the resolve_async method is called.

Either way, thank you for your help!

**Comment by ilslv** [comment]
@KennethGomez 

> Either way, my specific problem was that I wanted `Query` type to get `resolve_async` method executed instead of the `resolve_field_async` method

Without the context, I'm not really sure, what are you trying to achieve. `resolve_async` and `resolve_field_async` are 2 completely different methods  with 2 different behaviours. If there is something missing or not clear about differences in their docs, I am happy to help. 
Moreover default `resolve_async` implementation is calling `resolve_field_async` inside, so you will be stuck inside an infinite recursion.

**Comment by KennethGomez** [comment]
I know that, the thing is that I need the selection_set at once instead of getting each field separately, that's why I am trying to override the reolsve_async method

**Comment by ilslv** [comment]
@KennethGomez In that case you should leave default `resolve_field_async` panicking impl and just override `resolve_async`. It's ok, because `resolve_field_async` is called only from default impl of `resolve_async`.

**Comment by ilslv** [comment]
@KennethGomez can this issue be closed or do you have more questions?

**Comment by KennethGomez** [comment]
No its okay, thank you
