### ISSUE TITLE
Cannot use lifetime in `impl` blocks

### ISSUE THREAD

**Issue by ClementNerma** [graphql-rust/juniper#1050]
When writing an `impl` block with the `#[graphql_object]` attribute, declared lifetimes cannot be used in the return type. Example:

```rust
pub struct IndexGraph;

#[graphql_object(context = GraphQLContext)]
impl IndexGraph {
    async fn fingerprint<'c>(&self, context: &'c GraphQLContext) -> &'c str {
        context.index.fingerprint.as_str()
    }
}
```

I get the following error: `use of undeclared lifetime name 'c` in the return type.

The document states to use this syntax for lifetimes so I wonder if it's a bug or if there is another way to do this?

Using Juniper 0.15.9.

**Comment by tyranron** [comment]
@ClementNerma this is not possible in `juniper` 0.15 due to how `#[graphql_object]` is desugared. This, however, is fixed in the current `master` (see #971) and will be released 0.16, once we're complete all the necessities for the release (no ETAs can be given, though).
