### ISSUE TITLE
Dynamic Schemas?

### ISSUE THREAD

**Issue by thomas-jeepe** [graphql-rust/juniper#106]
I need dynamic schemas for a project I am working on. I was searching and found this PR https://github.com/graphql-rust/juniper/pull/66 which should address my issue.

It was merged and is in the master branch, however version 0.8.1 doesn't have this new feature. For now, I think I can pull directly off of github, however I am wondering when this will be put into a new version.

**Comment by theduke** [comment]
Progress on a `0.9` release is tracked in the milestone: https://github.com/graphql-rust/juniper/milestone/2

We really must get around to preparing a release... For now, as you mentioned, please work with the master branch.
