### ISSUE TITLE
Build failed with `default-features = false`

### ISSUE THREAD

**Issue by 50U10FCA7** [graphql-rust/juniper#1064]
**Describe the bug**
Juniper failed to build if specified as dependency with `default-features = false`

Build result:
```
error[E0433]: failed to resolve: could not find `ContentRefDeserializer` in `de`
   --> ~/juniper/juniper/src/http/mod.rs:232:17
    |
232 | #[derive(Debug, Deserialize, PartialEq)]
    |                 ^^^^^^^^^^^ could not find `ContentRefDeserializer` in `de`
    |
    = note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**To Reproduce**
- create a new (empty) rust project
- set juniper as dependency with `default-features = false`
- execute `cargo run` in project directory

**Expected behavior**
Build successful.

**Additional context**
The cause of the problem is that `juniper` specifies `serde` as dependency with no `std` feature enabled. The `serde/std` feature implements serialize/deserialize for std's structs like `Vec`, `HashMap`, etc... But `juniper` uses `Serialize` on a [struct](https://github.com/graphql-rust/juniper/blob/d6f5cee8b3a773f13f8eb61616d99e5b67a093f0/juniper/src/http/mod.rs#L350) which field is a `Vec`.

At now, `juniper` can build with `default-features = true` only because `bson` dependency uses `serde/std` feature.

**Comment by tyranron** [comment]
@50U10FCA7 I wonder why the `cargo check -p juniper --no-default-features` [running on CI](https://github.com/graphql-rust/juniper/blob/d6f5cee8b3a773f13f8eb61616d99e5b67a093f0/.github/workflows/ci.yml#L99) doesn't reproduce this 😕

**Comment by tyranron** [comment]
Is it because of Cargo workspace? 🤔

**Comment by 50U10FCA7** [comment]
@tyranron 

> Is it because of Cargo workspace? 🤔

Probably one of the workspace dependencies enables `serde/std` feature, but not sure. Check still pass if remove `serde/std` feature from all workspace-member crates, but I think the situation is the same when `bson` dependency hide this error (Compiles because dependency of dependency enables the feature).
