### ISSUE TITLE
publish juniper_rocket 0.8.2

### ISSUE THREAD

**Issue by Asone** [graphql-rust/juniper#1067]
Hi, 

A [fix](https://github.com/graphql-rust/juniper/commit/1f0f683d0b24ca9dbc463ea98f98852edc4eac32) has been pushed a few days ago to make `juniper_rocket` crate compatible with the latest version of rocket ( 0.5.0-rc.2 ). 
However the modifications have not been published yet.

I know it could be answered that users could use a former release of rocket instead, however, it appears there's an [issue](https://github.com/SergioBenitez/Rocket/issues/2166) with the semver used by rocket that makes impossible to install and build 0.5.0-rc.1. 

Therefore, any project that needs to install and use both latests versions juniper and rocket currently remains stuck on building. 

Thanks a lot

**Comment by daviddanielarch-nextroll** [comment]
It would be good to have this, I need to point to a fork in the meantime.

**Comment by tyranron** [comment]
@Asone @daviddanielarch-nextroll done: https://crates.io/crates/juniper_rocket/0.8.2

**Comment by Asone** [comment]
Works like a charm. Thanks a lot !
