### ISSUE TITLE
`graphql_input_object!` errors when public fields are present

### ISSUE THREAD

**Issue by berwyn** [graphql-rust/juniper#107]
When generating a struct like so:
```rust
graphql_input_object!(
    pub struct Foo {
        pub bar: u32,
        pub baz: u32,
        pub bat: u32,
    }
);
```
The compiler will bail out with multiple errors:
```
error: no rules expected the token `generate struct fields`
error: no rules expected the token `generate_from_input_value`
error: no rules expected the token `generate_to_input_value`
error: no rules expected the token `generate_meta_fields`
```
while indicating the body of the macro. Removing `pub` from the fields corrects the issue, but means the struct fields are only usable in the struct impl.

I am still a complete newbie to Rust, but it seems related to [this post on StackOverflow](https://stackoverflow.com/questions/42003501/preserving-struct-field-visibility-with-a-macro), which indicates that the current macro system cannot detect visibility modifiers. I'm not sure there's anything you fine folk can do about this, but maybe a warning about this in the documentation would be good for people like me that didn't know this previously!

**Comment by mhallin** [comment]
Hello!

This seems indeed to be a bug in `graphql_input_object!`, thanks for taking the time to report this.

In the meantime, if you're feeling adventurous, you could use Juniper from the master branch of this Git repository, together with the new `juniper_codegen` crate like this:

```toml
[dependencies]
juniper = { git = "https://github.com/graphql-rust/juniper" }
juniper_codegen = { git = "https://github.com/graphql-rust/juniper" }
```

This enables the new derive attribute for input objects, like so:

```rust
#[macro_use] extern crate juniper_codegen;
#[macro_use] extern crate juniper;

#[derive(GraphQLInputObject)]
struct Coordinate {
    pub latitude: f64,
    pub longitude: f64
}
```

Where the `pub` modifiers _should_ be respected.

**Comment by berwyn** [comment]
Aha! This is very good to know, thanks 😃 I am actually building against the master branch, since that's what's recommended in the readme and because I'm using Juniper in conjunction with Rocket, so I'll give that a go!

**Comment by mhallin** [comment]
The `graphql_input_object!` macro has been removed in favour of the custom derive in 0.9, so I'm closing this issue.

**Comment by berwyn** [comment]
Sounds good to me! Do you have a plan for approximately when that release will be tagged?

**Comment by theduke** [comment]
@berwyn it was already published on sunday.

https://crates.io/crates/juniper

**Comment by berwyn** [comment]
Oh, I must have missed that! Thanks guys for your hard work and awesome library!
