### ISSUE TITLE
Mutation argument with default value is marked as required in schema

### ISSUE THREAD

**Issue by deiwo** [graphql-rust/juniper#1083]
**Describe the bug**
The problem is when mutation argument is specified with scalar type and a default value in the macro. In the schema that is generated this argument is marked as required with `!` even though it doesn't have to be required, since the default value is specified.

**To Reproduce**
Define a simple mutation:
```rust
fn do_something(
    #[graphql(default = false)]
    should_switch: bool
) {
    ....
}
```

The generated schema:
```graphql
mutation doSomething(
    shouldSwitch: Boolean! = false
)
```
Send a request to this mutation with `should_switch` set to `undefined`.
This request gets a error response that the required type is `Boolean!` but `Boolean` was provided.

**Expected behavior**
The default value is used for the argument and no error is raised.

**Additional information**
This behavior occurs in `master` branch, but in the `v15` it works as expected.

**Comment by ilslv** [comment]
As pointed out in #1073, behaviour of `v15` is wrong and was fixed on `master` in #1080. Detailed spec explanation can be found in [Coercing Field Arguments][1] section, but I find wording [here][2] more helpful:

> In other words, there is a semantic difference between the explicitly provided value null versus having not provided a value.

So providing `null` for `shouldSwitch` field is different from not providing value at all. In current scenario first option should raise an error, while second one will use default value. 



[1]: https://spec.graphql.org/draft/#sec-Coercing-Field-Arguments 
[2]: https://spec.graphql.org/draft/#sel-GAHhBVHDCECCGkBm2E
