### ISSUE TITLE
Create scalar with object value

### ISSUE THREAD

**Issue by KennethGomez** [graphql-rust/juniper#1090]
I've created without issues a GraphQLScalar that admits JSON from `serde_json` but when using it for queries I get the following error:
```json
{
  "error": {
    "errors": [
      {
        "message": "Variable \"$obj\" got invalid value. Expected \"JsonScalar\", found object.",
        "locations": [
          {
            "line": 1,
            "column": 8
          }
        ]
      }
    ]
  }
}
```

Query:
```gql
query($obj:JsonScalar!){
  getAccounts(where: {
    properties: {
      _eq: $obj
    }
  }) {
    _key
    firstName
    lastName
  }
}
```

Query variables:
```json
{ "obj": {"a": 1, "b": "c"} }
```

How can I actually define that JsonScalar is an alias for objects for GraphQL?

**Comment by ilslv** [comment]
@KennethGomez [from GraphQL spec](https://spec.graphql.org/October2021/#sel-EAHXFCAACCJuvS)

> Scalar types represent primitive leaf values in a GraphQL type system. GraphQL responses take the form of a hierarchical tree; the leaves of this tree are typically GraphQL Scalar types (but may also be Enum types or null values).

That means you should provide following query variable: 

```json
{ "obj": "{\"a\": 1, \"b\": \"c\"}" }
```
