### ISSUE TITLE
Upgrade `uuid` to v1.x

### ISSUE THREAD

**Issue by edgarogh** [graphql-rust/juniper#1094]
The `uuid` crate has been in stable v1 for 4 month (9 if you include the alpha versions). It would be great to update it as it causes quite a few incompatibilities with other crates. Of course there are cheap (possibly optimized to nothing) ways to convert between the old and new UUIDs, but having to convert explicitly causes unnecessary friction.

Also [as said here](https://users.rust-lang.org/t/uuid-is-now-1-0/74560#stability-commitment-2), this version should be the "last" to require a breaking update :
> With uuid 1.0 we'll try to stay on that version "forever". There won't be a 2.0 unless there's a very compelling need for it. That means you should feel safe depending on Uuid in the public API of your libraries if you want to.

## Solution

Set `uuid`'s version to 1.x in `Cargo.toml`. _I don't know if the minor version would benefit from being specified too._ The breaking changes are described [here](https://github.com/uuid-rs/uuid/releases/tag/1.0.0).

I can work on that if you're interested.

**Comment by tyranron** [comment]
@edgarogh we do have this [on `master`](https://github.com/graphql-rust/juniper/blob/0df1e448e87d6b5f65d16710ca4b05d873459964/juniper/Cargo.toml#L58) for quite a while, and it will go into [0.16 release](https://github.com/graphql-rust/juniper/milestone/4). This won't be fixed on 0.15 `juniper` however, as introduces breaking change.
