### ISSUE TITLE
How do I access intermediate objects?

### ISSUE THREAD

**Issue by TemporaryHousing** [graphql-rust/juniper#1095]
I am building a GraphQL server with `juniper` and `actix-web`. I would like to be able to do the following things for a particular application that I am working on.

1. Access the query that was sent. Preferably, I would be able to use the AST itself.
2. Get the full object before it is resolved and turned into an `HttpResponse`.

Right now, I've forked juniper and created my own little version that changes the return type for POST requests to include the object as a JSON `Value` and the query as a `String`. I do not like this approach. Additionally, I still don't have the full result. The only way I can get that is to manually repeat the query to the database. Note that `HttpResponse` can't be cloned in order to extract the JSON from it.

EDIT: An interesting point is that I can't clone the `Payload` either to repeat the query using it.

**Comment by tyranron** [comment]
@TemporaryHousing 

1. You can use `juniper::parse_document_source()` to receive AST of the request GraphQL operation. It's [used directly in the `juniper::execute()`](https://docs.rs/juniper/0.15.10/src/juniper/lib.rs.html#278). Unfortunately, you'll have double parsing, as `juniper` at the moment doesn't provide API for executing already parsed AST.

2. `juniper::execute()` returns `juniper::Value`, which represents the resolved object. `juniper_actix`, however, doesn't provide any hooks into it. But you always may write your own `actix-web` handler, having your portion of logic, as it's quite trivial:
    - https://docs.rs/juniper_actix/latest/src/juniper_actix/lib.rs.html#119-129
    - https://docs.rs/juniper/0.15.10/src/juniper/http/mod.rs.html#102-121

> Additionally, I still don't have the full result. 

Don't really understand what do you mean by this, as the `juniper::execute()` always returns the fully resolved `juniper::Value`. Could you clarify?

**Comment by TemporaryHousing** [comment]
Ahh okay! You’ve already cleared up a bunch of things for me here.

Regarding the point about the fully resolved object. What I mean is that I want the object before it is resolved. I don’t know if that makes any sense. What I essentially want is the object before the unnecessary fields are removed.

**Comment by tyranron** [comment]
@TemporaryHousing 

>  What I essentially want is the object before the unnecessary fields are removed.

Ahh, I see. There is no such phase, however. The way how `juniper` works, is to execute leaf-value user-provided field (like struct field or a method), which returns some value of the user-provided type implementing `GraphQLType`, then for the returned value executes [`GraphQLValue::execute()`], which, as you see accepts the selection set and returns the `juniper::Value` with the fields being selected. So, once any leaf or sub-tree is resolved, even before any parent node is resolved, it already has selected fields only.

This design allows `juniper` to omit executing any computable fields if they are not selected by user.
