### ISSUE TITLE
Why doesn't juniper_warp::make_graphql_filter take schema: Arc<RootNode<...>>?

### ISSUE THREAD

**Issue by silvanshade** [graphql-rust/juniper#1135]
I notice that `juniper_hyper::graphql` takes the schema/rootnode argument as type `Arc<RootNode<...>>` but `juniper_warp::make_graphql_filter` only takes the schema as `RootNode<...>`.

This seems to make `juniper_warp` difficult to use in practice in the scenario of library integrations (e.g., a juniper-based GraphQL plugin for tauri).

In the example [here](https://github.com/graphql-rust/juniper/blob/6aa63854372bf50d7134491495568593e968c7c6/juniper_warp/examples/warp_server.rs#L13) this issue is side-stepped completely by creating a function `schema()` which returns a fresh `RootNode` instance.

In a library integration, however, you do not have access to the components necessary to construct a new `RootNode`.

It seems that `juniper_warp` should take the argument as an `Arc<RootNode<...>>` like `juniper_hyper` in order to avoid this problem.

Is there a reason why it is not defined this way?

**Comment by tyranron** [comment]
@silvanshade I don't see any. It seems that authors of the code just didn't consider this use case. A PR would be appreciated.
