### ISSUE TITLE
How do you disable a complex field for a type when fetching that field as a Vector?

### ISSUE THREAD

**Issue by PumpedSardines** [graphql-rust/juniper#1137]
I'm very new to GraphQL so I might've misunderstood something, but eitherway, I wanted to ask to see if this is possible.

I'm wondering if it's possible to disable high demanding fields when querying a schema as a batch instead of when fetching multiple of that schema.

So for example, if I have a user type which has a posts field that fetches all the users posts, I wouldn't want that to be able to fetch the posts when querying multiple users. 

Example code:
```rs
#[derive(Clone)]
pub struct User {
    id: i32,
    name: String,
}

#[graphql_object]
impl User {
    fn id(&self) -> i32 {
        self.id
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn posts(&self) -> Option<&str> {
        // Demanding DB call
    }
}

struct Query;
#[graphql_object(context = Database)]
impl Query {
    fn api_version() -> &'static str {
        "1.0"
    }

    fn user(
        context: &Database,
        #[graphql(description = "id of the user")] id: i32,
    ) -> Option<&User> {
        // Fetch one user
    }

    fn users(
        context: &Database,
    ) -> Vec<&User> {
        // Fetch many users
    }
}
```
Is it possible to "hide" the posts function when running `users` so that the users `posts` on wouldn't be available. You could always create a struct called `UserSmall` and return `Vec<UserSmall>`, but that seems weird to me.

**Comment by ilslv** [comment]
@PumpedSardines 

> You could always create a struct called `UserSmall` and return `Vec<UserSmall>`, but that seems weird to me.

Actually, this is a right thing to do. Main benefit of GraphQL is that it allows to build type safety around described schema. But in case we would allow hiding arbitrarily fields, this promise breaks.
As a client of an API I always expect non-optional fields to be present.
