### ISSUE TITLE
string mangling on dynamic schema due to smartstring dependency

### ISSUE THREAD

**Issue by matko** [graphql-rust/juniper#1142]
I'm working on a project that extensively uses dynamic schema generation to expose user databases as graphql. Recently we discovered a strange bug where on some machines generating responses for schema introspection was panicking due to invalid utf-8 strings.

We eventually found out that the underlying cause is the smartstring library, which in the released version of juniper is still on version 0.2.10. Specifically, fields created with `Registry::field(..)` have their field name turned into a `SmartString`, which for certain values on certain machines was generating garbage. When rebuilding juniper with smartstring 1.0.1, we no longer encounter this issue.

It looks like the current master has also made this upgrade, but unfortunately we can't run bleeding edge due to stability concerns and the fact that the codegen seems to be different on that branch.

Is it possible to release a version of juniper 0.15 with smartstring upgraded?

As a sidenote, while the latest released version of juniper appears to be 0.15.10, I can't actually find a commit with that version in the juniper Cargo.toml. The version tagged as juniper-v0.15.10 still has the version set to 0.15.9, and it seems to remain this way until it is raised to 0.16. How come?

We're tracking this issue at https://github.com/terminusdb/terminusdb/issues/1686.

**Comment by LegNeato** [comment]
What version of Juniper are you on? I believe this is already fixed in `master`:

https://github.com/graphql-rust/juniper/blob/5aadecedf679e882f61042014b04ec429c0131d2/juniper/Cargo.toml#L56

**Comment by LegNeato** [comment]
Ah, sorry, I see you specified as `0.15.10`. We'll look into the release tagging, perhaps we broke something.

**Comment by tyranron** [comment]
@matko should be fixed in [0.15.11 release](https://github.com/graphql-rust/juniper/releases/tag/juniper-v0.15.11).

**Comment by mrtnzlml** [comment]
@tyranron This fixed the issue for me. Thank you so much! 👏
