### ISSUE TITLE
Rust 1.67 emitting schema non-utf-8 field names

### ISSUE THREAD

**Issue by dmtrKovalenko** [graphql-rust/juniper#1143]
**Describe the bug**
After updating to rust 1.67 schema output started mangling some field names and output non-utf8 characters

**To Reproduce**
Open this codesandobx: 

https://codesandbox.io/p/sandbox/cocky-jackson-jnku3m?file=%2Fsrc%2Fmain.rs&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A20%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A20%7D%5D

Spawn a new terminal and `cargo run`, you will see the a non utf-8 character. Then go back to 1.66 `rustup default 1.66` and you will see correct output.

**Expected behavior**
No non-utf8 characters

**Additional context**

**Comment by MrPiao** [comment]
Probably related to #1142

**Comment by tyranron** [comment]
@MrPiao should be fixed in [0.15.11 release](https://github.com/graphql-rust/juniper/releases/tag/juniper-v0.15.11).

**Comment by dmtrKovalenko** [comment]
Thanks for a quick resolution, it works with 0.15.11
