### ISSUE TITLE
Expected query, got subscription.

### ISSUE THREAD

**Issue by CosminPerRam** [graphql-rust/juniper#1164]
**Describe the bug**
I'm trying to access my API via Postman/Insomnia, I got a query and a subscription and on the subscription one, using any of the programs mentioned, i get this response:
```json
{
    "errors": [
        {
            "message": "Expected query, got subscription"
        }
    ]
}
```
The query works as expected.

**To Reproduce**
Create a juniper project that uses subscriptions and try to query it from Postman/Insomnia.

Insomnia request body (the same in Postman):
![image](https://github.com/graphql-rust/juniper/assets/7972857/b5cd38d9-d7bd-4881-ae8c-10759bf75401)

**Expected behavior**
Get back a response.

**Additional context**
I'm using warp and juniper, my subscription setup is based on the example one, [here](https://github.com/graphql-rust/juniper/blob/master/examples/warp_subscriptions/src/main.rs).

Insomnia timeline:
![image](https://github.com/graphql-rust/juniper/assets/7972857/99ca5b6d-de2e-4264-972e-3faf2b819815)

By searching `Expected query, got subscription` in the repo, i find that it comes from [here](https://github.com/graphql-rust/juniper/blob/a648dd727519991c2e3c762af16eac027b2acec2/juniper/src/integrations/serde.rs#L65), although I can't make much of this and I can't seem to find any documentation related to using Insomnia/Postman with Juniper. Am I doing something wrong on the Insomnia part? Is this a Juniper problem regarding the graphql specification? Thanks in advance.

**Comment by CosminPerRam** [comment]
Yeah, they aren't done via HTTP, but I thought that it would automatically switch up protocols.
I have tried [Altair](https://altairgraphql.dev/) and it works, thanks for the suggestion, I would consider into adding it to the README as a fully working client.

Also, mind asking why has this issue been added to the `0.16.0` milestone? @tyranron

**Comment by tyranron** [comment]
@CosminPerRam 

> Yeah, they aren't done via HTTP, but I thought that it would automatically switch up protocols.

That's not trivial, maybe not possible in a menanigful way. WS request should contain `Connection: Upgrade`, and moreover, GraphQL over WebSocket Protocol has some initial handshake before executing the GraphQL operation. It seems not correct to just suddenly switch GraphQL over WebSocket Protocol whenever a `subscription` operation is received over HTTP, because the client side will unlikely expect that.

> Also, mind asking why has this issue been added to the `0.16.0` milestone?

It's just easier for me to track issues/PRs resolved in spans of releases.
