### ISSUE TITLE
Old version of book is still online

### ISSUE THREAD

**Issue by FrankReh** [graphql-rust/juniper#1168]
**Describe the bug**
Today was the first time reading about Rust Juniper. Googled and found https://graphql-rust.github.io

But after reading some time, I googled something related and got into what appears to be a much more recent version of the same book: https://graphql-rust.github.io/juniper/master/index.html

**To Reproduce**
Click on one link or the other from above.

**Expected behavior**
Expected only the most recent version of the book.

**Additional context**

Apologies if I'm overlooking something obvious.

**Comment by ilslv** [comment]
@FrankReh https://graphql-rust.github.io/juniper/master/index.html is describing usage of unreleased version of `juniper`, which is quite different from the latest `crates.io` release
