### ISSUE TITLE
operation_name not being set in juniper_hyper library

### ISSUE THREAD

**Issue by FrankReh** [graphql-rust/juniper#1169]
**Describe the bug**
The code block https://github.com/graphql-rust/juniper/blob/a648dd727519991c2e3c762af16eac027b2acec2/juniper_hyper/src/lib.rs#L225-L229
seems to be missing a statement where operation_name would be set to `Some(value)`.

**To Reproduce**
Just read through code. See the variable is defined a `None` and nowhere is being set.

**Comment by LegNeato** [comment]
You're right, looks like a bug / omission. Can you put up a PR with a test?

**Comment by FrankReh** [comment]
Sorry. I've lost the context for this repo. It's been too long. We can close it if this doesn't bother anyone else.
