### ISSUE TITLE
Looking for Help & Community

### ISSUE THREAD

**Issue by FinnFrotscher** [graphql-rust/juniper#1172]
Hi,
I have set out to learn Rust to build a larger application using juniper. The examples provided are all quite basic and don't tell much about how to structure larger applications.
Are there any community hubs?

**Comment by thirsty-wing** [comment]
There is a gitter chat: https://gitter.im/juniper-graphql/Lobby

**Comment by LegNeato** [comment]
There is also https://github.com/graphql-rust/juniper/discussions
