### ISSUE TITLE
Gitter link resolves to 404

### ISSUE THREAD

**Issue by tusharmath** [graphql-rust/juniper#1178]
The Gitter link in the README file is incorrect and leads to a 404 page. 

## Expected Behavior
The Gitter link should lead to the actual Gitter chat room for the project.

## Current Behavior
Clicking the Gitter link leads to a 404 page.
**Link:** https://gitter.im/juniper-graphql

## Possible Solution
Please update the link with the correct URL.

**Comment by LegNeato** [comment]
Fixed by https://github.com/graphql-rust/juniper/pull/1175.
