### ISSUE TITLE
expected tuple struct or tuple variant, found function `Ok`

### ISSUE THREAD

**Issue by folivi** [graphql-rust/juniper#1229]
Hi all,

I have a struct  MyStructFromDatabase {}

I have to turn into a Graphql object I need to return.

But my compiler complains with this error: 

error: expected tuple struct or tuple variant, found function `Ok`
label: not a tuple struct or tuple variant

What I'm I doin't wrong?

Thank you for your help

**Comment by folivi** [comment]
Seems like the issue came for VS Code.

**Comment by tyranron** [comment]
@folivi an empty struct cannot be a GraphQL object, because it's [obligated to have fields](https://spec.graphql.org/October2021/#sel-HAHZhCFBABABuBq9O).
