### ISSUE TITLE
Clean up Clippy warnings + remove try!

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#131]
Right now, there are a lot of clippy warnings in the codebase.

Most of them are sensible suggestions and should be fixed.

Also, we should remove `try!` and replace it with   `?` everywhere.

Instructions:

```bash
rustup install nightly
rustup default nightly
cargo install clippy

cd juniper
cargo clippy
```

This is an easy task and help is very welcome.
@LegNeato

**Comment by Atul9** [comment]
I am working on this.

**Comment by theduke** [comment]
@Atul9 cool.

Feel free to to a PR any time, also just fixing a couple of warnings if fine.

**Comment by Atul9** [comment]
@theduke I have opened up a PR. I need help to fix the build. I am new to Rust, I would like to learn what the build error `no rules expected the token `description`  means?
