### ISSUE TITLE
Provide TypeInfo to the GraphQLType::concrete_type_name

### ISSUE THREAD

**Issue by idubrov** [graphql-rust/juniper#133]
I have a generic implementation for the GraphQLType trait, so I rely heavily on the TypeInfo reference. Currently concrete_type_name does not have &TypeInfo as a parameter, even though it's caller does have it.

**Comment by idubrov** [comment]
https://github.com/graphql-rust/juniper/pull/134

**Comment by LegNeato** [comment]
Now that https://github.com/graphql-rust/juniper/pull/134 landed this can be closed, right?

**Comment by theduke** [comment]
@LegNeato thanks for the cleanup reminder.
