### ISSUE TITLE
Chronos NaiveDate Serialisation / Deserialisation

### ISSUE THREAD

**Issue by sporto** [graphql-rust/juniper#150]
I was trying to use `NaiveDate` as a scalar for a bookings application and was surprise to find out that I need to pass a string like `2018-01-01T16:39:57-08:00` for it to work. 

If I understand correctly `NaiveDate` is what you would use when you want a date independent of the timezone. When using a `Date` column type in postgres, using NaiveDate in a struct seems like a good fit.

So when using NaiveDate as a scalar I expected NaiveDate to serialize to `2018-01-01`. And be able to deserialize from that.

Maybe I'm wrong on my expectation of NaiveDate. Is there a type better suitable for only dates? Or maybe NaiveDate should only serialize to the date part.

Thanks

**Comment by theduke** [comment]
Fully agreed.
This was an oversight when this was implemented.
Will be a small fix: https://github.com/graphql-rust/juniper/blob/master/juniper/src/integrations/chrono.rs

**Comment by sporto** [comment]
Done in https://github.com/graphql-rust/juniper/pull/151
