### ISSUE TITLE
Use -Z minimal version on CI

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#163]
Use -Z minimal version when building on CI to make sure that everything works with the minimum version specified in cargo.toml.

Will need to wait until the flag hits stable.

**Comment by briankabiro** [comment]
Hey, @theduke. Has this been taken up?

**Comment by theduke** [comment]
@briankabiro no, feel free to take a shot at it.

Would have to be nightly only for now.

Please consider that we use https://crates.io/crates/cargo-make on the ci.

**Comment by LegNeato** [comment]
I don't think we need to do this now that we check our min version in CI.

**Comment by theduke** [comment]
> I don't think we need to do this now that we check our min version in CI.

What do you mean?

This is about building with the minimum version of dependencies in the allowed range, rather than the maximum version. This ensures not accidentally breaking

**Comment by theduke** [comment]
PS: just checked, the cargo flag is still unstable, but I'll add it to nightly. Doing this on one compiler version is enough anyway.

**Comment by tyranron** [comment]
Fixed by https://github.com/graphql-rust/juniper/pull/1113
