### ISSUE TITLE
How to nested graphql_object？

### ISSUE THREAD

**Issue by shuaizhiwen** [graphql-rust/juniper#169]
Sorry, My English is so poor.I don't know whether this description is right or not.
I want it likes this:
A query has many fields, but every field is a function, and can be included in query.
like this:
```
pub struct VersionText;

graphql_object!(VersionText: () |&self| {
    field version() -> &str {
        "1.0"
    }
});

pub struct QueryRoot;

graphql_object!(QueryRoot: () |&self| {
    field apiVersion() -> &str {
        "1.0"
    }
    field VersionText;
});
```
I don't know if I have a clear description. If you don't quite understand what I mean, I can describe it again.
Thank you very much for your help!

**Comment by theduke** [comment]
You are not far off, you just have to declare the nested field like a regular one and return the struct.

```rust
pub struct VersionText;

graphql_object!(VersionText: () |&self| {
    field version() -> &str {
        "1.0"
    }
});

pub struct QueryRoot;

graphql_object!(QueryRoot: () |&self| {
    field apiVersion() -> &str {
        "1.0"
    }
    field versionText() -> VesionText {
        VersionText
    }
});
```

**Comment by theduke** [comment]
I am closing this now, but feel free to ask more questions if you have any.
