### ISSUE TITLE
Floating point numbers issue

### ISSUE THREAD

**Issue by tailhook** [graphql-rust/juniper#178]
Hi, I came across the issue that all numbers without decimal part are treated as i32, which is a problem for handing floating point numbers. I.e. if I need large floating point number without a decimal part it's encoded as an integer by browsers:

```
>>> JSON.stringify({"x": 2.0 ** 35})
{"x":34359738368}
```

This means that you can't decode that json as `InputValue` reliably. As it will fail with the error like in #52.

I think treating everything that is > i32::max as floating point is fine, for InputValue? Or you you see any shortcommings of this approach?

**Comment by theduke** [comment]
Mhm, this is a complicated topic.

The spec clearly says that integers are int32 (http://facebook.github.io/graphql/October2016/#sec-Int).
So anything larger must be either a float or a string for the type system.

And the spec also clearly says that numbers without an exponent or decimal part are Int values, not floats.

BUT the spec also says that **raw** values should be coerced to float where appropriate (from int or string). We actually do this conversion already.

But the lexer will fail with int values that exceed the `i32` range.

So the lexer would have to recognize larger integers and a possible conversion would have to happen later. 

The spec doesn't say anything explicitly about this but it makes sense to allow larger integers on the lexer side and coerce them to floats later.

(PS: personally I'd probably use strings for large numeric values and manually cast them later one. That's a safer route to go considering you can have clients in all kinds of languages).

**Comment by tailhook** [comment]
Made a pull request. While I agree that graphql is a different language and can require `.0` on floating point numbers. We can't control such thing for JSON. It would be unfortunate if we need our own JSON serializer in browser to support floating point types :)
