### ISSUE TITLE
Any chance for a input union support? 

### ISSUE THREAD

**Issue by TheServerAsterisk** [graphql-rust/juniper#18]
Even though it is not officially supported by the current [specs](https://github.com/graphql/graphql-js/issues/207),  there is currently an unofficial [implementation](https://github.com/Cardinal90/graphql-union-input-type) for it. Personally, I think it would be great if it was there was perhaps a feature or is there a good workaround for this issue?

**Comment by mhallin** [comment]
Interesting. We could maybe support it with a feature flag. Are there any other GraphQL implementations that support it?

**Comment by TheServerAsterisk** [comment]
No, as far as I can tell there doesn't seem to be direct support for it in other implementation or even indirect support, but many of these are projects are quite young like this one especially compared to the js one.  

There might of have been some indirect support for it in the Go implementation but overlooked it due to a lack of familiarity with the language (not likely though).  While I have figured out a different way to approach the data, it just would have been nicer and less complex. I'll leave it up to you on what should be done.

**Comment by mhallin** [comment]
After thinking on this and working some more on an application, it seems as if a limited version of input unions that "automatically" maps to tagged Rust enums would be interesting. It would be a subset of the specification linked above.

I will try to work on this for a bit. The tricky part is to not build something that a later GraphQL will make obsolete :)

**Comment by thedodd** [comment]
The [node graphql](http://graphql.org/graphql-js/type/#graphqluniontype) system supports the full spec. It would be great to have this.

One use-case where this would be extremely valuable would be for paging. You can define a type `PagedData` with a field `page` of concrete type `PageInfo` and a field `data` which would be an array of some union type, where the union type would be all of the possible types which could be returned as a page of data:
```graphql
input PageRequest {
  page: Int!
  size: Int!
}

union PagedDataType = ConcreteTypeA | ConcreteTypeB | ConcreteTypeC # Union of concrete types.

type PagedData {
  page: PageInfo! # a concrete type.
  data: [PagedDataType!]!
}

type Query {
  myData(PageRequest!): PagedData!
}
```

Then you could query as follows:
```graphql
query {
  myData({page: 0, size: 50}) {
    data {
      ... ConcreteTypeB {
        field1 field2 field3
      }
    }
  }
}
```

So, in Rust terms, a union type would simply be an `enum` type behind the scenes, where each variant would have an associated struct value being one of the concrete types defined in the union.

**Comment by theduke** [comment]
Le'ts not support anything not in the spec, we have enough catch-up work to do as is.

We can re-open if/when this gets accepted.
