### ISSUE TITLE
[feature request ] Please advance generic types as they are pretty useless at this time

### ISSUE THREAD

**Issue by trsh** [graphql-rust/juniper#186]
1.

This is cool example from docs
```
struct GenericType<T> { items: Vec<T> }

graphql_object!(<T> GenericType<T>: () as "GenericType" |&self| {
    field count() -> i32 { self.items.len() as i32 }
});
```
bit can't use it like 

```
graphql_object!(<T> Listt<T>: () as "Listt" |&self| {
   ......
    field edges() -> Vec<T> {
        self.edges
    }
});
```

what gives an ^ the trait `juniper::GraphQLType` is not implemented for `T` error.
So it make little sense for me, if I can't use the generic as another GraphQLType in object macro. 

2.

```
#[derive(GraphQLInputObject)]
pub struct Paging<T> {
    pub first: i32,
    pub page: T,
}
```

Macro doesn't support this and neither this:

```
#[derive(GraphQLObject)]
struct NewConstant<T> {
    id: String,
    value: T,
}
```

To make this happen I had to drop Macro and generate a lot of boilerplate code. So it would be nice to see this kind of support in future.

**Comment by ForsakenHarmony** [comment]
well for the macro you're gonna have to put a bound on the generic type so it can only be a type that impls `GraphQLType`

**Comment by LegNeato** [comment]
I believe the second part was fixed in https://github.com/graphql-rust/juniper/pull/226 and the first part does not appear actionable.
