### ISSUE TITLE
Update to the June 2018 GraphQL spec

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#196]
A new spec is out (https://github.com/facebook/graphql/releases/tag/June2018). It looks like a lot of our error handling questions / behaviors have been clarified among other things.

**Comment by theduke** [comment]
We should come up with a checklist of what we have to implement.

**Comment by LegNeato** [comment]
https://github.com/graphql-rust/juniper/pull/219 switched from `data` to `extensions` for custom error data.

**Comment by dvic** [comment]
@LegNeato I think it would be useful to have a test suite based on https://github.com/graphql-cats/graphql-cats. That project seems to cover many scenario's, I think also beyond the June 2018 spec, but at least then we have an idea of what is supported and what is not. 

I'm not sure what the implementation would be exactly (a simple dynamic schema executor based on the scenarios'?) but the project is useful at least as a point of reference :)

**Comment by theduke** [comment]
@dvic I already made an issue for this a while ago.

https://github.com/graphql-rust/juniper/issues/245

**Comment by dvic** [comment]
@LegNeato Ah nice, next time I'll make sure to do a search ;) Maybe I have this weekend time to have a look at it to see what we can do with it.

**Comment by tyranron** [comment]
@LegNeato I guess this has been fixed in #631?

**Comment by LegNeato** [comment]
Yes, this should be fixed.
