### ISSUE TITLE
Significance of |&self| in graphql_object! macro

### ISSUE THREAD

**Issue by mikeyhew** [graphql-rust/juniper#197]
Hi there, first of all, great work on Juniper. I haven't used it yet, but it looks like a great library for making GraphQL servers in Rust.

I was reading the [Complex fields](http://juniper.graphql.rs/types/objects/complex_fields.html) page in the Juniper book, and was curious about the `|&self|` syntax and what it does. I couldn't find anything about it the book or in the reference documentation for the macro. Is it a sort of "placeholder" syntax for a feature that may be added farther down the road, where `|&mut self|` would be another option?

**Comment by kestred** [comment]
@mikeyhew: (I'm pretty sure:)

Rust's Macros by Example must capture any identifier they want to pass between generated code and code provided in a macro; including the `self` parameter.

The macro:
```rust
graphql_object!(Person: () |&self| {
    field name() -> &str {
        self.name.as_str()
    }
}```

is expanded into something like:
```rust
impl GraphQLType for Person {
    fn execute(&self, args: ...) -> Result<_, _> {
         match field {
              "name" => {
                     Ok(self.name.as_str())
               }
         }
    }
}```

And to allow the `self.name.as_str` to reference `self` it must be passed in as a token/identifier (e.g. `$self:ident` and used in the macro definition at `execute($self)`.

**Comment by mikeyhew** [comment]
@kestred that makes sense, thanks for the explanation!
