### ISSUE TITLE
No way to map an enum from a third-party crate to GraphQL trait.

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#209]
I can't seem to figure out how to expose an enum from a crate not in my control (in this case `isocountry`). I can't implement the derive because it isn't my enum, it was defined in a different crate. Trying to `impl juniper::GraphQLType for CountryCode` essentially requires me to copy all the data from the enum into  my code (image the struct `DogCommand ` had 100s of entries and was defined in another crate https://github.com/graphql-rust/juniper/blob/9313c7ca6dfecd287a2fd84117339a493041e25e/juniper/src/validation/test_harness.rs#L105).

Perhaps I am just missing a way to do this?

**Comment by piperRyan** [comment]
I don't think you can unless there is going to be a change in the coherence rules. The two ways that I know of is to do is the newtype pattern or manually export the code so that it isn't a external dependency. 

Alternatively, one can impl the trait in juniper or in the foreign crate you wish to integrate.

**Comment by tomhoule** [comment]
Serde has a way to derive `Serialize` and `Deserialize` for remote structs and enums but it requires repeating the fields.

https://serde.rs/remote-derive.html

**Comment by LegNeato** [comment]
Hmmmm, so I guess the answer is to get the crate to derive GraphQLEnum. That seems not great as it will be impossible to have the whole Rust ecosystem do so for useful enums

**Comment by theduke** [comment]
> Hmmmm, so I guess the answer is to get the crate to derive GraphQLEnum. That seems not great as it will be impossible to have the whole Rust ecosystem do so for useful enums

That's one of the burdens that come with coherence rules and the lack of orphan instances in Rust.
That's the reason why we need chrono, uuid etc features to implement them in Juniper.
But that's only feasible for very popular crates, of course.

If the remote enum implements some to/from string functionality or derives Serialize/Deserialize you can add a wrapper type and implement the GraphQL type by converting via serde or to/from a string to avoid manually repeating all variants.

**Comment by JeanMertz** [comment]
I ran into this today as well.

> If the remote enum implements some to/from string functionality or derives Serialize/Deserialize you can add a wrapper type and implement the GraphQL type by converting via serde.

Given the ubiquitous support that Serde has in the Rust ecosystem (many crates either directly depend on Serde, or have a `serde` feature flag), it might be worth it to add an example doing exactly this to the documentation.
