### ISSUE TITLE
Cut a release, ship to crates.io

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#210]
We should cut a new release as it has been a while.

**Comment by z0mbie42** [comment]
I would really love to see #201 in the next release, but as a relatively new rust programmer I don't understand anything to macros.
If someone give me any hint in how to implement this, I would enjoy to make a PR :)

**Comment by LegNeato** [comment]
Ok, I just pushed everything. Next up is updating docs with the latest changes, filed https://github.com/graphql-rust/graphql-rust.github.io/issues/8.
