### ISSUE TITLE
batch loading of nested child objects

### ISSUE THREAD

**Issue by hassox** [graphql-rust/juniper#211]
Hi,

I recently found juniper and got a bit excited to try it out. Unfortunately I couldn't find anywhere in the documents to do batch loading of nested children in collections (ala Dataloader style) 

I apologize if I missed it. Is Async batch resolvers supported?

**Comment by LegNeato** [comment]
This discussion may be of use:

https://github.com/graphql-rust/juniper/issues/124

**Comment by LegNeato** [comment]
We are going to write some docs on this, using https://github.com/graphql-rust/juniper/issues/234 to track closing.
