### ISSUE TITLE
Performing multiple operations in a single request

### ISSUE THREAD

**Issue by nick70** [graphql-rust/juniper#214]
How do you send multiple operations in a single request (in rocket for example)?

When I try and execute this query:

```graphql
mutation a1 {
  doSomething(id: "thing") {
    id
  }
}

mutation a2 {
  doSomething(id: "thing_else") {
    id
  }
}
```

I get GraphQLError::MultipleOperationsProvided.
There seems to be unit tests to validate this kind of syntax, but no tests of actually running it.

Thanks

**Comment by LegNeato** [comment]
I haven't personally used it myself, but support was added in https://github.com/graphql-rust/juniper/pull/171 so perhaps reading that might help.

**Comment by nick70** [comment]
I found an example from that pull request (sending an array of operation requests).

https://github.com/graphql-rust/juniper/blob/56f71e934be814722d10b0660156cf56b3753470/juniper/src/http/mod.rs#L267

I should've tried that.

thanks!
