### ISSUE TITLE
Build a warp integration?

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/juniper#215]
seanmonstar just [announced](http://seanmonstar.com/post/176530511587/warp) a new web framework, [warp](https://github.com/seanmonstar/warp), it should be straightforward to build at least an example to show how to make juniper work with it. What do you think? I might try to do it if I find the time since I want to experiment with warp.

**Comment by LegNeato** [comment]
Yeah, just saw it, warp looks great! I am away for the next week so won't have time to take a crack at it myself...if you do, please send a PR as it would be a great addition!

**Comment by tomhoule** [comment]
My attempt at this is in PR https://github.com/graphql-rust/juniper/pull/216

**Comment by LegNeato** [comment]
Landed in https://github.com/graphql-rust/juniper/commit/fd636e07df99744d9964570991bba3ff283f6642. Thanks @tomhoule !

**Comment by LegNeato** [comment]
https://crates.io/crates/juniper_warp has now been published! 🎉
