### ISSUE TITLE
Officially support wasm32-unknown-unknown

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#218]
We appear to work with `wasm32-unknown-unknown`. It would be nice to build with it in CI, as well as have an example where it is used in `node`. I'd be curious as to the perf, as rust/wasm is generally faster than js but most js graphql server implementations are async.

**Comment by theduke** [comment]
The really interesting use case here for me would be `offline` support.

As in, writing your GraphQL backend only once, with some for of compatability layer for database access. 
Compiling the backend down to wasm and then using it in the browser in offline mode would be a pretty rad feature.

**Comment by LegNeato** [comment]
Oh yeah, that would be cool. If the DB was https://realm.io/products/realm-database/ your changes would get transparently synced when you went back online too.

**Comment by theduke** [comment]
@LegNeato guess this can be closed?

**Comment by LegNeato** [comment]
Yeah, I think we are ok for now. I still want to have a node example but that can come later.
