### ISSUE TITLE
Omit field when using derive GraphQLObject 

### ISSUE THREAD

**Issue by sporto** [graphql-rust/juniper#220]
I have a struct like (which doubles as a diesel model):

```
#[derive(Queryable, GraphQLObject, Debug)]
pub struct User {
	pub id: i32,
	pub email: String,
	pub password_hash: String,
	...
}
```

I would like to omit `password_hash` in the generated GraphQl type. 
Is this possible at the moment or do I have to create another Struct? 
A way of omitting some fields would be great.

Thanks.

**Comment by piperRyan** [comment]
There is no way of omitting a field like serde's skip_serializing at this time , but I think one should be able to do 

```rust 
#[derive(Queryable, Debug)]
pub struct User {
	pub id: i32,
	pub email: String,
	pub password_hash: String,
	...
}

graphql_object!(User: () |&self| {
    description: "A user in the database"

    field id() -> &i32 as "The user's unique identifier" {
        &self.id
    }

    field email() -> &String as "The user's email" {
        &self.email
    }

   ... other fields to expose
});
```

However, I have to admit I haven't tried this.
