### ISSUE TITLE
graphql_scalar!() does not support paths in resolve()

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#227]
From @djc on gitter:

> sooo it seems like the return path for resolve() in graphql_scalar!() is not allowed to be a path or whatever
> (I previously wanted to prevent importing Value globally and used juniper::Value instead)

**Comment by djc** [comment]
Thanks for filing! This change:

```diff
@@ -325,8 +329,8 @@ macro_rules! identifiers {
         graphql_scalar!($id {
             description: "Identifier for $t type"
 
-            resolve(&self) -> Value {
-                Value::int(self.0)
+            resolve(&self) -> juniper::Value {
+                juniper::Value::int(self.0)
             }
 
             from_input_value(v: &InputValue) -> Option<$id> {
```

results in pretty obscure errors:

```rust
error: no rules expected the token `parse`
   --> src/models.rs:343:1
```

(I actually have a macro generating the newtypes that I'm using the scalars for, so the error points to the invocation of that macro.)
