### ISSUE TITLE
Failed to compile with uuid

### ISSUE THREAD

**Issue by jaidTw** [graphql-rust/juniper#237]
Not sure am I doing wrong, but I got an error when I was trying to use `uuid::Uuid` in my schema.
```rust
use uuid::Uuid;

#[derive(GraphQLObject)]
struct User {
    ...
    photo: Option<Uuid>
}
```

```
error[E0277]: the trait bound `uuid::Uuid: juniper::GraphQLType` is not satisfied
  --> src/qlschema.rs:10:10
   |
10 | #[derive(GraphQLObject)]
   |          ^^^^^^^^^^^^^ the trait `juniper::GraphQLType` is not implemented for `uuid::Uuid`
   |
   = note: required because of the requirements on the impl of `juniper::GraphQLType` for `std::option::Option<uuid::Uuid>`
```

I've read the source, and as the guide mentioned, there's no any explicity configuration needed, right?
The installed version of juniper is 0.9.2, with uuid 0.6.5, have tried both nightly and stable toolchain.

**Comment by LegNeato** [comment]
Are you using master or the version from crates.io?

**Comment by LegNeato** [comment]
I just confirmed it fails with the release but works with master. I'm trying to get a release out but don't yet have permissions to push (https://github.com/graphql-rust/juniper/issues/210).

In the meantime you should do:

```rust
[dependencies]
juniper = { git = "https://github.com/graphql-rust/juniper.git"}
```

**Comment by jaidTw** [comment]
I will use the master first, thanks!
