### ISSUE TITLE
Juniper panics when custom `FromInputValue` impl for struct returns `None`

### ISSUE THREAD

**Issue by stearnsc** [graphql-rust/juniper#242]
Hi, we're running into an error and I'm not sure if it's a bug in juniper or if we're doing something wrong.

I have a tagged enum I want to deserialize from a graphql input object, something like:
```
enum Foo {
  A(String),
  B(String),
}
```
which should deserialize from 
```
{
    "variant": "A"
    "value": "..."
}
```
To do so, we implemented `FromInputValue` and `GraphQLType` for `Foo` as so:
```
impl FromInputValue for Foo {
    fn from_input_value(v: &InputValue) -> Option<Self> {
        let obj = v.to_object_value()?;
        match (obj.get("variant"), obj.get("value")) {
            (Some(InputValue::String(variant)), Some(InputValue::String(value))) => match variant.as_str() {
                "A" => Some(Foo::A(value.to_owned())),
                "B" => Some(Foo::B(value.to_owned())),
                _ => None,
            },
            _ => None,
        }
    }
}

impl GraphQLType for Foo {
    type Context = ();
    type TypeInfo = ();

    fn name(_: &()) -> Option<&str> {
        Some("Foo")
    }

    fn meta<'r>(_: &(), registry: &mut ::juniper::Registry<'r>) -> ::juniper::meta::MetaType<'r> {
        let fields = &[
            registry.arg::<String>("variant", &()),
            registry.arg::<String>("value", &()),
        ];
        registry.build_input_object_type::<Foo>(&(), fields).into_meta()
    }
}
```
This appeared to work as expected, and ran in production for some time, until a change in the front-end code exposed a bug where "variant" was sent as "C" (an invalid value). Rather than returning a 400 error with a helpful message as we expected when juniper fails to deserialize a value, juniper instead panicked with the message "Argument missing - validation must have failed". I've confirmed that the error seems to occur any time `from_input_value` returns `None` for a type that has a non-zero number of "fields" as the second argument to `build_input_object_type`.

Is this expected behavior? If so, what's the recommended way to do input validation while avoiding panics?

Thanks!

**Comment by LegNeato** [comment]
Sorry about the crash in production! Are you using an integration crate (like `juniper_iron` or `juniper_rocket`) or did you roll your own?

**Comment by stearnsc** [comment]
No worries; just want to prevent it from happening again :). We're using `juniper_rocket`.

**Comment by LegNeato** [comment]
@stearnsc I'm going to dig into this, the behavior is unexpected. What version of juniper are you using? `master` or the latest crates.io release?

**Comment by LegNeato** [comment]
No need, there haven't been any changes in that area. I just wanted to be sure I was looking at the same version

**Comment by LegNeato** [comment]
Nothing obviously wrong when sticking this into a test:

https://gist.github.com/LegNeato/16a4acd56575e23db394e84837d09bcf

I'll keep poking.

**Comment by LegNeato** [comment]
I can repro in the test harness.

**Comment by LegNeato** [comment]
So here is the cause:

* For `InputValues`, we never check if `from_input_value` is `None` when validating.
* Instead we validate every field and "unify".
* In this case, every field is of the correct shape (non-null, has the right fields, etc), so it validates.
* If I check `from_input_value` while unifying, there is an issue. The default derive implementation of `from_input_value` unwraps and thus would panic.

I'm deciding on the best way forward without completely rewriting error handling in the validation step.

**Comment by stearnsc** [comment]
Awesome, thank you for the quick turnaround!
