### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#248]
It was pretty painful releasing 0.10.0.

We should use something like https://github.com/sunng87/cargo-release + cargo make to bump version numbers, update changelogs, etc.

It would be nice to have the book updated too, but that is in a different repo so let's just focus on what is in this repo for now.

**Comment by theduke** [comment]
I actually wanted to create an issue for this too.

PS: maybe we should also move to book in here to have a full on monorepo.
Then we could even run the book example tests on CI.

**Comment by LegNeato** [comment]
Closing this out. Will file new ones as issues come up.
