### ISSUE TITLE
Add support for automatically translating Rust deprecations to GraphQL deprecations

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#250]
Conceptually similar to what we do with descriptions (https://github.com/graphql-rust/juniper/issues/194), we should automatically translate any `#[deprecated]` field in a struct using the derives into GraphQL (https://graphql-rust.github.io/types/objects/defining_objects.html#deprecating-fields).

**Comment by weiznich** [comment]
For anyone interested into this: `wundergraph` already does this, so feel free to "copy" the [implementation](https://github.com/weiznich/wundergraph/blob/master/wundergraph_derive/src/wundergraph_entity.rs#L651) from there.

**Comment by willglynn** [comment]
This was merged in #269.

**Comment by theduke** [comment]
@willglynn thanks for the nudge. ;)

**Comment by tjkirch** [comment]
Is there a way to make this work for input object fields as well, a la https://github.com/facebook/graphql/pull/525?

**Comment by LegNeato** [comment]
Doesn't look like it is currently supported as it isn't in the spec. Feel free to file an enhancement (or a PR!)
