### ISSUE TITLE
Consider changing type names to conform to usual camel case style (e.g. GraphQLType)

### ISSUE THREAD

**Issue by robinst** [graphql-rust/juniper#252]
Camel case in Rust with acronyms usually only upper-cases the first letter. E.g. `Http`, not `HTTP`. `Url`, not `URL`. `Sql`, not `SQL`. That also applies to compound names. Quoted from the [API guidelines](https://rust-lang-nursery.github.io/api-guidelines/naming.html#c-case):

> In UpperCamelCase, acronyms and contractions of compound words count as one word: use Uuid rather than UUID, Usize rather than USize or Stdin rather than StdIn. In snake_case, acronyms and contractions are lower-cased: is_xid_start.

In this crate, there's e.g. [`GraphQLType`](https://docs.rs/juniper/0.10.0/juniper/trait.GraphQLType.html) which does not follow that.

To make it consistent with the usual style, and with the `graphql_object!` macro, it would have to be changed to `GraphqlType`.

(Note that I'm not using this crate (yet), just something I noticed and thought it would be good to bring it up before a 1.0 release.)

**Comment by theduke** [comment]
This also bothered me a little.
GraphQL is an edge case though because it's really short for 'GraphQueryLanguage', so a case can be made for `GraphQL`.

I'd personally like `Graphql*` since it's easier to parse.
I don't think it's worth the churn though before a `1.0` version IMO.

Other thoughts?

**Comment by jgillich** [comment]
+1 for `Graphlql*`. I think it's better to change this now than to be bothered by it forever.

**Comment by LegNeato** [comment]
We won't be fixing this, happy to discuss for 1.0.
