### ISSUE TITLE
Runtime NameParseError ... from code in a macro.

### ISSUE THREAD

**Issue by thedodd** [graphql-rust/juniper#254]
Getting a runtime `NameParseError` from code wrapped in the `graphql_object!` macro. Needless to say, it definitely would seem that this is something we should be catching at compile time. It is in a macro, and appears to be just a bit of string parsing.

The error I was getting:
```
NameParseError("Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"pb::ApiHub\" does not")
```

I was able to correct the issue by adjusting my import to use the name directly without the module namespace. Just wanted to report this as it would seem to be a low-hanging fruit type of issue. Anytime we can avoid runtime issues, it is definitely for the better. 

Also, thanks for all of the awesome work on this project so far!

**Comment by piperRyan** [comment]
The derive macro does, but the `graphql_object` macro doesn't at this time. I am waiting for static assertions to stabilize before adding it in.

**Comment by LegNeato** [comment]
@piperryan is there a rustc bug for the feature we are waiting for?

**Comment by piperRyan** [comment]
The name stuff we should be fine as it just an expression, but If I recall correctly it was also desired to have a better message for types that don't impl GraphQLObject/GraphQLInputObject which will require the assert_impl which is the blocking part, there aren't linked PRs/issues in rustc afaik, but I do remember coming across a couple RFC that needed to implemented in order for the static_assertions to stabilize when I get some time I'll figure out which ones.

**Comment by LegNeato** [comment]
Cool, I just wanted to make sure we were tracking so if it ever hits stable we can leverage it

**Comment by theduke** [comment]
The real reason for this, if I understand correctly, is the way the macros are written.

The pattern for fields is always like: `field $name:ident $args:tt`.

Note that the `$args` token tree is not surrounded by `()`.
This could relatively easily be rewritten.
