### ISSUE TITLE
Add a changelog to `juniper_warp`

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#268]
I just merged a breaking change (https://github.com/graphql-rust/juniper/commit/95dc436bb313ac3031b3dc4d9f3462b1842e2c17). We should have a changelog.

**Comment by LegNeato** [comment]
Also https://github.com/graphql-rust/juniper/commit/edecb8c99fff00aaa3a13eede8f8a90992c8687f should be added as a breaking change.

**Comment by tomhoule** [comment]
I will do this soon if nobody else takes this first :)
