### ISSUE TITLE
database ORM generation

### ISSUE THREAD

**Issue by gedw99** [graphql-rust/juniper#272]
It would be amazing if the project supporting talking to database like Prisma does.

https://github.com/prisma/prisma

The graphql schema has enough information to also manage the database tables, relations and migrations. See the excellent prisma docs. They are very well written and you can see how everything works quickly.
https://www.prisma.io/docs/data-model-and-migrations/data-model-knul/

´

**Comment by piperRyan** [comment]
I think this is what [wundergraph](https://github.com/weiznich/wundergraph) is trying to achieve so you'll probably want to check that project out.

**Comment by LegNeato** [comment]
Yep, out of scope for Juniper but wundergraph looks great. We've taken a lot of changes to support it.
