### ISSUE TITLE
Add playground integration?

### ISSUE THREAD

**Issue by mwilliammyers** [graphql-rust/juniper#274]
I saw in #230 playground integration was removed along the way. Is that just because it would need to be refactored into a central `playground_source` function similar to [`graphiql_source`](https://github.com/graphql-rust/juniper/blob/4be687f73eeb8c80044f542dfea49910e8347a71/juniper/src/http/graphiql.rs#L4-L66) or because of some other reason?

Playground has a lot more features than graphiql, like the ability to set/copy http headers (which is necessary for many APIs), so it would be nice to have... 

Although it looks like juniper's graphiql implementation allows sending the auth header? It still would be nice to have playground support out of the box.

**Comment by LegNeato** [comment]
Yep! Happy to take a PR that adds it.
