### ISSUE TITLE
How to return error form graphql_object field resolver?

### ISSUE THREAD

**Issue by alexfedoseev** [graphql-rust/juniper#276]
E.g.

```rust
// `num` must be returned on request
field num() -> f64 {
  // but in DB it is nullable col
  self.num.unwrap()
}
```

It seems I can only panic in this case? (or return `Option` and then handle it in all other places)

**Comment by kestred** [comment]
See the examples from the Error Handling page in the [guide book](https://graphql-rust.github.io/types/objects/error_handling.html).

**Comment by alexfedoseev** [comment]
Duh, RTFM :) Thanks!
