### ISSUE TITLE
 Which graphql client fits better with Juniper?

### ISSUE THREAD

**Issue by nerdyadventurer** [graphql-rust/juniper#279]
I would like to know which graphql client fits better with Juniper, **Apollo GraphQL client**  OR **Relay Modern**?

**Comment by LegNeato** [comment]
It should work fine with either. Note that Juniper doesn't directly support Relay in the library, you either need to encode the Relay semantics yourself or use a helper library like https://github.com/bbqsrc/juniper-relay. We also have a task to make integrate better with `graphql-client`: https://github.com/graphql-rust/graphql-client/issues/20
