### ISSUE TITLE
Unable to import macros individually [regression]

### ISSUE THREAD

**Issue by andy128k** [graphql-rust/juniper#296]
With 0.11.0 release it is again required to write `#[macro_use] extern crate juniper;`. With version 0.10.0 import of macro worked well. 

Bisect shows [this commit](https://github.com/graphql-rust/juniper/commit/2e5df9f8a469943d694a1deb67910cbbdcd6cae4) as a reason.

**Comment by theduke** [comment]
Ah also, since we bumped minimum to 1.30 anyway, we can stop using `local_inner_macros` and instead use the `$crate::` method as described here: https://rust-lang-nursery.github.io/edition-guide/rust-2018/macros/macro-changes.html

**Comment by theduke** [comment]
Ok I believe the macro issues should be fine now.

Except an issue with the custom_derives in the 2018 edition: 
the module import hack we use in custom derives to make them work both inside and outside of the juniper crate fails.
The [use_everything](https://github.com/graphql-rust/juniper/blob/dee849c88bdba23f1a5d4418e777d8754bea6eb9/juniper/src/lib.rs#L132) macro somehow does not work properly anymore and none of the types can be found.

**Comment by theduke** [comment]
Fixed and published as `0.11.1`.
