### ISSUE TITLE
ScalarValue custom derive: newtype support

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#303]
Extend the `(GraphQL)ScalarValue` custom derive to support newtype structs.

This should work similar to how serde does it with [#[serde(transparent)]](https://serde.rs/container-attrs.html#transparent).

(I'm working on this).

Example:

```rust
#[derive(GraphQLScalarValue)]
struct MyCustomId(Uuid);
```

**Comment by mwilliammyers** [comment]
Are you still working on this or should I take a crack at it?
