### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#304]
It would be nice to have a few testimonials in the repo / on the book.

So let's collect a list of projects (preferably large and in production).

**Comment by 0xcaff** [comment]
Not really large or in production yet, but we're using graphql to build a personal media streaming platform. https://github.com/forte-music/core

**Comment by Swoorup** [comment]
Would really like to use juniper, but I think, lot of boilerplate needs to go away via proc macro
