### ISSUE TITLE
Refactor example schema to be less confusing

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#308]
The example star wars schema always bugged me in one point:

It's very confusing for new users that the Query type is also the Database.
It's much easier to understand if the Database were a separate type.

This is relatively easy to do but quite a bit of work because it's used in many places.

**Comment by ELD** [comment]
@theduke I'd be interested in helping out with this issue if you're still looking for someone to champion it.

I recently got through building an example for use with Rocket (#68) and have a decent grasp of decoupling the Query, Mutation, and Database types from one another.

**Comment by theduke** [comment]
Hey @ELD , sure, your help would be much appreciated.
