### ISSUE TITLE
Move book into main repo

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#309]
We'll never keep the book up to date if it's not in the main repo and built on CI.

So we should:

* [ ] move the book from https://github.com/graphql-rust/graphql-rust.github.io into this repo under /book
* [ ] fix up the compile tests of the book, which are not running properly ATM
* [ ] extend the CI to build the book tests
* [ ] update the book where appropriate
* [ ] extend the release scripts to bump version numbers in the book

**Comment by LegNeato** [comment]
@theduke you said you had a PR for this?
