### ISSUE TITLE
I cannot describe the fields

### ISSUE THREAD

**Issue by dancespiele** [graphql-rust/juniper#311]
I try to describe the fields for documentation but it doesn't work or I'm no doing correctly,

I have this that compile fine:

```rust
#[derive(Serialize, Queryable, Debug, GraphQLObject)]
#[graphql(description="The person and his or her skills")]
#[graphql(field="findPerson", description="Find a person with the name given")]
#[graphql(field="people", description="Show all the people saved in the database")]
pub struct Person {
    pub id: String,
    #[graphql(description="Name of the person")]
    pub name: String,
    pub super_power: bool,
    pub rich: bool,
    pub genius: bool,
}
```

but i cannot see the docs description in graphiql.

**Comment by LegNeato** [comment]
Hmmm, not sure what you are trying to do here, but...

Usually you have two objects, one for your entity/"thing" and one for your query. So something like:

```rust 
/// The person and his or her skills
#[derive(Serialize, Queryable, Debug, GraphQLObject)]
pub struct Person {
    pub id: String,
    /// Name of the person
    pub name: String,
    pub super_power: bool,
    pub rich: bool,
    pub genius: bool,
}

graphql_object!(Query: Context |&self| {

    /// Find a person with the name given
    field findPerson() -> FieldResult<Person> {
       // Do your logic...
       unimplemented()!
    }

    /// Show all the people saved in the database
    field people() -> FieldResult<Vec<Person>> {
       // Do your logic...
       unimplemented()!
    }
});
```

Note that you can either use the annotation (`graphql(description="...")`) or standard rust doc comments as mentioned in https://graphql-rust.github.io/types/objects/defining_objects.html.

Let me know if that fixes it or is unclear.

**Comment by dancespiele** [comment]
Thank you @LegNeato. Now I can see the description of the fields in graphiql, but how can implement docs description for `QueryRoot` and `MutationRoot` ?  I tried this

```rust
/// Queries
pub struct QueryRoot;
```

and

```rust
graphql_object!(QueryRoot: Context |&self| {
  // more stuffs
}
```

but doesn't work

**Comment by theduke** [comment]
See the documentation for the graphql_object macro: https://docs.rs/juniper/0.11.1/juniper/macro.graphql_object.html#documentation-and-descriptions
