### ISSUE TITLE
Extract parser into its own crate

### ISSUE THREAD

**Issue by ianks** [graphql-rust/juniper#32]
Hey there! I am interested in using the parser from this library in one of my own projects. Would it be possible to extract it into its own crate? Great work on this project, and hope to hear from you soon.

Ian

**Comment by mhallin** [comment]
This would be a nice improvement - not just for the use case of using the parser or type system outside of this project - it would probably cut down on compilation time for the test suite when working on isolated parts.

I imagine looking at the setup used by e.g. [gluon](https://github.com/Marwes/gluon) would be useful; we probably would want the entire source code to still live in this repository and all released in lockstep with each other.

I'll see what I can do. Hopefully something that can be done before the 1.0 release.

**Comment by theduke** [comment]
Now that the repo is restructured, a good next step would be to extract the parser into it's own crate.

**Comment by pyros2097** [comment]
Just had a look at it. It seems the parser depends on the ast. So I guess that has to be moved into the parser.

**Comment by mitchtbaum** [comment]
See also [graphql-parser](https://github.com/Keats/graphql-parser) which uses [pest](https://github.com/pest-parser/pest).

**Comment by tailhook** [comment]
By the way, is there any reasons why you didn't use a parser library such as [combine](https://crates.io/crates/combine) (the one which I recommend) ? Is there any complexities with the grammar?

**Comment by tailhook** [comment]
Everybody watching this issue might be interested in #138

**Comment by theduke** [comment]
Tracked in #138
