### ISSUE TITLE
FieldResult should implement GraphQLType

### ISSUE THREAD

**Issue by jgillich** [graphql-rust/juniper#320]
I wanted to return `Option<FieldResult<Foo>>` from a field, but I can't because FieldResult doesn't implement GraphQLType. Thoughts? I could probably do the PR (assuming this is even possible, didn't really look into it).

**Comment by LegNeato** [comment]
I'm not sure that would make sense. `FieldResult` is analogous to `Result`. You might actually want `FieldResult<Option<Foo>>`, which means that the field can possibly fail to resolve (the `FieldResult` bit) but if it does resolve it either returns nothing (`None` in the `Option`) or `Foo` (`Some` in the `Option`).

Let me know if that isn't what you are trying to do or if I misunderstand.

**Comment by jgillich** [comment]
I have a field that can either:

* Not have a value
* Have a value that is a link to another object - but then the resolver might fail

So the most correct return type would be Option<FieldResult>. However, I didn't think of trying FieldResult<Option>, and I think that's fine as well. Makes no difference in the actual API anyway. Thank you!

**Comment by JeanMertz** [comment]
I ran into this issue while researching a problem I was facing.

I'm not a fan of using too many macro's in my code-base (for a lack of clarity, and usually a lack of informative compiler error messages), so I wanted to implement `GraphQLType` myself.

The documentation states "Manually deriving an object is straightforward but tedious".

I ran into an issue where I wanted to manually derive a `FieldResult<T>`. I was unable to do so using something like:

```rust
registry.field<FieldResult<Vec<&MyT>>>("my_t", info)
```

As it returned:

```
the trait `GraphQLType` is not implemented for `Result<Vec<&MyT>, FieldError>`
```

I had to dig into the `graphql_object` macro to find that the macro in fact [uses `field_convert`](https://github.com/graphql-rust/juniper/blob/f02e427cabe5b4cffe0758cff61063200fcd7dae/juniper/src/macros/object.rs#L363-L366) to make this work, which is a hidden (but public) API.

Am I doing something wrong here, or is this the correct way to use a `FieldResult<T>` in a manually derived `GraphQLTYpe`?

**Comment by theduke** [comment]
As @LegNeato said, having a field with a `FieldResult<T>` type does not make any sense, since `FieldResult` does not exist as a type for GraphQL, it is just a way of expressing if a field succeeded or failed to resolve. 

The proper way is to have the field type as `Option<T>` and return a `FieldResult<Option<T>>` from from the resolver, or manually return the error if you are implementing it yourself.

**Comment by theduke** [comment]
@JeanMertz if you are manually implementing `resolve_field` anyway, you can just return the `ExecutionError` in case the execution fails, no?

**Comment by JeanMertz** [comment]
Ah thanks @theduke, that's great, and it works flawlessly, thank you for this 👍

(documentation is still a bit lacking, I had to dig through the tests to find how to rename a field, as it only showed how to rename the object itself, but other than that, it worked as expected)

**Comment by theduke** [comment]
There is some more extensive documentation on the `juniper::object` macro (`cargo doc --open`, it's not online yet).

But thanks for pointing it out, I'll add that to the book.
