### ISSUE TITLE
enum(T) value type

### ISSUE THREAD

**Issue by jgillich** [graphql-rust/juniper#321]
My API returns currency exchange rates, so naturally, I have an enum like this:

```rust
enum CurrencyCode {
    USD,
    EUR,
    JPY,
    // about a thousand more
}
```
I could return this as a `Vec<struct { code, rate }>`, but this would always return all rates in queries, which I do not want. So what I have now is another struct that allows you to selectively request the rates you want:

```rust
#[derive(GraphQLObject)]
pub struct ExchangeRates {
    pub USD: f64,
    pub EUR: f64,
    pub JPY: f64,
    // ...
}
```
And I do have to match between the two, so there's another huge block of code.

I guess I could write a macro for this..buuut, I wonder if this couldn't be supported by Juniper itself. We already have basic enum support, so maybe we could add support for enums with a single value tuple? Or, alternative, support HashMap<enum, T>?

Or maybe there's a better way to do this, not sure.

**Comment by mrceperka** [comment]
Have you tried this: https://graphql-rust.github.io/types/enums.html?

**Comment by jgillich** [comment]
That only works with enum as a value, I want to use enum as a key.

**Comment by mrceperka** [comment]
So you wanna support something like this?
```gql
query exchangeRates {
  eur {
    rate
  }
}
```?

What about this? I this that following example/query could solve your issue.
```gql
query exchangeRates(code: eur) {
  rate
}
```

**Comment by jgillich** [comment]
No, what I have is this:
```

currency {
  exchangeRates {
    EUR
    USD
    GBP
  }
}
```
See the ExchangeRates struct from above. :)

**Comment by mrceperka** [comment]
I get it. I just wanted to know if you could change your api.
You can also query like this. Just a suggestion.
```gql
currency {
  exchangeRates(code: EUR) {
   rate
  }
}
```

**Comment by theduke** [comment]
I'm not exactly sure what you are asking for here in terms of features.

In GraphQL, A map can not have enum keys, only strings.
Also, this would not actually help here much as far as I can see.

I don't see anything here that could be directly supported by Juniper.

Also a note: having a struct with thousands of fields can be really bad for performance. 

I see two options here:


## Option A: struct with macro

Use a struct, but without actual fields.

```rust
pub struct ExchangeRates;

graphql_object!(ExchangeRates: Context |&self| {
    field EUR(&exector) -> String {
       executor.context().get(CurrencyCode::EUR)
    }
}
```

It would be very easy to write a macro for this to both define the enum and create a field for each currency.

If you need help with this just ask.


## Option B: filter

The one already suggested, using an argument to filter out the wanted currencies:

```graphql

type ExchangeRate {
  currency CurrencyCode!
  rate String!
}
query {
  exchangeRates(currencies: [CurrencyCode!]!) {
    currency
    rate
  }
}
```

**Comment by theduke** [comment]
I'm closing this as it seems to be non-actionable for me.

Feel free to continue discussion.

**Comment by jgillich** [comment]
I managed to implement this nicely using [strum](https://docs.rs/strum/0.14.0/strum/).

```rust
#[derive(Clone, Eq, PartialEq, Hash, EnumString, EnumIter, Display)]
enum CurrencyCode {
    USD,
    EUR,
}

pub struct ExchangeRates(HashMap<CurrencyCode, f64>);

impl GraphQLType for ExchangeRates {
    type Context = crate::Context;
    type TypeInfo = ();

    fn name(_: &()) -> Option<&'static str> {
        Some("ExchangeRates")
    }

    fn concrete_type_name(&self, _context: &Self::Context, _info: &Self::TypeInfo) -> String {
        String::from("ExchangeRates")
    }

    fn meta<'r>(_: &(), registry: &mut Registry<'r>) -> MetaType<'r>
    where
        DefaultScalarValue: 'r,
    {
        let fields = &CurrencyCode::iter()
            .map(|f| registry.field::<&f64>(&*f.to_string(), &()))
            .collect::<Vec<Field<'_, DefaultScalarValue>>>()[..];

        registry
            .build_object_type::<ExchangeRates>(&(), fields)
            .into_meta()
    }

    fn resolve_field(
        &self,
        info: &Self::TypeInfo,
        field_name: &str,
        _args: &Arguments,
        executor: &Executor<crate::Context>,
    ) -> ExecutionResult {
        executor.resolve_with_ctx(info, &self.0[&CurrencyCode::from_str(field_name)?])
    }
}
```
