### ISSUE TITLE
Rocket example does not build outside of repo

### ISSUE THREAD

**Issue by crashspringfield** [graphql-rust/juniper#322]
**Describe the bug**
When I try running the Rocket example, I get the following error:

    content::Html(juniper::http::playground::playground_source(
                                              ^^^^^^^^^^ could not find `playground` in `http`

**To Reproduce**
* `cp -r ./juniper/juniper_rocket ./test_project`
* `cd test_project`
* `cp examples/rocket_server.rs src/main.rs`
* remove the paths from Juniper in Cargo.toml
* `rustup override add nightly`
* `cargo run`

**Expected behavior**
A successful build

**Additional context**
I updated Cargo.toml to `juniper = { version = "0.11.1" , default-features = false}` hoping it would include #317 because I see [where it exists in the repo](https://github.com/graphql-rust/juniper/blob/master/juniper/src/http/playground.rs) but that didn't work.

I was, however, able to get the project running from within the repo following these steps: 
* `cd juniper/juniper_rocket`
* `cp examples/rocket_server.rs src/main.rs`
* `rustup override add nightly`
* `cargo run`

**Comment by theduke** [comment]
This is due to https://github.com/graphql-rust/juniper/pull/317, which added the playground integration.

It just wasn't released yet and is only in master.

You can use a git dependency for now if you don't want to wait for the release.

```toml
juniper = { git = "https://github.com/graphql-rust/juniper.git" }

```
