### ISSUE TITLE
juniper_codegen in documentation

### ISSUE THREAD

**Issue by WillSquire** [graphql-rust/juniper#332]
`juniper_codegen` is referenced in the docs: https://graphql-rust.github.io/types/objects/defining_objects.html but looks like its inclusive to `juniper`: https://docs.rs/juniper_codegen/0.11.1/juniper_codegen

Assume the docs example should be `#[macro_use] extern crate juniper;`

**Comment by LegNeato** [comment]
Thanks! Yep, we need to change that. We are [pulling the book into the repo](https://github.com/graphql-rust/juniper/pull/330) so will address this after!

**Comment by WillSquire** [comment]
Wow, that was a fast response! Great, and awesome repo by the way *thumbs_up*

**Comment by theduke** [comment]
This is fixed in #330 which is tracked by #309 so I guess we can close this.
