### ISSUE TITLE
Question / Support Request:  Does juniper support defining the `ofType` for scalars?

### ISSUE THREAD

**Issue by kestred** [graphql-rust/juniper#336]
Just the question in the subject line... but to restate it:

> Does juniper support defining what `ofType` a custom scalar results in when querying the introspection schema?

**Comment by LegNeato** [comment]
Not sure, but possibly via the custom representation support we have. Can you explain more why and maybe I can answer definitively?

**Comment by kestred** [comment]
Apologies... I tricked myself into thinking one of the graphql spec RFCs had already merged (https://github.com/graphql/graphql-spec/pull/521/files).

Not an issue unless it gets approved 😅 .

Thanks for the followup 🙏 !
