### ISSUE TITLE
Fix up the book building on CI

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#343]
Need to do two things:

* Make the automatic build/push work for both master and for release tags

* Enable the `linkcheck` "plugin" for mdbook
  This is a bit awkward because it has no binary release, so we'd need to `cargo install` it, which   also requires `cargo install` for `mdbook` itself due to version incompatabilities. (there is no binary release for mdbook `0.2.3` 
  
  So we might want to only run the linkcheck on master and not on each PR.

**Comment by LegNeato** [comment]
I assume we are using https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users ?

**Comment by theduke** [comment]
No, a deploy key: https://github.com/graphql-rust/juniper/settings/keys

The thing I got stuck on was just the Pipelines task to install the key. 
It wouldn't recognize the secret variables no matter what I did.

**Comment by LegNeato** [comment]
Ah, ok. I'll maybe poke at it tonight

**Comment by LegNeato** [comment]
Ok, got `master` push working: https://graphql-rust.github.io/juniper/master/
