### ISSUE TITLE
Visualization tooling compatibility

### ISSUE THREAD

**Issue by tupshin** [graphql-rust/juniper#35]
Is there some way for Juniper to be compatible with tools like https://github.com/sheerun/graphqlviz or https://github.com/APIs-guru/graphql-voyager ?
Check out https://apis.guru/graphql-voyager/ if you haven't previously.

I did try pointing graphqlviz at a juniper instance (with the star wars model), but was getting errors about some aspects of the juniper schema that graphqlviz didn't like.

**Comment by mhallin** [comment]
Yeah, definitely!

At a glance, there seem to be two separate issues:

* The [reference implementation's introspection query](https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js) contains a reference to `subscriptionType` which is not part of the standard, and not something that Juniper currently supports. We could add a `null` placeholder in our meta schema to satisfy these non-standard queries.
* GraphQLviz seems to be using an older version of the reference implementation, where the `location` field on directives was specified as three booleans: `onOperation`, `onFragment`, `onField`. We could probably add these three fields and mark them as deprecated to satisfy these queries.

GraphQL Voyager doesn't seem to be sending introspection queries by itself, but it uses the reference implementation's functions to build a schema from the result of such a query, so it would at least suffer from the first of these problems.

**Comment by tupshin** [comment]
I'm playing with gluing together a db backend to a graphql api, and being able to visualize it with voyager out of the box would be absolutely amazing. Big :+1: to just stubbing out what's necessary to make it not error out.

**Comment by LegNeato** [comment]
I believe this was fixed a bit ago...please open a new issue if it is not.
