### ISSUE TITLE
How are file uploads handled in juniper?

### ISSUE THREAD

**Issue by japrogramer** [graphql-rust/juniper#363]
Hello, there is an apollo client that attaches attachments to the post.
I would like to know if juniper can handle this new format.
I know that it would require separating the query and vars from the form data
and ideally attaching the file to the node as it is done now in python.

**Comment by theduke** [comment]
Are you refering to https://github.com/jaydenseric/graphql-multipart-request-spec ?

No support for this is currently implemented.

What I would do is upload the file separately to an endpoint that returns a id/uuid and pass that id into a GraphQL request.

**Comment by japrogramer** [comment]
Yes, that is what im referring to. 
That could work for now, I guess i than also have to handle the case if something errors out
in the graphql endpoint to clean up the orphan files.

**Comment by LegNeato** [comment]
I don't think this is part of GraphQL and is instead Apollo's implementation details that they are leaking and trying to get the rest of the GraphQL community to adopt.

Would love to be pointed to an official proposal if there is one.

**Comment by theduke** [comment]
Yeah this is non-standard and not on the horizon.

Non actionable for us at the moment.

Note that you could implement this yourself for the web server of your choice, and then ,for example, putting the relevant data (tmp file path, some read buffer) into the `Context.

**Comment by Asone** [comment]
> Yeah this is non-standard and not on the horizon.
> 
> Non actionable for us at the moment.



Hi,

I'd like to know if this is still considered as non actionable.

> Are you refering to something like https://github.com/jaydenseric/graphql-multipart-request-spec ?

 I know the mentioned specification is non-standard, however it is currently the only specification that exists, and even if not official, many graphQL libraries implement it ( Apollo, Altair, async-graphql for example ), and as the mentioned answers are almost 3 years old from now i thought maybe an implementation of the spec could be worth a shot. 

> Note that you could implement this yourself for the web server of your choice, and then ,for example, put the relevant data (tmp file path, some read buffer) into the `Context` on into the request variables (path/id only).

I've written what could be somewhat a draft of such implementation for Rocket web servers that is available [here](https://github.com/Asone/graphQLN/tree/28-handle-file-upload-with-graphql/juniper_rocket_multipart_handler). 

The implementation seems to work fine, yet it probably be improved and still lacks unit testing. 

I'm wondering if this could be any help about the topic and if it could be worth being  either the base of a contribution or a complementary crate. 

Any feedback will be much appreciated. 

Thanks !
