### ISSUE TITLE
Improve ergonomics of ID scalar type

### ISSUE THREAD

**Issue by JeanMertz** [graphql-rust/juniper#365]
I came here looking into the ergonomics of `ID`.

Given that the Juniper book states:

> `juniper::ID` as ID. This type is defined in the spec as a type that is serialized as a string but can be parsed from both a string **and an integer**.

(emphasis mine)

It seems to be quite cumbersome to go from an integer to an ID:

```rust
ID::new(self.id.to_string())
```

Would it make sense to:

* make the inner string `pub`, so we don't need `new`, and
* make it `ID<T>(T) where T: ToString`

Making the above more trivial:

```rust
ID(self.id)
```

I don't think these changes would be breaking changes, would they?

**Comment by JeanMertz** [comment]
Also, it would be nice if `Serialize` and `Deserialize` were derived/implemented for this type.

See: https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#data-structures-implement-serdes-serialize-deserialize-c-serde

> Types that play the role of a data structure should implement `Serialize` and `Deserialize`.

(and since it looks like this crate already depends on `serde`, there's no need for a feature flag for this)

**Comment by LegNeato** [comment]
These sound like good changes to me. Let's keep the field private for now...calling new isn't a bug burden but leaves flexibility if we need to change implementation later.

**Comment by theduke** [comment]
Note that the IDs also need to be converted from input values, so the trait bound will have to be:

```rust
struct ID<T: ToString + std::str::FromStr>(T)
```

The `graphql_scalar!` impl for ID will need to be updated to handle this accordingly.

**Comment by theduke** [comment]
Also note: this is in fact a breaking change, due to the added `FromStr` bound.

**Comment by JeanMertz** [comment]
I'm not sure what you'd like me to do about the breaking change in this proposal, but I went ahead and submitted a PR for de serialize/deserialize implementations, as those shouldn't cause any problems.

**Comment by theduke** [comment]
@JeanMertz  we will have plenty of breaking changes coming up, so if you are interested you can go ahead and implement the other changes as well.
