### ISSUE TITLE
Support customer headers in graphiql editor

### ISSUE THREAD

**Issue by lpil** [graphql-rust/juniper#369]
Often we want our graphql endpoints to be behind header based authentication so that we can protect private data and identify the user. This becomes a problem when we wish to use the graphiql for development/testing/documentation because there is no way of setting the required authentication header.

I would like to be able to supply additional headers for graphiql to use when making requests to the graphql endpoint.

I was thinking that perhaps we could add a `juniper::graphiql::graphiql_source_with_config` or similar that takes the endpoint (as before) and a struct of options which (for now) has one field request_headers: `Vec<(String, String)>`.

These headers would then be added to the headers used in the graphiql fetcher https://github.com/graphql-rust/juniper/blob/2ea7d9b46e6f7c88de3dd3bd31402fd6251648e5/juniper/src/http/graphiql.rs#L20-L23

Each of the web frameworks would then need to be updated to expose a handler for this new graphiql function for developers to use.

I would be happy to contribute this change if it is likely to be merged.

**Comment by davidpdrsn** [comment]
I have hit a similar issue. I got around it by overriding the JavaScript function that makes the request. Here is my code https://gist.github.com/davidpdrsn/f74824dd6b5b4c0018b6ea5994eafec5

This is of course not clean, but does get the job done.

**Comment by jdno** [comment]
The GraphQL Playground supports HTTP headers out of the box. Can't you use that instead?

**Comment by lpil** [comment]
Graphiql does too and juniper is already using this feature, as shown in the code linked above :)

**Comment by michalbe** [comment]
What's wrong with using `playground` in place of `graphiql`? It's already [in juniper's source](https://github.com/graphql-rust/juniper/blob/master/juniper/src/http/playground.rs).

**Comment by theduke** [comment]
I think the best approach to this is using [GraphQL Playground](https://github.com/prisma/graphql-playground) which as @michalbe mentioned is already in the repo.

`juniper_warp` has the `playground_filter` function, rocket has `playground_source`.

**Comment by dallen4** [comment]
When I use GraphQL Playground and try to use the "Schema" or "Docs" feature sidebars they just load infinitely. Is this expected behavior? Is Juniper missing some support for parsing the schema and generating documentation for the playground client?

**Comment by theduke** [comment]
Please check the console and the HTTP request for errors. It's possible that there is some issue with the introspection query.
