### ISSUE TITLE
__typename fails on root query type

### ISSUE THREAD

**Issue by saolsen** [graphql-rust/juniper#372]
**Describe the bug**
I get an error 'concrete_type_name must be implemented by unions and interfaces' when  trying to query `__typename` on the  root query type.

**To Reproduce**
Query type is defined like this.
```
pub struct Query;

#[object(
    name = "Query",
    Context = Context,
)]
impl Query {
    fn foo() -> FieldResult<String> {
        Ok("Hello World".to_string())
    }
}
```

Then a query like `{ __typename }` fails with the error above.

**Expected behavior**
I would  expect it to return "Query"

**Comment by LegNeato** [comment]
Ha, I just hit this with `cargo-fuzz`! Cool that it ended up generating the same thing that humans did.

**Comment by tyranron** [comment]
No longer reproduces on `master`.
