### ISSUE TITLE
Any way to auto-generate struct field resolvers, and also hand-write a custom one?

### ISSUE THREAD

**Issue by hrbigelow** [graphql-rust/juniper#377]
Is there a way to have all fields of a struct have auto-generated resolvers, as provided by #[derive(GraphQLObject)], but be able to custom-derive a few more, as can be done with graphql_object! macro?

Since the two techniques don't mix, it seems the only choice is to use graphql_object! macro, and hand-write all of the trivial resolvers along with the custom ones.

**Comment by LegNeato** [comment]
I don't believe there is. Happy to review a PR!

**Comment by theduke** [comment]
This is much wanted and there are multiple paths to this.

One option, merging definitions, is discussed in #182 .

My personally preferred way forward would be to apply a proc macro to a whole module to make this easy.

This is currently only possible on nightly with the `proc_macro_hygiene` feature.

I'd want us to have code like this and make it just work:

```rust

#[juniper::module]
mod graphql {
  #[derive(GraphQLObject)]
  struct MyType {

  }
  
  #[juniper::object]
  impl MyType {
    fn extra_resolver() -> bool { true } 
    ....
  }
}

```

**Comment by hrbigelow** [comment]
Hi Christian,

That's great to hear there is interest in this.  At the moment my macro
writing skills are not up to the task, but if that changes, I'll try to do
it.  Incidentally, I did also try to write another unrelated macro, but
noticed that it doesn't work when called from within the graphql_object!()
call.

Cheers,

Henry

**Comment by LegNeato** [comment]
@theduke I like the module idea. Can we leverage the new(ish) "extends" keyword here?

**Comment by theduke** [comment]
Let's track this in #182 .
