### ISSUE TITLE
Incorrect http test data

### ISSUE THREAD

**Issue by Jekshmek** [graphql-rust/juniper#379]
**Describe the bug**
[Module juniper::http is not a valid data]

"/?query=%7Bhero%7Bblah%7D%7D" does not match "{hero {blah}}"

```rust
    fn test_invalid_field<T: HTTPIntegration>(integration: &T) {
        // {hero{blah}}
        let response = integration.get("/?query=%7Bhero%blah%7D%7D");
        assert_eq!(response.status_code, 400);
        let response = integration.post("/", r#"{"query": "{hero{blah}}"}"#);
        assert_eq!(response.status_code, 400);
    }
```
[Module juniper::http is not a valid data]:https://github.com/graphql-rust/juniper/blob/49f723a3ddb3ee64b79d3f53388ae3804f9f7e35/juniper/src/http/mod.rs#L332

**Comment by tyranron** [comment]
@LegNeato this one can be closed. It's OK in latest `master`.
