### ISSUE TITLE
Using variables produces invalid value errors

### ISSUE THREAD

**Issue by jatsrt** [graphql-rust/juniper#390]
**Describe the bug**
When using "variables" to sent a nested/complex object, the request fails with "got invalid value"

**To Reproduce**
```
mutation {
  update(update: {where: {id: "xxxxxxxxxx"}, data: {bedrooms: 1, location: {lat: 41.2 lon: -87.6}}}) {
    id
  }
}
```
vs
```
mutation Update($update: Update!) {
  update(update: $update) {
    id
  }
}

{"update": {
  "where": {
    "id": "xxxxxxxxxx"
  },
  "data": {
   "bedrooms": 1, "location": {"lat": 41.2, "lon": -87.6}
  }
}
}
```

Produces the errors like:
```
{
      "message": "Variable \"$update\" got invalid value. In field \"data\": In field \"bedrooms\": Expected \"Int\".",
      "locations": [
        {
          "line": 1,
          "column": 17
        }
      ]
    }
```

**Expected behavior**
Should work/parse the same as the first example.

**Comment by LegNeato** [comment]
Interesting. To clarify, `Update` is an `InputObject` consisting of the content from the first example (which works)?

**Comment by jatsrt** [comment]
Correct

**Comment by jatsrt** [comment]
More testing, enums work, chrono date time works. Right now just Int and Float seem to be the issue

**Comment by jatsrt** [comment]
Running it as a test using the following works too. Status and propertyType are enums, bedrooms is i32/Int

```rust
&vec![
                (
                    "where".to_owned(),
                    InputValue::object(vec![("id", InputValue::scalar("xxxxxxxxx"))].into_iter().collect()),
                ),
                (
                    "data".to_owned(),
                    InputValue::object(
                        vec![
                            ("status", InputValue::scalar("OTHER")),
                            ("propertyType", InputValue::scalar("OTHER")),
                            ("bedrooms", InputValue::scalar(1)),
                        ]
                        .into_iter()
                        .collect(),
                    ),
                ),
            ]
            .into_iter()
            .collect(),
```

**Comment by jatsrt** [comment]
OK, root cause identified, not sure if it is something juniper should handle or not though.  
One of my deep dependencies sets `serde_json = { version = "1.0", features = ["arbitrary_precision"] }`

This changes the behavior globally and causes the input validation for numbers only to fail.

**Comment by LegNeato** [comment]
Ugh, that is annoying! Looks like this could be https://github.com/serde-rs/json/issues/505 ?

**Comment by LegNeato** [comment]
What server integration are you using this with? I might try the workaround in that bug.

**Comment by jatsrt** [comment]
Warp, the serde_json config was due to an internal library that was a dependency of a dependency.

**Comment by saskenuba** [comment]
I'm having the same issue. My queries accepting i32 on parameters always return errors such as:
`"message": "Variable \"$assetsToDeposit\" got invalid value. In element #0: In field \"appid\": Expected \"Int\"."`.

And this doesn't matter if it is an input object or a raw scalar, neither works. But if I parse them from a String, it works normally.

Query:
```
query DepositRequest($assetsToDeposit: [AssetNewTradeOffer!]!) {
  depositRequest(assetsToDeposit: $assetsToDeposit)
}
```

Variables:
```JSON
{
	"assetsToDeposit": [
		{
			"appid": 730,
			"contextid": 2,
			"assetid": ["17099917172"],
			"price": "100"
		}
	]
}
```

Response:
```JSON
{
  "errors": [
    {
      "message": "Variable \"$assetsToDeposit\" got invalid value. In element #0: In field \"appid\": Expected \"Int\".",
      "locations": [
        {
          "line": 1,
          "column": 22
        }
      ]
    },
    {
      "message": "Variable \"$assetsToDeposit\" got invalid value. In element #0: In field \"contextid\": Expected \"Int\".",
      "locations": [
        {
          "line": 1,
          "column": 22
        }
      ]
    }
  ]
}
```

```rust
#[derive(GraphQLInputObject, Clone, Debug)]
pub struct AssetNewTradeOffer {
    appid: i32,
    contextid: i32,
    assetid: Vec<Long>,
    price: Long,
}

async fn deposit_request(context: &Context, assets_to_deposit: Vec<AssetNewTradeOffer>) -> FieldResult<i32> { ... }
```

After using `cargo tree -e features -i serde_json`, I found that a dependency is using the `arbitrary_precision` feature of `serde_json` as @jatsrt described, but I still haven't disabled it to check if it affects behaviour.

I am not sure if this dep introduced this bug because until now, there were no queries with i32 only strings.
