### ISSUE TITLE
Figure out why testing release automation is failing on CI

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#396]
Not sure why, but suddenly the release automation test job started failing. When I run everything locally it is fine.

**Comment by LegNeato** [comment]
Looks like this is a regression in `cargo-release`. https://github.com/sunng87/cargo-release/issues/129

**Comment by theduke** [comment]
Doesn't look like a regression, it still fails with a pinned `0.11.2` (see PR).

**Comment by theduke** [comment]
The problematic diff is: 

```
diff --git a/juniper_codegen/Cargo.toml b/juniper_codegen/Cargo.toml
index 6ce783fc..10294daf 100644
--- a/juniper_codegen/Cargo.toml
+++ b/juniper_codegen/Cargo.toml
@@ -20,6 +20,7 @@ syn = { version = "0.15.28", features = ["full", "extra-traits", "parsing"] }
 quote = "0.6"
 regex = "1"
 lazy_static = "1.0.0"
+juniper = {version = "^0.14.0"}

 [dev-dependencies]
 juniper = { version = "0.13.0", path = "../juniper" }
```

**Comment by LegNeato** [comment]
Hmmm, I couldn't repro it locally with 0.11.2 but instantly repro'd with the newest version

**Comment by theduke** [comment]
True, was my fault.

**Comment by theduke** [comment]
We'll probably want to explore using the workspace support once https://github.com/sunng87/cargo-release/pull/130 lands.
