### ISSUE TITLE
"Panic when using look ahead from fragment with nested type" has come back in 0.13.0

### ISSUE THREAD

**Issue by davidpdrsn** [graphql-rust/juniper#398]
It seems https://github.com/graphql-rust/juniper/issues/335 has come back in 0.13.0

**Describe the bug**
Given the schema

```graphql
schema {
  query: Query
}

type Query {
  users: [User!]!
}

type User {
  country: Country!
}

type Country {
  id: Int!
}
```

and the query

```graphql
query Query {
    users {
        ...userFields
    }
}

fragment userFields on User {
    country {
        id
    }
}
```

Juniper panics if you call `executor.look_ahead();` inside the `User::country` resolver.

Message is

```
thread 'main' panicked at 'lookahead to find the field', src/libcore/option.rs:1036:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**To Reproduce**
I have made a reproduction script here https://github.com/davidpdrsn/juniper-look-ahead-with-fragments-error. Download that and run `cargo run` to see the panic.

**Comment by theduke** [comment]
Looking into it.
