### ISSUE TITLE
Broken documentation link for "new object macro"

### ISSUE THREAD

**Issue by sssilver** [graphql-rust/juniper#400]
Hi,

https://docs.rs/juniper/0.13.0/juniper/macro.graphql_object.html has a notice at the top that says:

> The `graphql_object!` macro is deprecated and will be removed soon. Use the new[object](https://docs.rs/juniper/latest/juniper/macro.object.html) macro instead.

The hyperlink under "object" points at https://docs.rs/juniper/latest/juniper/macro.object.html which doesn't seem to exist. Searching the docs for a macro named "object" doesn't seem to yield anything either.

**Comment by theduke** [comment]
Thanks for pointing that out, fixed the link.
FYI https://graphql-rust.github.io/juniper/current/types/objects/complex_fields.html also provides more information on the new macro.
