### ISSUE TITLE
Have configurable default output UUID format (simple/hyphenated,etc)?

### ISSUE THREAD

**Issue by hrbigelow** [graphql-rust/juniper#408]
**Is your feature request related to a problem? Please describe.**
The UUID specification allows for both hyphenated and non-hyphenated (and URN?) formats:
`30cb8e40-b44f-4155-a93c-134eea428651`
`30cb8e40b44f4155a93c134eea428651`

Juniper currently can *parse* any of the valid formats, but it defaults to outputting the hyphenated one, as seen in [this](https://github.com/graphql-rust/juniper/blob/752584fbbdd27961d2641f8033a65e3c5f985d27/juniper/src/integrations/uuid.rs#L13)

```
graphql_scalar!(Uuid where Scalar = <S> {
    description: "Uuid"

    resolve(&self) -> Value {
        Value::scalar(self.to_string())
    }
```

Type uuid::Uuid's `to_string()` method defaults to the hyphenated version.  I made a feature request to Uuid crate [here](https://github.com/uuid-rs/uuid/issues/420), but they suggested this could be better handled in Juniper.

**Describe the solution you'd like**
What I thought was a #[cfg(feature)] type of configuration in which the desired default output format could be specified.

**Describe alternatives you've considered**
Opened a feature request with the Uuid crate but they turned it down.

**Additional context**

**Comment by theduke** [comment]
Sorry but this kind of customization is too specific and too edge case to include in the main repo.

I'd suggest using a custom `Uuid` newtype wrapper with a custom `graphql_scalar!` implementation.

**Comment by hrbigelow** [comment]
No problem - that's a fine idea, and if I understand correctly, it is equally efficient.
