### ISSUE TITLE
Implement std::error::Error for all public error types

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#415]
* GraphQLError
* ParseError
* LexerError
* RuleError
* FieldError

**Comment by davidpdrsn** [comment]
I looked into this yesterday and it isn't totally straight forward. `std::error::Error` requires a `Display` implementation which `Spanning<ParseError<'a>>` and `RuleError` doesn't have. They should be possible to add but I wasn't sure what the most helpful implementations might be.

I might just make some initial implementation so we have something to discuss.

**Comment by theduke** [comment]
All errors should get a `Error` impl, it's a big oversight that they didn't have it yet.

The only limitation here is that we can't include surrounding input query context in the generated error message but that's fine I think.
