### ISSUE TITLE
Refactor object proc macro attributes to support parameter attributes

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#421]
Function parameter attributes are getting stabilized with `1.39`. (see https://github.com/rust-lang/rust/issues/60406#issuecomment-526327343).

This means we can refactor the argument customization of the `object` proc macro.

This is currently awkward due to the lack of above feature ( see https://graphql-rust.github.io/juniper/current/types/objects/complex_fields.html#customizing-arguments ).

* Supported arguments: `#[graphql(rename = "...", default = expr, description = "...")]`
* Old style should remain supported for now but with a deprecation warning (simple `println` in the macro)
* can be implemented right now with a feature flag, which can be removed once `1.39` is released

**Comment by davidpdrsn** [comment]
I have started hacking in this. Progress is here https://github.com/davidpdrsn/juniper/tree/parameter-attributes

**Comment by theduke** [comment]
@davidpdrsn awesome, please ask if you have any questions.

Also feel free to open a draft PR to give it visibility.

**Comment by tyranron** [comment]
In #682 landed the implementation for GraphQL interfaces.

**Comment by c410-f3r** [comment]
Nice
