### ISSUE TITLE
Support Content-Type: application/graphql

### ISSUE THREAD

**Issue by aisrael** [graphql-rust/juniper#426]
**Is your feature request related to a problem? Please describe.**

I'm trying out Juniper + Hyper and discovered that it doesn't support `Content-Type: application/graphql`.

When submitting an HTTP POST request containing a JSON GraphQL query, like so, it works as expected:

```
$ curl -X POST -H "Content-Type: application/json" -d '{"query":"{user(id:\"1\") {name email}}"}' http://localhost:3000/graphql
{
  "data": {
    "user": {
      "name": "name",
      "email": "name@example.com"
    }
  }
}
```

However, other GraphQL implementations also support `Content-Type: application/graphql` where the entire POST body is treated as the GraphQL query. When I tried it with Juniper + Hyper, I get:

```
$ curl -X POST -H "Content-Type: application/graphql" -d '{user(id: "1") {name email}}' http://localhost:3000/graphql
key must be a string at line 1 column 2
```

It seems that Juniper + Hyper is still treating the POST body as JSON and thus encountering a parsing error.

**Describe the solution you'd like**

Juniper + Hyper should accept `Content-Type: application/graphql` and handle it accordingly, similar to a `GET` query.

**Describe alternatives you've considered**

While JSON payloads are more powerful (since you can include variables), `application/graphql` _is_ commonly accepted by other GraphQL implementations in other languages.

**Additional context**

I have a working juniper-hyper project at https://github.com/aisrael/juniper-hyper-demo

**Comment by LegNeato** [comment]
Thanks for the report! Should be an easy PR. I'm a bit slammed at work so I am not sure when I can get around to it. Patches welcome!

**Comment by theduke** [comment]
Is this mentioned in the spec, or is there a PR in the specs repo?

How does one pass non-inline variable values with this approach?

**Comment by aisrael** [comment]
@theduke Am not sure if it's in the `graphql-spec` anywhere but it is mentioned in the docs: https://graphql.org/learn/serving-over-http/#post-request

**Comment by LegNeato** [comment]
That's not official GraphQL docs, that's Apollo FWIW.

**Comment by knidarkness** [comment]
@LegNeato , so do you think this update would be nice to have? If so, I could spend some time on it.
