### ISSUE TITLE
Support descriptions with `param_attrs` on field arguments with proc-macro

### ISSUE THREAD

**Issue by davidpdrsn** [graphql-rust/juniper#428]
I have been [working on removing the use of `graphql_object!`](https://github.com/davidpdrsn/juniper-from-schema/pull/74) from juniper-from-schema in favour of the new proc macro. The process was pretty straight forward except for supporting descriptions on field arguments. [The juniper docs](https://docs.rs/juniper_codegen/0.13.2/juniper_codegen/attr.object.html#customization-documentation-renaming-) mentions that cleaning that up is blocked by [RFC 2564](https://github.com/rust-lang/rust/issues/60406). However that RFC is now stabilised and will be included in 1.39 🎉

I'm not sure if you want to require 1.39 for the next release, but since it'll include async/await I imagine most people are going to upgrade quickly. If you do wait until 1.40 I would appreciate it if you keep `graphql_object!` around until then so juniper-from-schema doesn't get stuck in limbo 😊

Anyways I'm mostly opening this issue as a reminder and to let you know the RFC has landed, and since I didn't see an issue about it already. Let me know if you need help implementing it.

**Comment by theduke** [comment]
#421  ;)
