### ISSUE TITLE
Use https://crates.io/crates/proc-macro-error

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#435]
It would be good to use https://crates.io/crates/proc-macro-error to improve error reporting for proc macros.

Basically we should look everywhere we `panic()` in our proc macros and add span info.

**Comment by davidpdrsn** [comment]
Just wondering, how is that different from [`syn::Error`](https://docs.rs/syn/1.0.5/syn/struct.Error.html)?

**Comment by davidpdrsn** [comment]
Ah I see it mentioned in the readme further down. Nvm

**Comment by davidpdrsn** [comment]
https://github.com/graphql-rust/juniper/pull/441 lays the ground work for this. Once that is merged I’ll update the rest of code gen.

**Comment by LegNeato** [comment]
This is done.
