### ISSUE TITLE
EmptyMutation breaks Sync trait

### ISSUE THREAD

**Issue by Y0hy0h** [graphql-rust/juniper#439]
Since Rocket requires the data it manages to be thread-safe, I encountered an issue where the Juniper `Schema` containing a thread-safe database pool would not be recognised as implementing `Sync`. I've initially opened an [issue at the Rocket repo](https://github.com/SergioBenitez/Rocket/issues/1157).

The gist is that I would get blocked by a compile error:
```
error[E0277]: `std::cell::Cell<i32>` cannot be shared between threads safely
  --> src/api.rs:27:1
   |
27 | / fn post_graphql_handler(
28 | |     context: Database,
29 | |     request: juniper_rocket::GraphQLRequest,
30 | |     schema: State<Schema>,
31 | | ) -> juniper_rocket::GraphQLResponse {
32 | |     request.execute(&schema, &context)
33 | | }
   | |_^ `std::cell::Cell<i32>` cannot be shared between threads safely
   |
   = help: within `juniper::schema::model::RootNode<'static, store::Query, juniper::types::scalars::EmptyMutation<store::Context>>`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<i32>`
   = note: required because it appears within the type `diesel::connection::AnsiTransactionManager`
   = note: required because it appears within the type `diesel::SqliteConnection`
   = note: required because it appears within the type `rocket_contrib::databases::r2d2::Conn<diesel::SqliteConnection>`
   = note: required because it appears within the type `std::option::Option<rocket_contrib::databases::r2d2::Conn<diesel::SqliteConnection>>`
   = note: required because it appears within the type `diesel::r2d2::PooledConnection<diesel::r2d2::ConnectionManager<diesel::SqliteConnection>>`
   = note: required because it appears within the type `store::db::Database`
   = note: required because it appears within the type `store::Context`
   = note: required because it appears within the type `std::marker::PhantomData<store::Context>`
   = note: required because it appears within the type `juniper::types::scalars::EmptyMutation<store::Context>`
   = note: required because it appears within the type `juniper::schema::model::RootNode<'static, store::Query, juniper::types::scalars::EmptyMutation<store::Context>>`
   = note: required by `rocket::State`
```

This is surprising, because the `store::db::Database` type actually implements `Sync`. I found that I could resolve the issue by not using `juniper::EmptyMutation` but instead doing
```rust
pub struct Mutation;

#[juniper::object(Context=Store)]
impl Mutation {}
```

Therefore, I assume that there is a bug in the implementation of `EmptyMutation` that prevents correct inference of the `Sync` trait.

While it is not a self-contained example, the error is present on [this commit](https://github.com/Y0hy0h/lindyhop-aachen/tree/bcbc0f02b62e10db2cdf73ae4deb194fe7f6c19a) and is fixed in [this commit](https://github.com/Y0hy0h/lindyhop-aachen/tree/d17e88e6dee78237a0fe73cda43ddcc15c906b70).

**Comment by LegNeato** [comment]
I *think* we can just do:

```rust
unsafe impl<T> Send for EmptyMutation<T> {}
```
Because ` EmptyMutation` never references `T`...it only uses it for `PhantomData`. That being said, I am unsure as I have never used `unsafe` in Rust before. @theduke ?

**Comment by Y0hy0h** [comment]
Wow, you guys are awesome! Thanks a lot!

**Comment by LegNeato** [comment]
I pushed a point release with this fix in it.
