### ISSUE TITLE
Serde Implementation with graphql_object

### ISSUE THREAD

**Issue by AurelienFT** [graphql-rust/juniper#440]
I've implemented the following `User` structure and graphql_object :
```
#[derive(Serialize, Deserialize, Debug)]
pub struct User {
    #[serde(rename = "_id")]
    pub id: Option<ObjectId>,

    #[serde(default)]
    pub email: Option<String>,

    #[serde(default)]
    pub username: Option<String>,

    #[serde(default)]
    pub role: Option<String>,
}

graphql_object!(User: Context |&self| {
    field id() -> String { if let Some(ref id) = self.id { id.to_string() } else { "".into() } }
    field email() -> &str { if let Some(ref email) = self.email { email.as_str() } else { "".into() } }
    field username() -> &str { if let Some(ref username) = self.username { username.as_str() } else { "".into() } }
    field role() -> &str { if let Some(ref role) = self.role { role.as_str() } else { "".into() } }
});
```
I need the `struct User` to interact with my database MongoDB. Is it possible to translate my structure to a `graphql_object` using `serde` or an other serialization process to avoid duplicating my structure ?

Thanks for your support.

**Comment by tyranron** [comment]
@AurelienFT I would highly recommend to keep your models for DB and GraphQL objects separately, so don't event try to write GraphQL objects into DB.

Let me explain why...

GraphQL objects are part of a GraphQL schema, which does not represent a _data model_, but rather a _data interface_ for external clients. In terms of mainstream REST API, we can say that GraphQL schema is a Controller layer, not a Model/Domain layer.

This is quite obvious if you think/look about/at how GraphQL schema may evolve in time. Let's start with a simple:
```rust
#[derive(juniper::GraphQLObject)]
struct Chat {
    id: Uuid,
    members: Vec<Member>,
}

#[derive(juniper::GraphQLObject)]
struct Member {
    id: Uuid,
    name: String,
}
```

This schema is quite obvious and each field has trivial resolution (just returning reference to its value).

However, at some point, we want be able to query `Message`s of this chat. But we cannot just pull all the `Message`s stored in our DB and paster them into `Chat` struct as `Vec`. So, what we want is a _dynamic field resolution_. We want `Message`s being loaded from DB _only if_ they were requested. With Juniper it can be easily done as following:
```rust
struct Chat {
    id: Uuid,
    members: Vec<Member>,
}

#[juniper::object(Context = Db)]
impl Chat {
    fn id(&self) -> Uuid { &self.id }

    fn members(&self) -> &[Member] { self.members.as_slice() }

    fn messages(
        &self,
        after: Option<Cursor>, 
        first: Option<i32>, 
        context: &Db,
    ) -> Result<Vec<Message>, Error> {
        Ok(context
            .load_messages_of_chat(self.id, after, first)?
            .into_iter()
            .map(Into::into)
            .collect())
    }
}

#[derive(juniper::GraphQLObject)]
struct Message {
    id: Uuid,
    text: String,
}

#[derive(juniper::GraphQLObject)]
struct Member {
    id: Uuid,
    name: String,
}
```

Now we won't trigger `Message`s loading at all in situations like this:
```graphql
queries {
    chat(id: "....") {
        members,
    }
}
```

So, as you see, `Chat` has nothing common with DTOs or domain Models. It's just a _queryable API interface_.

---------------------------

So, you problem can be solved by introducing a separate `struct`s which store the actual data and are able to ser/de for your DB and are `From`/`Into`-convertible to GraphQL objects of your schema for ergonomics.

**Comment by AurelienFT** [comment]
@tyranron Thanks a lot man ! Your response is awesome.
