### ISSUE TITLE
Document N+1 mitigation techniques in the book

### ISSUE THREAD

**Issue by MikailBag** [graphql-rust/juniper#444]
**Is your feature request related to a problem? Please describe.**
Now, resolver signature looks like:
`fn field(&self, /*args*/)`.
This can easily lead to N + 1 DB query problem. (Or even N**K if query has K levels of depth). To avoid this problem, special libraries should be used, that somehow accumulate queries and merge them into one.

**Describe the solution you'd like**
(Idea itself is very simple. It is possible that is was already discussed and rejected, but I didn't find such an issue). I propose to allow batched resolvers. Signature now looks smth like:
`fn field(self: &[Self], ctx:&Ctx, args: ...)`
Now, from N**K requests we go to K (each level will be processed with _one_ resolver execution and _one_ db request).
**Describe alternatives you've considered**
Alternative: do nothing.
However, I believe batched resolvers  provide good enough performance with high flexibility.

**Comment by tyranron** [comment]
@MikailBag for N + 1 query problem the usual solution is either [dataloader](https://github.com/cksac/dataloader-rs) or [lookahead](https://github.com/graphql-rust/juniper/issues/387).

As for proposed solution I'm unsure how well it will fit. Usually, resolvers may contain allowed-resoling-depth checks, authorization-rights check, authentication checks, etc, which all are query-scoped. Resolving multiple queries at the same time, but now with the same context, seems to be less flexible.

**Comment by davidpdrsn** [comment]
If you're interested in the lookahead approach you could consider [juniper-eager-loading](https://crates.io/crates/juniper-eager-loading) which handles all the boilerplate. We're using it in production at @tonsser and its been working well so far. Full disclosure: I'm the maintainer of the library.

**Comment by theduke** [comment]
As mentioned by others, the possible approaches here are

* datalaoder
* using lookahead
* uniper-eager-loading

We should really add to the book, since it's a common stumbling block.

**Comment by MikailBag** [comment]
Thanks for the responses!
I will study your proposals (so far juniper-eager-loading looks the most promising).

Regarding book, I would like to see quite complex example, e.g.:
- Response data are aggregated from DB and in-memory source (e.g. calculated).
- Application doesn't directly use diesel, it uses some trait, `MyAppDbProvider`.
- And without too much glue code :)

**Comment by davidpdrsn** [comment]
@MikailBag I maintain a complete example app. You can find it here https://github.com/davidpdrsn/graphql-app-example. It does use Diesel directly however.

**Comment by jayy-lmao** [comment]
@MikailBag I'd be happy to make any requested changes to my demo repo and provide it as an example.

https://github.com/jayy-lmao/rust-graphql-docker

It currently uses dataloaders and has an emphasis on code structure. I welcome any feedback/critique.
