### ISSUE TITLE
Is it possible to add authorization system on Juniper

### ISSUE THREAD

**Issue by AurelienFT** [graphql-rust/juniper#447]
Hello,

I have my GraphQL API with Juniper and I want to add permissions to call a graphql_object/to get his result/to get some fields of the result.

With Type-GraphQL we can do something like that : 
```
class MyObject {
  @Field()
  publicField: string;

  @Authorized()
  @Field()
  authorizedField: string;

  @Authorized("ADMIN")
  @Field()
  adminField: string;

  @Authorized(["ADMIN", "MODERATOR"])
  @Field({ nullable: true })
  hiddenField?: string;
}
```

In Rust with Juniper I'll like to know if there is a way to do it ? I didn't find anything about it so I think about a good syntax to make it easy to use. There is something similar to this in Juniper ? :
```
impl Queries {
    #[authorized_call("ADMIN")]
    #[authorized_return(readPermissions)]
    fn user(
        context: &Context,
        id: Option<String>,
        email: Option<String>,
        username: Option<String>,
        role: Option<String>,
    ) -> FieldResult<Option<User>> {
                Ok(find_user(context, id, email, username, role))
    }
}
```

Thank you for your time

**Comment by theduke** [comment]
This is not currently possible, but definitely desired.

The async migration will take precedence for now, but this would be terribly hard to implement. 

We could even implement this in a relatively type-safe way.

Currently your best bet is something more manual:

```rust
struct Context {
  user: Option<User>,
}

enum Permission {
  ReadPost,
  ReadOwnPost,
  WritePost,
  ...
}

fn authorize(ctx: &Context, permissions: &'static [Permission]) -> Result<(), FieldError> {
  // ...
}

#[juniper::object(Context = Context)]
impl Query {
  fn post(context: &Context, id: u64) -> Result<(), FieldError> {
    authorize(context, &[Permission::ReadPost])?;
    ...
  }
}


```

**Comment by EituKo** [comment]
@theduke 
Hi and thank you for your answer!

We really appreciate your alternative but we would like to have a compilation-time, type-safe permissions system with the following characteristics:

- Permissions implementation would be checked at compilation time and generate errors / warning if not implemented or not implemented correctly
- A custom filter could be applied if the return is an iterable type

We started using Rust for this kind of usage and would like to use it to its full potential since we're not able to do something like this with other languages.
We also think that having automated permissions documentation would be a great future feature.

As  @AurelienFT mentioned it earlier, it would look like this:
```rust
impl Query {
    #[authorized_call("ADMIN")]
    #[filter_result(readPermissions)]
    fn user(
        context: &Context,
        id: Option<String>,
        email: Option<String>,
        username: Option<String>,
        role: Option<String>,
    ) -> FieldResult<Option<User>> {
                Ok(find_user(context, id, email, username, role))
    }
}
```

We really want to implement this in the Juniper crate, can we create a MR to do so?
Also, do you have any possible suggestions on macro syntax?

Thank you for your time!

**Comment by davidpdrsn** [comment]
@EituKo What are you thinking `#[authorized_call("ADMIN")]` and `#[filter_result(readPermissions)]` would expand into? Like what code would be generated in the end?

**Comment by EituKo** [comment]
@davidpdrsn
`#[authorized_call("ADMIN")]` would expand into a function that defines the permissions needed to call the associated query / mutation.
`#[filter_result(readPermissions)]` would expand into a function that filters the iterable objects returned using a given functor, `readPermissions` in this case.

**Comment by davidpdrsn** [comment]
Isn’t that pretty much what @theduke suggested? If you want things to be more type safe I guess you would have to make the return type something like Option<User<Authorized>> where Authorized is in a PhantomData.

**Comment by EituKo** [comment]
@davidpdrsn 
We didn't understand each other and this is mainly my fault.

- we want to avoid any side effects on our permissions system, so the authorization check has to be made **before** the function handling the query.
- the majority of queries are subjects to some sort of authentication/authorization therefore **the public calls are the exception**
- the above reason also implies that the user **must** define these authorizations no matter what
- we want a **compilation error** if authorizations are not defined

This justifies the use of a `proc_macro` that expands into a function **wrapping** the function handling the query. If authorizations are not defined correctly, the wrapped function **is not called** and a compilation error pops.

These are the macros (names are not definitive):
1. `#[authorized_public]` to specify **explicitly** that a query is `public`
2. `#[authorized]` to specify that the user must be logged in
3. `#[authorized_with]` to specify that the user must be logged in **and** the permissions required
4. `#[authorized_filter]` to specify a function to check the permissions used to **filter the query result**

If either **1**, **2** or **3** is not specified on a query, we throw a **compilation error**.

**Comment by AurelienFT** [comment]
Hello,

We didn't have any answer from you. We want to try something to show you our proposition in a PR. But we face the complexity of the `impl_object` proc-macro. We want to make a simple proc-macro to test but it's filtered by `from_attrs` function.
We want to know if you have some tips to help us to start something ?

Thanks for your answer
(cc @theduke @davidpdrsn )

**Comment by ccbrown** [comment]
Imo if there is a generic, non-Authorization-related, way Juniper can help you accomplish what you want, that would be a great addition to Juniper.

However, building authorization on top of Juniper is a bit of an anti-pattern. See the GraphQL.org's page on best practices for authorization:

https://graphql.org/learn/authorization/

In your example, the recommended practice would be for the `find_user` function to be responsible for authorization, not the API layer.

**Comment by LegNeato** [comment]
Agreed! If Juniper doesn't have the proper hooks, please open an issue on the missing extension / integration point.

**Comment by AlbertMarashi** [comment]
Really would like a way to define directives with attributes
