### ISSUE TITLE
Unnecessary todo (?)

### ISSUE THREAD

**Issue by nWacky** [graphql-rust/juniper#451]
In [`executor/mod.rs`](https://github.com/graphql-rust/juniper/blob/master/juniper/src/executor/mod.rs#L526) there is a 'support excludes' todo: 

```rust
 let found_field = p.iter().find(|&x| {
                    match *x {
                        Selection::Field(ref field) => {
                            let field = &field.item;
                            // TODO: support excludes.
                            let name = field.name.item;
                            let alias = field.alias.as_ref().map(|a| a.item);
                            alias.unwrap_or(name) == field_name
                        }
                        _ => false,
                    }
```

As I understood, this todo suggests that fields with `@skip(if: true)`/`@include(if: false)` directives should be excluded from returned selection set. 

However, they are excluded later on when calling `LookAheadSelection::build_from_selection`

Todo was first found in [this commit](https://github.com/graphql-rust/juniper/commit/5065eb2265d666b675abf17204b688cd86c97208)

**Comment by LegNeato** [comment]
probably.  I put that in there because the code I was writing didn't handle the case explicitly and I didn't check if downstream did.

**Comment by tosti007** [comment]
Considering the TODO is removed, this issue can be closed.
