### ISSUE TITLE
Move CI got Github Actions

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#453]
Github Actions are a bit more powerful,  largely identical, but mostly they don't necessitate us managing two different platforms (and deal with the somewhat obscure Azure Pipelines UI).

Let's move over.

**Comment by LegNeato** [comment]
See https://github.com/graphql-rust/juniper/issues/531

**Comment by tyranron** [comment]
@LegNeato for now GitHub Actions duplicate the Azure CI. However the later is less handy for cancellation, for example. Are you ok with dropping Auzre CI altogether?

**Comment by tyranron** [comment]
Moved to GitHub Actions completely in #1043
