### ISSUE TITLE
Recommended way to allow a single field of a struct to fail

### ISSUE THREAD

**Issue by sbditto85** [graphql-rust/juniper#488]
In the GraphQL docs example 184 (https://graphql.github.io/graphql-spec/June2018/#example-bc485) mentions a field of object can fail and if it nullable then it gets nulled out but the rest of the object still shows and an in the errors it shows how that particular field had a problem. How would someone do that with Juniper?

My own small contrived example would be if I have a particular field on a table that has access control rights, but the rest of the table can be viewed. I need to be able to return everything like normal, but if they request the protected field then check to see if they are allowed and if not return null and set the error indicating they weren't allowed to.

Sorry if this is a newb question I still have a lot to learn about Juniper and GraphQL

**Comment by mwilliammyers** [comment]
You should use the [GraphQL object proc-macro](https://graphql-rust.github.io/juniper/master/types/objects/complex_fields.html) for that which has access to the `Context` which you can use to check the current User and go from there.

**Comment by sbditto85** [comment]
Just got back from break, how would i use the macro? have a function for each column of the table and do a select for each field? I would like to do a select for the whole row(s) and then only on particular columns do the check.

**Comment by sbditto85** [comment]
@LegNeato can this be reopened? I don't think the question was answered other then RTFM which i've been trying to and can't see how I'm supposed to accomplish my question

**Comment by sbditto85** [comment]
FWIW I _may_ of figured out how to have (https://graphql.github.io/graphql-spec/June2018/#example-bc485) the heroFirends with a null name. Basically I have to have something on the `QueryRoot` that returns a `FieldResult<Vec<HeroFriends>>` (or similar) that fetches the rows and then have a `struct HeroFriends` that has an `impl HeroFriends` with a function for each field that can just return its member (probably just a reference) BUT on the field that needs checking accept the context and return a `FieldResult<Option<_member data_>>` (even though the struct field may not be optional) so that the particular field can fail. When returning a `Ok(herofriends)` from the `QueryRoot` funciton it will auto-magically perform the check for me when generating the response (it wasn't obvious to me that would happen, like i said newb) and return a null for the heroFiends name when my context check returns a field result failure.

Cool

**Comment by mwilliammyers** [comment]
For posterity’s sake:

Yes you are correct; that would enable you to not have to do a db query for each field. 

Sounds like you have the correct mental model of how to do this—essentially the idea is to “lift” the db query one level higher in the GraphQL schema tree (at the root in your example) and then do the checks for each field on your `impl HeroFriends`—which will use the graphql object proc-macro to allow you to write custom functions with access to the `Context` and allow to you to return an `Err` or a `None` for failed auth checks.

**Comment by sbditto85** [comment]
I feel that there should be a section added to the book re "lifting" as well as how errors work.

I didn't realize that GraphQL treated errors like:

> If the field which experienced an error was declared as Non-Null, the null result will bubble up to the next nullable field. In that case, the path for the error should include the full path to the result field where the error occurred, even if that field is not present in the response.

Which means that if i wanted something to be able to error at that level it must be Option(al) otherwise the error will keep propagating up the tree until the root itself is null even if there were other parts which were perfectly valid and able to be sent to the client.

If I get time I'll see if i can put in a PR to at least get it started even though I am most definitely not the most qualified.
