### ISSUE TITLE
Using unsupported scalar types

### ISSUE THREAD

**Issue by monophthongal** [graphql-rust/juniper#492]
Hi,

The documentation indicates that if you want to use Juniper with built-in Rust scalar types other than i32, f64, String, and bool you can wrap them in a newtype. However doing this with existing structs that use the base types directly would mean rewriting a lot of existing code. 

Are there any examples or documentation of how it might be possible to add support for using other types like i16 or i128 without needing newtypes?

The example for Custom Scalars in the documentation doesn't compile when used with non-local scalars.

I came across the Wundergraph project which appears to do something similar - is this the recommended approach?

https://github.com/weiznich/wundergraph/blob/master/wundergraph/src/scalar.rs

Thank you for your help.

**Comment by monophthongal** [comment]
I researched this more and realized the documentation for [ScalarValue](https://docs.rs/juniper/0.12.0/juniper/trait.ScalarValue.html) has the answer to my question. 

Once you implement your new scalar value representation as described in the ScalarValue docs, you can then use `graphql_scalar!` with `where Scalar = MyScalarValue` as shown in [the Wundergraph code](https://github.com/weiznich/wundergraph/blob/master/wundergraph/src/scalar.rs).

It looks like you also need to use `#[graphql(scalar = MyScalarValue)]` when deriving GraphQLObjects. This is mentioned in the [docs for juniper::object](https://docs.rs/juniper/0.14.2/juniper/attr.object.html#lifetimes-generics-and-custom-scalars).

I'll go ahead and close this issue.

**Comment by Tails** [comment]
@monophthongal is the use of ```#[graphql(scalar = MyScalarValue)]``` only neccessary for Query and Mutation objects, or should these be applied to every GraphQL model/entity in your app?

**Comment by tyranron** [comment]
@Tails at the moment (current `master`) it depends... in some cases generated code is polymorphic on `S: ScalarValue` and is some cases it's bounded strictly to `DefaultScalarValue`. You need to read docs carefully about the exact your case, and also look into `cargo expand` output for your type to see where `#[graphql(scalar = MyScalarValue)]` should be applied.

Till next release we will do our best to remove this incovenience, so the all generated code will be abstracted over generic `S: ScalarValue`.
