### ISSUE TITLE
Enum structs in `input`

### ISSUE THREAD

**Issue by UkonnRa** [graphql-rust/juniper#495]
**Describe the bug**
Say I want to put an enum struct into `input object`:

```rust

// The Enum Struct
enum Episode {
    Test1(i32),
    Test2(String),
}

juniper::graphql_interface!(Episode: () where Scalar = <S> |&self| {
    instance_resolvers: |_| {
        &Episode => match *self {
            Episode::Test1(ref h) => Some(h),
            Episode::Test2(ref s) => Some(s),
        },
    }
});

#[derive(juniper::GraphQLObject)]
#[graphql(description = "A humanoid creature in the Star Wars universe")]
struct Human {
    id: String,
    name: String,
    appears_in: Vec<Episode>,
    home_planet: String,
}

// There is also a custom derive for mapping GraphQL input objects.

#[derive(juniper::GraphQLInputObject)]
#[graphql(description = "A humanoid creature in the Star Wars universe")]
struct NewHuman {
    name: String,
    // Here is the error
    appears_in: Vec<Episode>,
    home_planet: String,
}

```

And I just got:

```
error[E0277]: the trait bound `Episode: juniper::ast::FromInputValue<__S>` is not satisfied
  --> src/main.rs:29:10
   |
29 | #[derive(juniper::GraphQLInputObject)]
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `juniper::ast::FromInputValue<__S>` is not implemented for `Episode`
   |
   = note: required because of the requirements on the impl of `juniper::ast::FromInputValue<__S>` for `std::vec::Vec<Episode>`
```

Which says `the trait `juniper::ast::FromInputValue<__S>` is not implemented for `Episode``? But why? I do implement `graphql_interface`, aren't I?

**Comment by UkonnRa** [comment]
I found from [the spec](http://spec.graphql.org/June2018/#sec-Input-and-Output-Types) that the fields of an Input Object can only be `a Scalar, Enum, or Input Object type`. So if I want to pass an enum struct, the only solution is to pass an JSON/String or something and deserialize it after receiving it?

**Comment by tyranron** [comment]
@UkonnRa yup, that's the limitation of GraphQL type system, not `juniper` itself:
- GraphQL enums are flat, they cannot have structures inside;
- GraphQL unions which can have structures, cannot be used as input.

> So if I want to pass an enum struct, the only solution is to pass an JSON/String or something and deserialize it after receiving it?

That is  possible, but is quite unnatural for GraphQL.

We overcome such situations in our codebase just by using multiple optional args:
```rust
#[derive(GraphQLInputObject)]
#[graphql(description = "A humanoid creature in the Star Wars universe")]
struct NewHuman {
    name: String,
    appears_in_episode_by_num: Option<i32>,
    appears_in_episode_by_name: Option<String>,
    home_planet: String,
}
```
After that we tend to impl something like `impl TryFrom<(Option<i32>, Option<String>)> for Episode` and use a regular enum in the downstream code.

Not very pleasant, by just how it is.

P.S. Sorry for too late reply.
