### ISSUE TITLE
Add subscription support on graphiql

### ISSUE THREAD

**Issue by librelois** [graphql-rust/juniper#501]
It would be really nice to be able to test our subscriptions on graphiql.

It's possible, indications here: https://blog.apollographql.com/how-to-use-subscriptions-in-graphiql-1d6ab8dbd74b

**Comment by LegNeato** [comment]
Thanks for the enhancement request! This looks like a good first bug.

**Comment by iho** [comment]
+1

**Comment by thekuom** [comment]
@LegNeato I would like to work on this since it doesn't look like anybody has started yet
