### ISSUE TITLE
[main branch, async] `juniper::GraphQLTypeAsync<__S> is not satisfied` when generating custom scalar

### ISSUE THREAD

**Issue by UkonnRa** [graphql-rust/juniper#506]
**Describe the bug**
```
error[E0277]: the trait bound `Badges: juniper::GraphQLTypeAsync<__S>` is not satisfied
  --> src\main.rs:14:10
   |
14 | #[derive(juniper::GraphQLObject, Serialize, Deserialize)]
   |          ^^^^^^^^^^^^^^^^^^^^^^ the trait `juniper::GraphQLTypeAsync<__S>` is not implemented for `Badges`
   |
   = note: required because of the requirements on the impl of `juniper::GraphQLTypeAsync<__S>` for `&Badges`
```

**To Reproduce**
```rust

#[derive(juniper::GraphQLObject, Serialize, Deserialize)]
struct User {
    pub badges: Badges,
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
#[serde(transparent)]
pub(crate) struct Badges(HashMap<String, String>);

juniper::graphql_scalar!(Badges where Scalar = <S> {
    description: "Badges"

    // Define how to convert your custom scalar into a primitive type.
    resolve(&self) -> Value {
        Value::scalar(serde_json::to_string(&self).unwrap())
    }

    // Define how to parse a primitive type into your custom scalar.
    from_input_value(v: &InputValue) -> Option<Badges> {
        v.as_string_value().and_then(|s| serde_json::from_str(s).ok())
    }

    // Define how to parse a string value.
    from_str<'a>(value: ScalarToken<'a>) -> ParseScalarResult<'a, S> {
        if let ScalarToken::String(value) = value {
            Ok(S::from(value.to_owned()))
        } else {
            Err(ParseError::UnexpectedToken(Token::Scalar(value)))
        }
    }
});

```

**Expected behavior**
No Error

**Comment by UkonnRa** [comment]
I just checked the other intergrations (`uuid::Uuid`, etc.). The macro code are all the same, but `uuid::Uuid` just does not encounter the problem, the custom scalar does. Weird...

**Comment by UkonnRa** [comment]
Well, you should impl `GraphQLTypeAsync` yourself, I think it is just a bug(or a miss).

```rust
impl<S: juniper::ScalarValue + Send + Sync> juniper::GraphQLTypeAsync<S> for Badges {}
```

**Comment by LegNeato** [comment]
There are some weird interactions with features on master. I'm hoping to have some time this week to sort it all out. I believe if you use the `async` feature it should all work

**Comment by mwilliammyers** [comment]
I also ran into this. It looks like `graphql_scalar!` is [disabled](https://github.com/graphql-rust/juniper/blob/824f329b0f23718fc996437aad76361a82e46453/juniper/src/macros/scalar.rs#L45) with the `async` feature enabled.

I am also going to look into just implementing `GraphQLTypeAsync` directly;  the macro has been a little bit of a pain point in my codebase tbh.

PS thanks everyone for all the hard work moving to async! 🎉 Such a huge undertaking but one well worth the effort! I have been trying to familiarize myself with the codebase more to see if I can pitch in.

**Comment by LegNeato** [comment]
It's actually enabled further down:

https://github.com/graphql-rust/juniper/blob/824f329b0f23718fc996437aad76361a82e46453/juniper/src/macros/scalar.rs#L345

**Comment by LegNeato** [comment]
Please reopen if the issue was not fixed!
