### ISSUE TITLE
Confusing about the escaped chars in String of InputValue

### ISSUE THREAD

**Issue by UkonnRa** [graphql-rust/juniper#510]
Because now juniper does not support JSON scalar(#509), I have to pass a JSON Object using a piece of string, like:

```rust
let (res, errors) = juniper::execute_async(
      r#"mutation {
createUser(input: {
    nickname: "nickname",
    avatar: "http://example.com", 
    badges: "{\"Github\": \"https://github.com\"}"}) {
        id
        nickname
    }
}"#,
    None,
    &schema,
    &Variables::new(),
     &ctx,
).await.unwrap();
```

And then I created a new Scalar type named `JsonValue`:
```rust
juniper::graphql_scalar!(JsonValue where Scalar = <S> {
    // other definitions...
    from_input_value(v: &InputValue) -> Option<JsonValue> {
        v.as_string_value().and_then(|s| {
            println!("input string: {:?}", s);
            serde_json::from_str(s).ok()
        })
    }
}
```

What I want is receiving a string like: `{"Github": "https://github.com"}`, but in fact, I get:
```
{\"Github\": \"https://github.com\"}
```

I wonder if this a feature? How can I pass the string from input object correctly?

**Comment by LegNeato** [comment]
You appear to be using Rust raw string literals (`r#...#`) which means you do not need to escape `"` on the Rust side. See https://rahul-thakoor.github.io/rust-raw-string-literals/.

Do you still see the resulting slashes if you remove them from the Rust side? If so please reopen!
