### ISSUE TITLE
Support for warp-0.2?

### ISSUE THREAD

**Issue by maxburke** [graphql-rust/juniper#513]
I notice that Warp 0.2 is out; is anyone at present working on support for this? Curious if I should take a stab at it myself if no one is...

**Comment by LegNeato** [comment]
Would love a PR! I think it will simplify the `warp` integration code greatly.

**Comment by LegNeato** [comment]
Looks like this might already be a part of https://github.com/graphql-rust/juniper/pull/433/files#diff-e8ffeb0b59b8285ec303dc3a8a4703fe

**Comment by LegNeato** [comment]
This is now on `master`.

**Comment by AurelienFT** [comment]
Warp 0.2 is an important update is that possible to release a new version of `juniper_warp` for the support of warp 0.2 please ?

**Comment by LegNeato** [comment]
There are still some outstanding work items to do before we can push a release.

**Comment by jeromegn** [comment]
Looking forward to the release supporting warp 0.2. It's been merged in master for a while.

Any thoughts on making warp 0.2-compatible filters based on juniper_wrap 0.5.2? I see master uses the concept of subscriptions which appear fairly new and unreleased in juniper.
