### ISSUE TITLE
Implement GraphQLType for chrono_tz::Tz

### ISSUE THREAD

**Issue by nirman28** [graphql-rust/juniper#516]
Following on from https://github.com/graphql-rust/juniper/issues/87

Since the chrono_tz crate is so popular, it's a pain not to have it implement GraphQLType.

We should implement it behind a feature flag, representing Tz with its name string.

**Comment by nirman28** [comment]
I'm happy to take the implementation for this.
It shall be similar to https://github.com/graphql-rust/juniper/issues/87

**Comment by davidpdrsn** [comment]
Go for it 💪

**Comment by nirman28** [comment]
can you assign it to me, lest someone else might also spend time on it
