### ISSUE TITLE
Tried to resolve async field on type Some("Mutation") with a sync resolver

### ISSUE THREAD

**Issue by eeyun** [graphql-rust/juniper#523]
I'm hoping that this is just me being a dummy. I've been hacking with juniper  async for a couple days and got everything compiling and running. However at runtime when the `addPost`  mutation in my app gets called I get a panic  with an error like so:
```
[2020-02-04T21:44:24Z DEBUG hyper::proto::h1::conn] incoming body completed
thread 'tokio-runtime-worker-1' panicked at 'Tried to resolve async field addPost on type Some("Mutation") with a sync resolver', components/graphql-warp/src/schema/mutation.rs:8:1
```
Looking through the juniper_codegen crate I find myself confused about the codepath for async resolvers and I'm not confident enough to know if this is a bug or just an issue with the way I've implemented my server. The gist below has all of the Juniper bits in it - I haven't pushed the code to a repo just yet but I can if more info is needed.

https://gist.github.com/eeyun/aab7f6b9d2cb0eb35d0e14dddb9c3fc5

**Comment by engylemure** [comment]
Are you using the async feature? after enabled you should change the usage of 
```rust
let data: GraphQLRequest = ... ;
let res = data.execute(&schema, &context);
```
for :
```rust
let data: GraphQLRequest = ... ;
let res = data.execute_async(&schema, &context).await;
```

**Comment by eeyun** [comment]
I'm using the async feature with warp 1.20. You put me on the right track... I was calling the synchronous filter method in juniper_warp... omg. Thank you..
