### ISSUE TITLE
Resolve crashes in CI for Github Actions

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#531]
We are now seeing crashes in GitHub CI across all platforms and Rust versions. Tracking in https://github.com/rust-lang/rust/issues/69121

**Comment by LegNeato** [comment]
I have disabled Github Actions in the UI until this is resolved.

**Comment by sagiegurari** [comment]
I wonder if this was a temporary thing which is now resolved.
i moved all my projects to github actions and they are all working well (stable, beta, nightly and specific version).

**Comment by LegNeato** [comment]
I renabled it, we shall see

**Comment by LegNeato** [comment]
Nope, still the same issue.

**Comment by sagiegurari** [comment]
looks like a rustc bug worth reporting. wdyt?

**Comment by LegNeato** [comment]
Already reported above :-)

**Comment by msdinit** [comment]
Not an expert by any means, but is there a reason for [RUSTFLAGS: "-C link-dead-code"](https://github.com/graphql-rust/juniper/blob/master/.github/workflows/ci.yml#L63)?

Does not look like that variable is set for Azure pipelines, and if I remove it, checks for `nightly` [seem to pass for the most part](https://github.com/msdinit/juniper/actions/runs/143650580).
And the other way around, running `RUSTFLAGS="-C link-dead-code" cargo build --tests` seem to reproduce the error locally

**Comment by LegNeato** [comment]
Nice catch! I'll look into it.

**Comment by sagiegurari** [comment]
the deadcode flag is for code coverage to be more accurate

**Comment by tyranron** [comment]
With https://github.com/graphql-rust/juniper/pull/884 we removed the `RUSTFLAGS="-C link-dead-code"`. So this is resolved now.
