### ISSUE TITLE
execute_validated_query_async is using std::sync::RwLock  

### ISSUE THREAD

**Issue by jxs** [graphql-rust/juniper#532]
[`execute_validated_query_async`](https://github.com/graphql-rust/juniper/blob/master/juniper/src/executor/mod.rs#L745) is using `std::sync::RwLock` which blocks the thread while waiting to read/write, this will probably block the whole runtime if running under tokio's [`basic_scheduler`](https://docs.rs/tokio/0.2.11/tokio/runtime/struct.Builder.html#method.basic_scheduler).  

Both [`tokio`](https://docs.rs/tokio/0.2.11/tokio/sync/struct.RwLock.html) and [`async-std`](https://docs.rs/async-std/1.5.0/async_std/sync/struct.RwLock.html) offer `async` versions of the RwLock, there's also the `futures` crate [`Mutex`](https://docs.rs/futures/0.3.1/futures/lock/struct.Mutex.html)

**Comment by tyranron** [comment]
@jxs @LegNeato looking at the code in the [current master](https://github.com/graphql-rust/juniper/tree/aedb2d1eb453f605380ff527f88d7467253ba341), the described above is totally non-issue. `RwLock`'s locking is used in a [single place only in sync function](https://github.com/graphql-rust/juniper/blob/aedb2d1eb453f605380ff527f88d7467253ba341/juniper/src/executor/mod.rs#L608) and there is literally no way for the lock guard to live accross any `.await` point to block the underlying executor. This is totally correct usage of `RwLock` there (I'd rather prefer even regular `Mutex`, as there is no `read()` blocks at all), and using any async `Mutex`/`RwLock` will just create extra overhead with no benefit at all, as we do not require to block across `.await` points.
