### ISSUE TITLE
Need to add a `use futures;` statement to object derive w/ async feature.

### ISSUE THREAD

**Issue by thedodd** [graphql-rust/juniper#534]
**Describe the bug**
On the master branch, using the `async` feature, use of the derive macro `#[juniper::graphql_object(...)]` will cause a compilation error stating that `futures` is not in scope. Looks like this just needs a `use futures;` somewhere in the macro.

**To Reproduce**
Just pop a `#[juniper::graphql_object(...)]` on any valid struct with the `async` feature enabled, and don't `use futures;` anywhere in the module.

**Expected behavior**
Pretty common issue in macros. Just need to add a use statement.

**Comment by samuela** [comment]
I think this might be why `cargo test` is failing on 547cf3e36fa0532476295186b86954fab3a258f6 too:
```
error[E0432]: unresolved import `futures`
  --> integration_tests/juniper_tests/src/issue_398.rs:39:1
   |
39 | #[juniper::graphql_object]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `futures`
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
