### ISSUE TITLE
master version of the book is not up-to-date with master

### ISSUE THREAD

**Issue by samuela** [graphql-rust/juniper#539]
**Describe the bug**
I just noticed that the master version of the book (https://graphql-rust.github.io/juniper/master/index.html and linked to from https://github.com/graphql-rust/juniper/blob/master/README.md) is not actually up-to-date with the contents of `docs/book`.

**To Reproduce**
In particular the code blocks in https://graphql-rust.github.io/juniper/master/schema/schemas_and_mutations.html and https://github.com/graphql-rust/juniper/blob/master/docs/book/content/schema/schemas_and_mutations.md are not the same.

**Expected behavior**
The master book and master branch to be in alignment (via CI, etc).

**Additional context**
The book is very helpful! Thank you!

**Comment by LegNeato** [comment]
I believe this should be fixed when https://github.com/graphql-rust/juniper/pull/543 lands.
