### ISSUE TITLE
Macro `#[juniper::graphql_union]` does not impl `GraphQLTypeAsync`

### ISSUE THREAD

**Issue by UkonnRa** [graphql-rust/juniper#549]
**Describe the bug**

In the [master branch](https://github.com/graphql-rust/juniper/blob/a0b854f31c586fcf786f7ff1d5d563c5ce2d8b79/juniper_codegen/src/impl_union.rs#L155), bacause macro `juniper::graphql_union` does not impl `GraphQLTypeAsync`, the async function is not usable

**Comment by LegNeato** [comment]
Yep, unions and interfaces are not supported yet on master.

**Comment by jadedevin13** [comment]
This doesn't work in custom scalars as well.

**Comment by arlyon** [comment]
All the tests pass on my machine with a small change to a lifetime:

```rust
diff --git a/juniper/src/macros/tests/union.rs b/juniper/src/macros/tests/union.rs
index 6dfbfe75..089ea3b2 100644
--- a/juniper/src/macros/tests/union.rs
+++ b/juniper/src/macros/tests/union.rs
@@ -57,7 +57,7 @@ impl CustomName {
 }
 
 #[crate::graphql_union_internal]
-impl<'a> WithLifetime<'a> {
+impl<'b> WithLifetime<'b> {
     fn resolve(&self) {
         match self {
             Concrete => match *self {
```
