### ISSUE TITLE
QuickStart with Warp

### ISSUE THREAD

**Issue by DrYSG** [graphql-rust/juniper#560]
I am having a bit of trouble getting started with Warp and Juniper. Perhaps I could help improve the documentation?

**Cargo.toml**
```
[dependencies]
    warp = "0.1.8"
    juniper = "0.14.2"
    juniper_warp = "0.5.2"
    log = "0.4.8"
```

I cut and pasted the main.rs from: https://github.com/graphql-rust/juniper/blob/master/juniper_warp/examples/warp_server.rs

and these are the errors I get (which clearly indicates that I do not know what crates/modules you are expecting, but this page seemed to indicate that this was all I needed in Cargo.toml : 
https://graphql-rust.github.io/servers/warp.html

**Errors**

```
Compiling rust-server v0.1.0 (D:\CRIME\rust-server)
error[E0433]: failed to resolve: could not find `tests` in `juniper`
 --> src\main.rs:6:5
  |
6 |     tests::{model::Database, schema::Query},
  |     ^^^^^ could not find `tests` in `juniper`

error[E0433]: failed to resolve: use of undeclared type or module `env_logger`
  --> src\main.rs:19:5
   |
19 |     env_logger::init();
   |     ^^^^^^^^^^ use of undeclared type or module `env_logger`

error[E0433]: failed to resolve: use of undeclared type or module `Database`
  --> src\main.rs:33:41
   |
33 |     let state = warp::any().map(move || Database::new());
   |                                         ^^^^^^^^ use of undeclared type or module `Database`

error[E0412]: cannot find type `Query` in this scope
  --> src\main.rs:11:33
   |
11 | type Schema = RootNode<'static, Query, EmptyMutation<Database>>;
   |                                 ^^^^^ not found in this scope

error[E0412]: cannot find type `Database` in this scope
  --> src\main.rs:11:54
   |
11 | type Schema = RootNode<'static, Query, EmptyMutation<Database>>;
   |                                                      ^^^^^^^^ not found in this scope

error[E0425]: cannot find value `Query` in this scope
  --> src\main.rs:14:17
   |
14 |     Schema::new(Query, EmptyMutation::<Database>::new())
   |                 ^^^^^ not found in this scope

error[E0412]: cannot find type `Database` in this scope
  --> src\main.rs:14:40
   |
14 |     Schema::new(Query, EmptyMutation::<Database>::new())
   |                                        ^^^^^^^^ not found in this scope

error: aborting due to 7 previous errors

Some errors have detailed explanations: E0412, E0425, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `rust-server`.
```

**Comment by LegNeato** [comment]
Hmmmm, I'm sure we can figure this out, thanks for the report! What command are you running? Does enabling the `expose-test-schema` feature make it work?

**Comment by kemicofa** [comment]
@LegNeato I got the same issue, but after I took a similar structure from your `Cargo.toml` it worked.

```
[dependencies]
warp = "0.1.8"
juniper = { version = "0.14.2", features = ["expose-test-schema", "serde_json"] }
serde_json = "1.0.24"
serde_derive = "1.0.75"
failure = "0.1.2"
futures = "0.1.29"
serde = "1.0.75"
tokio-threadpool = "0.1.7"
env_logger = "0.5.11"
log = "0.4.3"
percent-encoding = "1.0"
futures03 = { version = "0.3.1", optional = true, package = "futures", features = ["compat"] }
juniper_warp = "0.5.2"
```

**Comment by LegNeato** [comment]
Yeah, the key is `features = ["expose-test-schema", "serde_json"]` I believe.

**Comment by DrYSG** [comment]
Ok, This is working great for me. As an aid to newbies you may want to also refer folks to the model for the schema:  https://github.com/graphql-rust/juniper/blob/master/juniper/src/tests/model.rs

As well as update the Readme for juniper_warp (although I am already using the new async  subscribe branch in my code): https://github.com/graphql-rust/juniper/tree/master/juniper_warp

**Comment by japsu** [comment]
Could you please make an out-of-tree example? Meaning one that is a crate of its own and not part of the `juniper_warp` crate. This would mean it easier to start developing a server that uses `juniper_warp` as dependencies would already been laid out in a way that does not use `path` references.
