### ISSUE TITLE
Make `graphql_scalar` a proc macro

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#571]
Make `graphql_scalar` a proc macro to match everything else...currently it is only a macro with some wonky syntax.

**Comment by andrisak** [comment]
I'd like to give this a try.

**Comment by andrisak** [comment]
Would this be a suitable approach?

Create a new trait that gets the information needed for the macro:
```rust
trait ParseCustomScalarValue<'a, T> {
    const DESCRIPTION: &'a str;
    fn resolve(&self) -> juniper::Value;
    fn from_input_value(value: &juniper::InputValue) -> Option<T>;
    fn from_str<'b>(value: ScalarToken<'b>) -> ParseScalarResult<'b, DefaultScalarValue>;
}
```

Then implement the trait for the custom scalar type when using the new macro:
```rust
struct UserId(String);

juniper::graphql_scalar! {
    impl<'a> ParseCustomScalarValue<'a, UserId> for UserId {
        const DESCRIPTION: &'a str = "my description";

        fn resolve(&self) -> juniper::Value {
            Value::string(&self.0)
        }

        fn from_input_value(value: &juniper::InputValue) -> Option<UserId> {
            value.as_string_value().map(|s| UserId(s.to_owned()))
        }

        fn from_str<'b>(value: ScalarToken<'b>) -> ParseScalarResult<'b, DefaultScalarValue> {
            <String as ParseScalarValue>::from_str(value)
        }
    }
}
```

**Comment by LegNeato** [comment]
Close! We'll want to to be a proc macro, not a macro (so annotate with `#[juniper::graphql_scalar]` not the macro `juniper_graphql!`).

We have a general function to parse an `impl` block and handle a lot of this.fkr example, the description can be pulled from doc comments rather than making it part of the proc macro.

Also, take a look at how `graphql_object` is implemented.

**Comment by andrisak** [comment]
I've created a WIP PR just to verify the approach. What do you think?
