### ISSUE TITLE
Published version has incorrect serde_json dependency

### ISSUE THREAD

**Issue by SirWindfield** [graphql-rust/juniper#573]
**Describe the bug**
The uploaded version on crates.io has a missing dependency declaration for the `expose-test-schema` feature, resulting in compilation errors when enabling the feature.

**To Reproduce**
Add juniper as a dependency and enable the feature.

**Expected behavior**
The project compiles without problems.

**Additional context**
The feature is enabled because I am developing a library on top of juniper and want to use the test module for testing purposes.

[Here](https://docs.rs/crate/juniper/0.14.2/source/Cargo.toml) is a link to the `Cargo.toml` file uploaded to crates.io. The `features` section looks like this:
```toml
[features]
default = ["chrono", "url", "uuid"]
expose-test-schema = []
```

`expose-test-schema` is missing the `serde_json` value. It is, however, correctly specified on master:

```toml
[features]
expose-test-schema = ["serde_json"]
default = [
    "bson",
    "chrono",
    "url",
    "uuid",
]
```

**Comment by LegNeato** [comment]
We're likely not going to push another release for this. You should be able to add serde_json yourself.

**Comment by SirWindfield** [comment]
I just saw that this has been fixed on master already.
