### ISSUE TITLE
Better way to negotiate the WebSocket protocol

### ISSUE THREAD

**Issue by spacemeowx2** [graphql-rust/juniper#584]
https://github.com/seanmonstar/warp/issues/496

In the `warp_subscriptions` example, the playground cannot connect to the server via WebSocket because the WebSocket implementation in `wrap` has a unconfigurable `Sec-WebSocket-Protocol` header. Currently we can do a workaround adding the header manually.

**Comment by cloudsftp** [comment]
Is this till current?
The example seems to work w/o the workaround

**Comment by tyranron** [comment]
Fixed by auto-negotiating `Sec-WebSocket-Protocol` in https://github.com/graphql-rust/juniper/pull/1191.
