### ISSUE TITLE
Current version of juniper_hyper example is not working.

### ISSUE THREAD

**Issue by huseyinyilmaz** [graphql-rust/juniper#590]
Hello,
I am trying to use this example as a starting point to a project but it is giving me bunch of errors. 
https://github.com/graphql-rust/juniper/blob/6e4bc127b05dc29f7832cbf468c9fb2bc18f78ec/juniper_hyper/examples/hyper_server.rs
After looking more closely I realized that this is not working because last version on hyper_juniper did not have async support.
https://github.com/graphql-rust/juniper/blob/juniper-0.14.2/juniper_hyper/examples/hyper_server.rs

I was wondering if there will be any new juniper and juniper_hyper release soon.

Thanks.

**Comment by LegNeato** [comment]
Does using master for both work? Either the latest releases need to be used together or the latest master of both.

**Comment by huseyinyilmaz** [comment]
Here is the original example with current master branch:

https://github.com/huseyinyilmaz/juniper_test/tree/sample

With this I realized that module structure was changed. So I tried to put something together from juniper book examples and I ended up with this branch: 
https://github.com/huseyinyilmaz/juniper_test/tree/master

This version is also not working.

**Comment by LegNeato** [comment]
Ah! `graphql_object!` does not exist on master. Instead use the `juniper::graphql_object` proc macro.
