### ISSUE TITLE
Error handling for input object types.

### ISSUE THREAD

**Issue by TanaseHagi** [graphql-rust/juniper#593]
How does one do error handling for input object types?

The example below is for object types, but there is no example for input object types.
https://graphql-rust.github.io/juniper/master/types/objects/error_handling.html

I am just beginning with rust so please excuse me if the solution is obvious.

Thanks.

**Comment by LegNeato** [comment]
I'm fairly positive that for any input object that cannot be automatically deserialized via `serde` (https://serde.rs) into the rust type, `juniper` returns an execution error.

It is then up to you (or the http server library integration) to decide how to send that error back to the client.

Please let me know if this doesn't work!


Please try it and let me know if that is not the case. Welcome to Rust!
