### ISSUE TITLE
expected `()`, found struct `Context`

### ISSUE THREAD

**Issue by RemiKalbe** [graphql-rust/juniper#601]
Hi,

I'm using Actix and I'm trying to set a context.
I've done the following

```rust
#[derive(Clone)]
pub struct Context {
    pub client: reqwest::Client,
}

impl juniper::Context for Context {}
impl Context {
    pub fn new(client: reqwest::Client) -> Self {
        Self { client }
    }
}

async fn graphql(
    st: web::Data<Arc<Schema>>,
    data: web::Json<GraphQLRequest>,
    client: web::Data<reqwest::Client>,
) -> Result<HttpResponse, Error> {
    let client = client.into_inner().as_ref().clone();
    let ctx = Context::new(client);

    let user = web::block(move || {
        let res = data.execute(&st, &ctx);
        Ok::<_, serde_json::error::Error>(serde_json::to_string(&res)?)
    })
    .await?;
    Ok(HttpResponse::Ok()
        .content_type("application/json")
        .body(user))
}
```
I've done that by following what they did https://github.com/clifinger/canduma/blob/master/src/graphql/handler.rs and https://github.com/LantosTG/rust_site/blob/master/src/main.rs

But sadly I'm getting the following error:

```
error[E0308]: mismatched types
  --> src/main.rs:43:37
   |
43 |         let res = data.execute(&st, &ctx);
   |                                     ^^^^ expected `()`, found struct `Context`
   |
   = note: expected reference `&()`
              found reference `&Context`
```
I have no idea what I did wrong 😳

**Comment by LegNeato** [comment]
Does https://github.com/graphql-rust/juniper/pull/603 help?

**Comment by engylemure** [comment]
@RemiKalbe Can you show your schema definition? it seems that your problem is related to the Context itself being a empty tuple in the RootNode usage for the Schema type definition

**Comment by RemiKalbe** [comment]
@engylemure 
Ok so It works now. I didn't know I was forced to add that
```
#[juniper::object(
    Context = Context,
)]
```
I just stopped at the error, thinking I did something wrong there, or that the API changed, I didn't want to go further.
It's a bit confusing when you are new to rust.

Anyway thank you 🙏
