### ISSUE TITLE
Composing an error response

### ISSUE THREAD

**Issue by biot023** [graphql-rust/juniper#602]
Hi -- I'm validating an input object to an update mutation.
It would be really great if I could compose the `extensions` object of the `FieldError` to look something like this:

````
{
  "errors": [
    ["title", "Too short"],
    ["title", "Invalid characters"],
    ["description", "Invalid characters"]
  ]
}
````

My attempts to compose a `Value::Object` to match that were (I think) successful but I failed when I tried to substitute it to the `extensions` bit of `FieldError::new`.
Am I misunderstanding what the `extensions` bit is for?
And could someone advise me on the best way to achieve a list of errors the client can parse when composing a `FieldError`?
Thanks for any and all advice,
   Doug.

**Comment by LegNeato** [comment]
Does the example at https://graphql-rust.github.io/juniper/master/types/objects/error_handling.html#structured-errors help?

**Comment by biot023** [comment]
Hi @LegNeato, thanks for the reply.
Those docs don't really help, sorry. What I need to be able to do is to build up an error based on whether various input fields are deemed valid or not.
So something like:

````
if is_invalid(title) {
    errors.push(("title", "Invalid characters"));
}
if is_invalid(description) {
    errors.push(("description", "Invalid characters"));
}
// Now build the `FieldError` `extensions` with the errors `Vec<(&str, &str)>`.
````

The examples in the docs just show you how to build a static structure, I need to build one procedurally.
I have an ugly hack of just listing them in the error description for the time being but I'll really want to fix that before I open our API up!

**Comment by LegNeato** [comment]
You could do something like:

```rust
enum CustomInputError {
    TooShort(i32),
}

impl juniper::IntoFieldError for CustomError {
    fn into_field_error(self) -> juniper::FieldError {
        match self {
            CustomError::TooShort(x) => juniper::FieldError::new(
                "Too short",
                graphql_value!({
                    "min_length": x
                }),
            ),
        }
    }
}

struct Example {}

#[juniper::graphql_object]
impl Example {
    fn whatever(&self, title: MyTitle) -> Result<bool, CustomError> {
        if is_too_short(title) {
            Err(CustomError::TooShort(5))
        }
        // Do your logic or additional checks that return other errors.

        // Success case.
        Ok(true)
    }
}
```

As is standard in GraphQL and [mentioned in the book](https://graphql-rust.github.io/juniper/master/types/objects/error_handling.html#structured-errors :
), for every field that fails with a `FieldError` it is added to the `errors` array and the structured key/value pairs for the error are put in extensions as-is (again, following the GraphQL spec):


```json
{
  "errors": [
    "message": "Too short",
    "locations": [{ "line": 2, "column": 4 }]),
    "extensions": {
      "min_length": 5
    }
  ]
}
```

Please let me know fi that answers your question or not!

**Comment by LegNeato** [comment]
You could also just build the key/value object and then generate the `FieldError` directly with the aggregate values as the second arg to `new()`.

**Comment by biot023** [comment]
@LegNeato 
Ah! I see! So what I really need to do is to be able to raise an error for every failed field.
Which suggests to me that I'm probably doing something fundamentally wrong.
I have an update input that has one method `apply()` that validates each field procedurally before running the update. The first validation to fail will raise an appropriate error but that will immediately exit with the `Err` part of the `FieldResult` and we'll never know about any other fields that may have been invalid.
For example:

```
fn apply(context: &Context) -> FieldResult<Item> {
    if is_too_short(&self.name) {
        return Err(CustomError::TooShort("name", 5));
    }
    if is_too_short(&self.description) {
        return Err(CustomError::TooShort("description", 32));
    }
    // Perform updates and compose item to return...
    Ok(item)
}
```

If the title was too short, we'd never find out whether or not the description was also too short.
I notice in your example that you didn't return the `Err`-wrapped `CustomError`: is that a typo or have I missed something fundamental that would easily allow me to do what I'm after?
Thanks again for all your help and my apologies if I'm missing something that should be obvious.
   Doug.

**Comment by biot023** [comment]
> You could also just build the key/value object and then generate the `FieldError` directly with the aggregate values as the second arg to `new()`.

Hi again @LegNeato -- would you be able to offer a pointer as to how I would do that?
I'm looking at the `juniper::Value` enum but I'm not seeing how to construct a key/value object from it.

**Comment by biot023** [comment]
Okay, this might not be the most elegant code you've ever read (!) but here's how I've got it working for now:

                                                                
```
let errs: Vec<(&str, juniper::Value)> = errs.iter().map(|(k, v)|
    (*k, juniper::Value::scalar(*v))                            
).collect();                                                    
                                                                
let errs = juniper::Value::Object(errs.into_iter().collect());  
                                                                
Err(FieldError::new(                                            
    "Item update fields were invalid",                          
    errs,                                                       
))       
```                                                       

I'll see how I get on with it...

**Comment by biot023** [comment]
Just as a final update, this is what I ended up with:

```
pub fn errs_vec_to_juniper_value(errs: Vec<(String, String)>) -> juniper::Value {
    let errs: Vec<(juniper::Value)> = errs.iter().map(|(k, v)| {                 
        let row = (                                                              
            &(*k)[..],                                                           
            juniper::Value::scalar(v.clone()),                                   
        );                                                                       
        juniper::Value::Object(vec![row].into_iter().collect())                  
    }).collect();                                                                
                                                                                 
    let errs = juniper::Value::List(errs);                                       
                                                                                 
    juniper::Value::Object(                                                      
        vec![("errors", errs)].into_iter().collect(),                            
    )                                                                            
}                                                                                
```

If something looks horribly wrong do please feel free to correct it!
It works, however, which is nice.

**Comment by jmpunkt** [comment]
I also came across input validation recently. There two possibilities handling input validation. Either you return all errors as error responses (like you did) or use unions. The idea is that you separate your errors into two classes, one class for hard errors and another class for soft errors. Soft errors describe things like failed input validation. These errors are directly connected to the user input and can be fixed by the user. Hard errors on the other hand are, e.g., database errors. Returning a hard error results in an error response. Soft errors are part of your GraphQL schema and return a union where it is either the desired object or an error object. Consider the following example

```rust
#[derive(GraphQLObject)
struct Item {
    name: String,
    amount: i32,
}

#[derive(GraphQLObject)
struct ValidationError {
   nameError: String,
   amountError: String,
}

#[derive(GraphQLUnion)
enum NewItemResult {
    Item(Item),
    Error(ValidationError),
}
```

The model contains information that a certain error is possible and needs to be handled by the client. Compared to the other approach, it provides more type-safety and the documentation is built-in. An obvious downside of this approach is the large amount of required types. For each function with input validation a type is required. Types can be reused if the all input arguments are the same. 
Since the soft error class is not limited to input validation, it is also possible adding more error cases to the union.

Notice that this is only possible on the `master` branch since the support for derive GraphQLUnion is new. The impl macro must be used if a release version is targeted.

Since you asked, I would change a small thing in your example

```rust
    let errs: Vec<(juniper::Value)> = errs.iter().map(|(k, v)| {                 
        let row = (                                                              
            &(*k)[..],                                                           
            juniper::Value::scalar(v.clone()),                                   
        );                                                                       
        juniper::Value::Object(vec![row].into_iter().collect())                  
    }).collect();  
```
into


```rust
    let errs: Vec<(juniper::Value)> = errs.into_iter().map(|(k, v)| {                 
        let row = (                                                              
            k.as_str(),                                                           
            juniper::Value::scalar(v),                                   
        );                                                                       
        juniper::Value::Object(vec![row].into_iter().collect())                  
    }).collect();  
```

**Comment by biot023** [comment]
@jmpunkt Yes, that last example is much nicer, cheers! As you can probably guess, I got it working by trial and error and gave up before a proper refactoring! :)
And your suggestion for breaking the errors up is really informative as well, thank you. I'll probably not adopt it for now as I try to avoid the very bleeding edge for work stuff but it was a really interesting read and a nice design pattern, thank you.

**Comment by biot023** [comment]
@jmpunkt 
Just a final note -- your suggested design pattern stayed with me!
So I've taken a middle route and am returning `*Result` objects that have option fields for:

- the items we'd expect to see returned
- validation errors

The first is `Some(Item)` and the second is `None` in the case of success.
In the unsuccessful case, obviously, the second is `Some(Vec<Vec<String>>)`, which converts nicely to 2D array of errors for GraphQL.

It's miles better than what I was attempting -- thanks so much for your advice, again.
I'll close this thread, now.

**Comment by LegNeato** [comment]
Would love this in the book of you are willing!
