### ISSUE TITLE
Build a GraphQL Client

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#61]
All the pieces are there.

* a parser
* a type system
* value types for representing graphql data

Building a client should be relatively straight forward.

I'll tackle this when I have some time.

**Comment by LegNeato** [comment]
@theduke do you still intend to tackle this? I would love to help but feel my rust-fu isn't quite there yet.

**Comment by LegNeato** [comment]
@zsck mentioned in gitter that they might be interested in working on this.

**Comment by theduke** [comment]
Like we have documented, the first step would be to extract the parser and AST from the main crate to make it reusable. 

This should also include making the AST easily shareable so it can be used with tokio.

I believe @mhallin already did some experiments in this branch: https://github.com/graphql-rust/juniper/tree/async-experiments

**Comment by theduke** [comment]
Closing since we have the client in the org now.

We still need to figure out what code can be shared between the client and juniper, though.

**Comment by tomhoule** [comment]
There is another issue I opened about sharing query validation code (since it is in the spec and all that is needed is the query and the schema, as far as I know). Juniper has far better validation so the main beneficiary would be graphql-client. Other than that I don't have many ideas but it is of course interesting.

**Comment by theduke** [comment]
I guess in a perfect world we would share:


* parser
* AST
* Value representation
* Validation logic
* testing utilities

It would also be awesome to instantiate a client from a server Schema definition
I haven't looked at the client code yet so I don't know how feasible this is.

But that would be the ideal state for me.

**Comment by tomhoule** [comment]
I have thought about using the juniper schema representation as an additional source (besides schema.json and .graphql schemas), but since graphql-client does code generation, we would need to instantiate the schema at compile time, which sounds challenging.
