### ISSUE TITLE
Is there any way to centrally modify a field error before it's returned?

### ISSUE THREAD

**Issue by meh** [graphql-rust/juniper#622]
For instance on the non GraphQL side of things I use `HttpApiProblem` and convert from an `anyhow::Result` into more meaningful responses, or fail with an internal server error if the error isn't supposed to bubble up to the user.

Is there anything I can do aside from panicking instead of bubbling up errors?

**Comment by tyranron** [comment]
@meh what we do for this is:
- Have our own `graphql::Error` type which `impl juniper::IntoFieldError` and return this type anywhere in schema resolvers.
- For any other errors which bubble up into resolvers we simply `impl Into<graphql::Error>` and just let `?` operator to do the stuff.

**Comment by LegNeato** [comment]
Do the new docs at https://graphql-rust.github.io/juniper/master/types/objects/error_handling.html#errors-backed-by-graphqls-schema help as well?

**Comment by meh** [comment]
That does help a bit, but it's still too boilerplatey for my taste, in an ideal scenario I would have some way to convert an `anyhow::Result` into a validation error or a critical error by centrally doing downcasting and conversion.

**Comment by tyranron** [comment]
@meh you may still have you own `GraphQlError` type which impls `impl juniper::IntoFieldError` and have a central `impl From<anyhow::Error>`.

**Comment by meh** [comment]
@tyranron duh, I'm dumbo, that's a very good point, I'll give that a try, thanks!
