### ISSUE TITLE
Best Practice for requests authorizations using Actix-web

### ISSUE THREAD

**Issue by GioPat** [graphql-rust/juniper#625]
Hello,
I am using actix-web 2.0.0 as webserver that supports authentication using JWT holding user uuid as one of the claims through a middleware (you can find a similar example [here](https://github.com/actix/examples/blob/master/middleware/src/redirect.rs)).
The only solution that I found, reading lots of documentation, was to:
- Create an actix state with the user uuid intiated to _empty_ at the start of the server.
- Fill this user uuid in the middleware by encoding the JWT passed in the request
- In the junper request handler use the actix state extractor (web::data) to get the user id and then handle the authorization logic directly in the handler.

I am afraid this is not the best practice to handle authorization, I would be very grateful if someone who already did this job could share with me some hints!

Thanks 🙏

**Comment by LegNeato** [comment]
@GioPat does https://github.com/BrendanBall/example-actix-web-juniper-diesel or https://github.com/mattdamon108/rust_graphql_api_boilerplate or https://github.com/davidpdrsn/graphql-app-example help you?

**Comment by LegNeato** [comment]
Going to close this out, feel free to comment if you haven't figured it out!
