### ISSUE TITLE
rust-lang/rust#70814: code using quote generates false lint warnings for unused_braces in juniper::graphql_object

### ISSUE THREAD

**Issue by grantperry** [graphql-rust/juniper#626]
One liner function definitions causes a lint warning about unused braces. Removing said braces, creates invalid rust.
rust-lang/rust#70814
```
warning: unnecessary braces around block return value
   --> src/models/user.rs:137:63
    |
137 |     fn ticket(&self, context : &SharedContext) -> Option<Ticket> { self.get_ticket(context) }
    |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these braces
```

Minimum example
```
#[juniper::graphql_object]
impl Obj {
    fn ticket(&self) -> &str { &self.field }
}
```

I expect no lint errors.

cargo 1.44.0-nightly (ebda5065e 2020-04-16)

**Comment by LegNeato** [comment]
Looks like this is going to be fixed in clippy.

**Comment by Igosuki** [comment]
More than a year later and still hasn't been fixed

**Comment by Igosuki** [comment]
As a reference anyone landing here, add a linter allowance in the mod ```#![allow(unused_braces)]```

**Comment by tyranron** [comment]
@Igosuki this should be already resolved in `master` due to using `#[automatically_derived]` attribute in #971.

**Comment by Igosuki** [comment]
Cool, I'll wait for it to land as a release

**Comment by twiclo** [comment]
I'm experiencing this on juniper 0.15.10. Any suggestions? (Other than the allow macro)

**Comment by tyranron** [comment]
@twiclo unfortunately, `juniper` 0.15.10 doesn't include #971, it's only in `master` for the moment.
