### ISSUE TITLE
Union behavior is different to GraphQL spec

### ISSUE THREAD

**Issue by jmpunkt** [graphql-rust/juniper#627]
**Describe the bug**
Juniper allows creating GraphQL unions with non-objects as variants. The GraphQL spec does not allow to create such unions. It is possible to compile the code, but the user receives and error messages on the playground website, like the following:
```json
{
  "message": "Expected String to be a GraphQL Object type.",
  "stack": "..."
}
```

**To Reproduce**
```rust
enum Character {
    Human(String),
}

#[juniper::graphql_union]
#[graphql(Scalar = juniper::DefaultScalarValue, Context = (), noasync)]
impl Character {
    fn resolve(&self) {
        match self {
            String => { match *self { Character::Human(ref h) => Some(h) } },
        }
    }
}

#[derive(juniper::GraphQLObject)]
#[graphql(Scalar = juniper::DefaultScalarValue,Context = (), noasync)]
pub struct Query {
    test: Character
}
```

Notice that there is no difference between using the `impl` macro or the derive macro for the union type. Both compile and create the same error.

**Expected behavior**
This should not compile. In the best case the proc macro should point out that `String` is not an GraphQL object.

**Comment by jmpunkt** [comment]
I have notice that other types also do not follow the specification correctly. For example, objects (impl macro) can be empty which is not allowed by the specification.

The easiest way to prevent this, is defining failing code generation tests cases. A quick search suggests to use something like [trybuild](https://docs.rs/trybuild/1.0.25/trybuild/) to test Juniper's proc macros.

I would like to know how you(@LegNeato) think about this?

**Comment by LegNeato** [comment]
For empty objects, we should be able to handle that in the proc macro and fail the compile. Please file a different issue!

For requiring a GraphQL object for unions, that will be harder. I like the idea of generating a test. We might also be able to generate a line that only compiles if it is an object but I am not sure. Right now it seems to require GraphQLType, we could have a marker trait just for objects and use trait bounds to enforce the Union's members implement it.
