### ISSUE TITLE
Unable to find Juniper_actix crate on crates.io

### ISSUE THREAD

**Issue by kunjee17** [graphql-rust/juniper#633]
Sorry for extremely dumb question. I m pretty sure I am missing something here. But juniper_actix package is already there in master but I can't find in crates.io . 

As there is current and master version of book so I m sure I m missing some release cycle or something. 

Is there any details regarding this? And is there any way I can pull that package or any road map when it will land crates.io

**Comment by LegNeato** [comment]
It has yet to be released to crates.io as it relies on async which is only on master. We will do a release once interfaces and unions work under async.

**Comment by kunjee17** [comment]
Thanks @LegNeato for reply. Will be waiting for that then. Again thanks for great work and nice library.
