### ISSUE TITLE
Disallow empty GraphQLBatchRequests

### ISSUE THREAD

**Issue by tyranron** [graphql-rust/juniper#639]
**Is your feature request related to a problem? Please describe.**  
At the moment, it's possible to deserialize `GraphQLBatchRequest` as an empty `Vec<GraphQLRequest>`. The downstream implementations (like `juniper_warp`) rely transparently on that, executing empty batch and returning empty response.

I'm unsure this is OK. Maybe, it's better to reject empty batches at deserialization level?

**Describe the solution you'd like**  
The one was implemented once in early `juniper_actix` iterations:
```rust
enum GraphQLBatchRequest<S = DefaultScalarValue>
where
    S: ScalarValue,
{
    Single(GraphQLRequest<S>),
    #[serde(deserialize_with = "deserialize_non_empty_vec")]
    Batch(Vec<GraphQLRequest<S>>),
}

fn deserialize_non_empty_vec<'de, D, T>(
    deserializer: D,
) -> Result<Vec<T>, D::Error>
where
    D: de::Deserializer<'de>,
    T: Deserialize<'de>,
{
    let v = Vec::<T>::deserialize(deserializer)?;
    if v.is_empty() {
        Err(de::Error::invalid_length(0, &"a positive integer"))
    } else {
        Ok(v)
    }
}
```

**Describe alternatives you've considered**  
Leave it "as is". But seems to be more error-prone for frontends.

-------------------

If it something desirable, I'll submit the PR shortly.

**Comment by LegNeato** [comment]
Yeah, I think we should reject empty batch requests as it almost certainly points to a bug on the client side.
