### ISSUE TITLE
Allow specifying type for `#[graphql_object]`

### ISSUE THREAD

**Issue by zhenwenc** [graphql-rust/juniper#647]
**Is your feature request related to a problem? Please describe.**
Consider the following case:
```rust
#[derive(Debug, Clone)]
pub struct User {
    pub id: i32,
    pub first_name: String,
    pub last_name: String,
    pub notes: Vec<Note>,
}

#[derive(Debug, Clone)]
pub struct Note {
    pub name: String,
}
```

In order to define extra field resolvers for a struct, I need to use the `graphql_object` macro:
```rust
#[juniper::graphql_object]
impl User {
    pub fn full_name(&self) -> String {
        format!("{} {}", self.first_name, self.last_name)
    }
}
```

which generates `impl juniper::GraphQLType<juniper::DefaultScalarValue> for User`. However, I am also using `diesel` and defining SQL queries in `impl User`, clearly I don't want those functions to be exposed as field resolvers for `User` object.

**Describe the solution you'd like**
I am thinking to use a similar approach for [objects-and-generics in the docs](https://graphql-rust.github.io/juniper/current/advanced/objects_and_generics.html):

```rust
#[juniper::graphql_object]
impl User {
    pub fn full_name(&self) -> String {
        format!("{} {}", self.first_name, self.last_name)
    }

    // Instead of doing this...
    // pub fn notes(&self) -> Vec<GraphObject<Note>> {
    //     self.notes.clone().into_iter().map(GraphObject).collect()
    // }

    // I prefer this...
    pub fn notes(&self) -> Vec<Note> {
        self.notes.clone()
    }
}

struct GraphObject<T>(T);

impl Note {
    fn get_notes_from_database() -> Vec<Note> {
        vec![]
    }
}

#[juniper::graphql_object(
    name = "Note", 
    _type = Note,  // <-- proposed solution
)]
impl GraphObject<Note> {
    fn name(&self) -> String {
        self.name.clone()
    }
}
```

No sure if reading from an optional `_type` attribute would work, similar to the `name` attribute:

https://github.com/graphql-rust/juniper/blob/358ca27d28fd6e5497effcf097e2729193ad0d50/juniper_codegen/src/impl_object.rs#L34

Thanks very much for the great library!

**Comment by LegNeato** [comment]
I am likely misunderstanding, but you can have two impl blocks:


```rust
#[juniper::graphql_object]
impl User {
    pub fn full_name(&self) -> String {
        format!("{} {}", self.first_name, self.last_name)
    }
}

impl User {
  pub fn foo() {
    // Do whatever, this will not be exposed in GraphQL
  }
}
```

The GraphQL impl block isn't really an impl block...we just use that format to make it familiar to rust folks, provide syntax highlighting in IDEs, and not create another DSL. But it generates a `impl GraphQLType for User` block so you can still use `impl User` to do whatever you need.

I believe you can make the GraphQL one this (note the `GraphQLObject`):

```rust
#[juniper::graphql_object]
impl GraphQLObject for User {
    pub fn full_name(&self) -> String {
        format!("{} {}", self.first_name, self.last_name)
    }
}
```

to make it clearer.

Does that work?

**Comment by zhenwenc** [comment]
@LegNeato Thank you very much for the clarification! Sorry, it was my mistake. 🤦‍♂️

Both having two `impl User` block and `impl GraphQLObject for User` works, and I do prefer the second one as it seems more clear. Thanks!

Closing this as its not an issue. Sorry for the confusion!

**Comment by LegNeato** [comment]
Perhaps we should change the docs to use the second form, hmmm. Glad it fixed your issue!
