### ISSUE TITLE
Implement Subscriptions for juniper-actix

### ISSUE THREAD

**Issue by mihai-dinculescu** [graphql-rust/juniper#649]
It would be awesome to have subscriptions in juniper-actix.

I'm willing to put effort into making it happen, but I will need some guidance.

**Comment by LegNeato** [comment]
That would be great! What guidance do you need?

**Comment by mihai-dinculescu** [comment]
Tbh I think that I'm OK for now.

So far I have:
- got a new examples/actix_subscriptions example up and running based on the [juniper_actix example](https://github.com/graphql-rust/juniper/blob/master/juniper_actix/examples/actix_server.rs)
- Followed the [Actix WS example](https://actix.rs/docs/websockets) to get a Juniper Subscription to connect to the Actix WS

Next, I will look into actually implementing the WS handler. `juniper_warp::subscriptions` and the actix ws examples should help me get there.

**Comment by LegNeato** [comment]
Looks like this landed, thank you!

**Comment by kamalkech** [comment]
@mihai-dinculescu not working correctly for me

**Comment by tyranron** [comment]
@kamalkech this may be quite outdated, please, follow the [example of the latest `juniper_actix` version](https://docs.rs/juniper_actix/latest/juniper_actix/#examples).
