### ISSUE TITLE
Implement test coverage analysis on CI

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#65]
Right now there is a lot of duplication between the appveyor and travis test suites.

The build + test workflow should be implemented with a build tool like (cargo-make)[https://github.com/sagiegurari/cargo-make] to prevent errors and duplication.

**Comment by mhallin** [comment]
I _had_ code coverage running a while ago but they were relying on some hacks and inevitably stopped working. Now that https://github.com/xd009642/tarpaulin seems to work we can maybe add it back to Travis (as it only works on Linux).

I find the coverage tools useful to spot problematic areas that aren't covered by tests: usually you'll find places in error handling and other "negative" logic by looking at missed lines.

**Comment by theduke** [comment]
Cargo make is now in use!

I'm repurposing this issue to track getting test coverage analysis on CI.

**Comment by mhallin** [comment]
Resolved by #110.
