### ISSUE TITLE
Enum values documentation in Playground not parsed.

### ISSUE THREAD

**Issue by ralpha** [graphql-rust/juniper#653]
**Describe the bug**
I used `juniper_rocket::playground_source("/graphql")` to render a playground page.
I noticed that for Enums (parsed with `#[derive(GraphQLEnum)]`) the documentation for the values is not parsed, so text is not bold and links are not interpreted.
![Screenshot from 2020-05-06 18-27-03](https://user-images.githubusercontent.com/2608639/81203527-5b869800-8fc8-11ea-81b4-f320a81861c0.png)
In GraphiQL it works correctly:
![Screenshot from 2020-05-06 18-27-48](https://user-images.githubusercontent.com/2608639/81203618-70fbc200-8fc8-11ea-8079-0527433f34c2.png)

**To Reproduce**

1. Setup an application with GraphQl
1. Enable the playground somewhere: `juniper_rocket::playground_source("/graphql")`
1. Open the playground.
1. Open 'Docs' on the right side.
1. Navigate to an Enum with documentation and see documentation for values. (the enum description itself is parsed correctly.)

For documentation I used:
```
/// The documention from here is interpreted **correctly**
#[derive(GraphQLEnum)]
pub enum RegionType{
    /// A [swamp](https://example.com/Swamp) is a type of biome,
    /// flooded permanently or only periodically,
    /// with an abundance of foliage, including heavy, specialized tree-growth and a vast ecosystem.
    Swamp,
    ...more values...
}
```

**Expected behavior**
Something like this. Where the text `[swamp](https://example.com/Swamp)` is replaced with a link.
![Screenshot from 2020-05-06 18-27-48](https://user-images.githubusercontent.com/2608639/81204328-61c94400-8fc9-11ea-9f62-67529c818949.png)

**Additional context**
```
juniper = "0.14.2"
juniper_rocket = "0.5.2"
rocket = "0.4.4"
```

**Comment by LegNeato** [comment]
Is this with master or the latest crates.io release?

**Comment by LegNeato** [comment]
I'm not sure this is a bug. It appears GraphiQL supports markdown and the playground does not. We could possibly convert to html bit it is not clear that is desired in all cases

**Comment by LegNeato** [comment]
Looks like it is a playground issue: https://github.com/prisma-labs/graphql-playground/issues/1081
