### ISSUE TITLE
children with aliases are not visitable from LookAheadSelection

### ISSUE THREAD

**Issue by bumblepie** [graphql-rust/juniper#660]
**Describe the bug**
When attempting to enumerate all the children of a LookAheadSelection, fields with an alias are not visitable. This is because to access child selections, you must call the method `selection.child_names()` which gives the alias if one exists, or the field name if it doesn't:
```
fn child_names(&self) -> Vec<&str> {
    self.children
        .iter()
        .map(|c| c.alias.unwrap_or(c.name))
        .collect()
}
```
You can then access the child selection via `selection.select_child(name)` - however, this only checks for equality of the child selection's name, not the alias:
```
fn select_child(&self, name: &str) -> Option<&Self> {
    self.children.iter().find(|c| c.inner.name == name)
}
```
What this means is that a child selection with an alias is essentially unvisitable, as the children Vec is a private field of the LookAheadSelection struct, and you cannot see what the aliased field's name is for access via `select_child`.

**To Reproduce**
Steps to reproduce the behavior (from the tests introduced in the [PR for children visitability](https://github.com/graphql-rust/juniper/pull/431/commits/ed5c17d1d3c1b121c4b72058eca6526a77ecf2f0)):
```
#[test]
fn check_alias_visitability() {
    let docs = parse_document_source::<DefaultScalarValue>(
        "
query Hero {
    hero(episode: EMPIRE) {
        my_name: name
        name
        friends {
            name
        }
    }
}
        ",
    )
    .unwrap();
    let fragments = extract_fragments(&docs);
     if let crate::ast::Definition::Operation(ref op) = docs[0] {
        let vars = Variables::default();
        let look_ahead = LookAheadSelection::build_from_selection(
            &op.item.selection_set[0],
            &vars,
            &fragments,
        )
        .unwrap();

        look_ahead
            .child_names()
            .iter()
            .for_each(|child_name| assert!(look_ahead.select_child(child_name).is_some()));
    }
}
```

**Expected behavior**
I would expect to be able to enumerate the children of anything that implements LookAheadMethods (this issue also exists for the implementation of ConcreteLookAheadSelection).

**Solution ideas**
In terms of a solution, I don't believe that changing `selection.child_names()` to only return field names (and not aliases) is sufficient - you'd still not be able to select aliases, as multiple fields could have the same name and only the first one would be returned under the current implementation.

I think changing the selection.select_child(name) method to use the same logic would work:
```
fn select_child(&self, name: &str) -> Option<&Self> {
    self.children
        .iter()
        .find(|c| c.inner.alias.unwrap_or(c.inner.name) == name)
        .map(|s| &s.inner)
}
```
However, I think this might break backwards compatibility for anything already relying on the old behavior, so that's important to be aware of.

Alternatively, is there any reason we couldn't expose the children field directly or have a method providing an iterator over the children? It seems like the cleanest solution here.

**Comment by LegNeato** [comment]
Thanks for the report! This looks like an oversight. I like the idea of providing an iterator over the children. I'm also fine breaking backward compatibility if we need to as master already has a lot of breakage.
