### ISSUE TITLE
Could not find `object` in juniper.

### ISSUE THREAD

**Issue by teymour-aldridge** [graphql-rust/juniper#668]
**Describe the bug**
The documentation states that the `graphql_object` macro is deprecated and the `object` proc macro should be used instead. The `object` macro is not exported from `juniper`.

**To Reproduce**
1. Attempt to use `juniper::object` on an `impl` for a struct.

**Expected behavior**
The procedural macro to run and produce an output.

**Additional context**
Because the object macro exists in `juniper_codegen` I think this is just a case of [exporting it from juniper](https://github.com/graphql-rust/juniper/blob/master/juniper/src/lib.rs#L117). I'd be happy to submit a PR doing this.

**Comment by LegNeato** [comment]
Hello! The doc is actually wrong, the name of the proc macro is `graphql_object`. Would love a PR to fix.

**Comment by teymour-aldridge** [comment]
That’s good to know! I was just a bit confused because there is an `object` proc macro in `juniper_codegen` crate.
I’ll submit a PR.
https://docs.rs/juniper_codegen/0.14.2/juniper_codegen/attr.object.html

**Comment by nicemaker** [comment]
I am a little confused what to use now ...
for me `[juniper:object]` shows up, if try `graphql_object` it doesn't find it in scope.
I also can't use await in my query, it complains with `await is only allowed inside async`, but my resolver is eclared as async. Am I missing something? Last one might be a different issue but I am not even sure if I use right macro now.

```
#[juniper::object(
    Context = Context,
)]
impl QueryRoot {
    fn api_version() -> &'static str {
        "0.1"
    }

    async fn skills(context: &Context, id: String) -> FieldResult<Vec<Skill>> {
        let skills = storage::skills::read().await;
        return Ok(skills);
    }

```}

**Comment by LegNeato** [comment]
On the latest crates.io release async is not supported...you need to use master (and `juniper:: graphql_object`). Hope that helps!

**Comment by nicemaker** [comment]
Thanks that helped indeed! So easy!
