### ISSUE TITLE
the trait `juniper::types::base::GraphQLType<__S>` is not implemented for `i64`

### ISSUE THREAD

**Issue by bugproof** [graphql-rust/juniper#671]
How to use 64bit ints with #[derive(juniper::GraphQLObject)] ? E.g. I have IDs represented as `u64`

**Comment by tyranron** [comment]
@bugproof you should roll out a [custom GraphQL scalar](https://graphql-rust.github.io/juniper/master/types/scalars.html) in your schema for that. GraphQL spec [doesn't define any built-in scalars for `i64`/`u64` by default](https://spec.graphql.org/June2018/#sec-Int).

**Comment by bugproof** [comment]
https://github.com/graphql/graphql-spec/issues/73
