### ISSUE TITLE
Docs link for juniper_subscriptions is dead

### ISSUE THREAD

**Issue by Zedjones** [graphql-rust/juniper#672]
**Describe the bug**
The API documentation links listed on [this page](https://github.com/graphql-rust/juniper/blob/master/juniper_subscriptions/README.md) are dead.

Specifically, [this page](https://docs.rs/juniper_subscriptions) is linked.

**To Reproduce**
- Go the the provided page.
- Click "API Documentation" link.
- Notice that there are no docs.

**Expected behavior**
Click the link and be provided documentation.

**Comment by Nocturem** [comment]
is there anywhere else this documentation is/was being hosted 
looking around for as much info as I can get on subscriptions and the Juniper implementation of them

**Comment by LegNeato** [comment]
https://graphql-rust.github.io/juniper/master/advanced/subscriptions.html

You can also clone the repo and use `cargo doc` to see the embedded / API docs.

**Comment by LegNeato** [comment]
These links now work.
