### ISSUE TITLE
Ability to create GraphQLRequest manually (or expose GraphQLBatchRequest to allow manual construction)

### ISSUE THREAD

**Issue by thomjs** [graphql-rust/juniper#673]
The last few days I've been trying to implement a Data Guard to authorize signed requests using ECDSA, and everything worked great until I ported it over to the GraphQL project. My main issue is that I need to implement `FromData` or `FromDataSimple` for `GraphQLRequest`. I've looked at two main ways of doing this, and one works for `URI` queries but not for `POST` data. I'll show an example, for `URI` queries, I can do something like this:

```
pub struct SignedRequest(pub juniper_rocket::GraphQLRequest);
impl FromDataSimple for SignedRequest {
    type Error = SignError;

    fn from_data(request: &Request, data: Data) -> Outcome<Self, SignError> {
        // Parse Request Data
        let mut query = String::new();
        if let Err(e) = data.open().take(SIGNATURE_LIMIT).read_to_string(&mut query) {
            return Failure((Status::InternalServerError, SignError::InvalidSignature));
        }
        let signature = request.headers().get("Signature").collect::<String>();
        let public_key = request.headers().get("X-PUBLIC-KEY").collect::<String>();

        if verify_signature(&query, &signature, &public_key) {
            let mut items = FormItems::from(&*query);
            let graphql_req = juniper_rocket::GraphQLRequest::from_form(&mut items, false);
            return Success(SignedRequest(graphql_req.expect("Invalid form data.")));
        }
        // Invalid signature in request
        Failure((Status::UnprocessableEntity, SignError::InvalidSignature))
    }
}
```

This works, because I can construct `FormItems` from the query string, and use `juniper_rocket::GraphQLRequest::from_form` to create the GraphQLRequest no problems.

However, I can't do the same thing with `from_data` when receiving the query as `POST` data, because the following line causes `data` to be owned, and there isn't a `clone` or similar method to allow me to consume `data` twice (this would be my other solution to the `rocket` team, if we could `clone()` the `data` struct):

```
//                        open method takes ownership
//                          \/
if let Err(e) = data.open().take(SIGNATURE_LIMIT).read_to_string(&mut query) {
    return Failure((Status::InternalServerError, SignError::InvalidSignature));
}
```

Which means that the following line won't compile because `data` is now owned by `query`:

```
let graphql_req = juniper_rocket::GraphQLRequest::from_data(data);                          
return Success(SignedRequest(graphql_req.expect("Invalid data.")));
```

**Describe the solution you'd like**
Ideally, I'd like a way to construct a `juniper_rocket::GraphQLRequest` the same way you do internally:

```
GraphQLRequest(GraphQLBatchRequest::Single(http::GraphQLRequest::new(
            query,
            None,
            Some(variables),
)));
```

Which would ideally be exposed by a `GraphQLRequest::new(query, variables)` or similar method, the same way it is exposed by `juniper::http::GraphQLRequest::new` method, but a workaround would be to expose `GraphQLBatchRequest` enum as public.

However, please note I've only been learning juniper for a few weeks and I may completely have the wrong end of the stick, in which case it would be very beneficial to me to hear how others may implement a data guard that needs to return a GraphQLRequest, as I couldn't find any resources to help in this process online.

Thanks.

**Comment by flexabyte** [comment]
Hey,

This is an interesting problem, but I think you should still be able to use `let graphql_req = juniper_rocket::GraphQLRequest::from_data(data);` if you ensure to use `peek()` instead of `open()` on the `rocket::data::Data` instance. See the documentation [here in Rocket source](https://github.com/SergioBenitez/Rocket/blob/63a4ae048540a6232c3c7c186e9d027081940382/core/lib/src/data/data.rs#L56): **Peek enables partially or fully reading from a `Data` object without consuming the `Data` object.**

Hopefully this solves your problem of ownership.

**Comment by thomjs** [comment]
Wow this shows how little I read the rocket documentation. Just what I was looking for, thanks! This can be closed now. `from_data` works as I'd hoped.
