### ISSUE TITLE
Better example for rocket

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#68]
The rocket example is very bare bones.

We should have a more complete example that shows a mutation and context.

**Comment by mhallin** [comment]
I created a small example repository here: https://github.com/mhallin/juniper-example-todo-backend, which uses Iron instead of Rocket. It should of course be extended, but it's a start at least. Maybe we could add Rocket support to that repo?

**Comment by ELD** [comment]
I created an example based off of @mhallin's Iron app. I hit a few pinpoints and will document them more thoroughly in the future, but overall it was a worthwhile experience.

Link to the repo: https://github.com/ELD/rocket-juniper-example

**Comment by WillSquire** [comment]
I've also created an example using the above repos as guidance (these were very helpful to use alongside the docs). It's minimal, so doesn't include database logic or an ORM, and makes use of the `GraphQLObject` and `GraphQLInputObject` derives. Hope this helps people: https://github.com/WillSquire/graphql-rust

**Comment by MonsieurMan** [comment]
Hello there ! I'm building an app with juniper_rocket, mongodb, and yew for the front-end. It's going to be open source once ready anyway so I could definitely use it while it's still relatively simple to complete the documentation and example.

Just tell me if it's actually useful and I'll begin working on it. :slightly_smiling_face:

**Comment by LegNeato** [comment]
Closing unless someone wants to put up a PR.
