### ISSUE TITLE
Benchmarking Juniper

### ISSUE THREAD

**Issue by divy-work** [graphql-rust/juniper#690]
Hey there! I'm trying to do benchmarks for a Juniper GraphQLAPI with `wrk` and here's my wrk script:
```lua
wrk.method = "POST"
wrk.headers["Content-Type"] = "application/json"
wrk.headers["Accept"] = "application/json"
wrk.rawData = '{"query":"{\n  package(name: \"sass\") {\n    name,\n    owner,\n    normalizedName,\n    latestVersion,\n    latestStableVersion,\n    packageUploadNames\n  }\n}","variables":{}}'
```
But the API is returning a 400 bad request which is weird because it works for other frameworks like Apollo.

Here's my wrk command (not a wrk expert): 
```sh
wrk -t12 -c400 -d10s --timeout 10s --script=user.lua --latency http://127.0.0.1:8080/graphql
```
Thanks. I'm loving Juniper so far :smile:

**Comment by LegNeato** [comment]
Hello! I might need a bit more info to debug this. Can you try without the `query` bit? Does the same query + schema work calling `execute()` / without going through a http integration? What http integration are you using? Are you on master or the crates.io release?

Can you share your code or schema so I can repro?

Thanks for the kind words and for trying Juniper! I'm sure we'll get this sorted.

**Comment by divy-work** [comment]
@LegNeato Thanks for your reply. I'm using actix as my Http service with tokio-postgres.
I can confirm that the same query works when I call it using graphiql and Postman graphql.

Here is the complete code:
https://github.com/nestdotland/api/tree/chores/benchmarks
Tell me if you need anything else.

**Comment by LegNeato** [comment]
Ah, I see what is happening. You need to check the `GraphQLResponse` and map it to an actix response. Something like:

```rust
        res = data.clone().execute(
            &st.st,
            &context::GraphQLContext {
                pool: Arc::clone(&st.pool),
            },
        );
        if res.is_ok() {
            Ok(HttpResponse::Ok()
            .content_type("application/json")
            .body(serde_json::to_string(&res).unwrap()))
        } else {
            Ok(HttpResponse::InternalServerError()
            .content_type("application/json")
            .body(serde_json::to_string(&res).unwrap()))
        }
```

I'd send a patch but don't know too much about Actix and was hitting some `ResponseError` sizing issues.

Note you may want to switch to `master` as it might make your life easier:

* Supports async/await.
* Supports multiple POSTs and and the `graphql` content type.
* Has built in support for actix using `juniper_actix`.
* Has built in support for getting the graphql schema in the GraphQL Schema Format.

Main issue with master is it does not yet support interfaces but you do not appear to be using them.

**Comment by divy-work** [comment]
Thank you! This is for returning the error back right? 
I'll check it out, but I still don't understand how valid POST requests are not working (giving 400). Thank you for your time.

**Comment by LegNeato** [comment]
Hmmm, not sure. Similar to what I posted above is used for the actix async integration on `master`:

https://github.com/graphql-rust/juniper/blob/master/juniper_actix/src/lib.rs#L140

(example usage at https://github.com/graphql-rust/juniper/blob/master/juniper_actix/examples/actix_server.rs)

You need to map from juniper's concept of a http failure to Actix's concrete view of the world...which doesn't look to be happening in your code from what I can see. FWIW, this is all `juniper_actix` and the other http server integrations fo...add helpers that do it for you.

**Comment by divy-work** [comment]
Sure. I'll swtich to master and come back to you.

**Comment by LegNeato** [comment]
Be sure to check the https://github.com/graphql-rust/juniper/blob/master/juniper/CHANGELOG.md for breaking changes, as there are some. Let us know if it doesn't work or you need help!

**Comment by divy-work** [comment]
@LegNeato So I have migrated to master branch of juniper and also have used some code from juniper_actix in my code. Now, I face the only error .i.e:

```rust
error[E0271]: type mismatch resolving `<juniper::types::scalars::EmptySubscription as juniper::types::base::GraphQLValue>::Context == context::GraphQLContext`
  --> src/main.rs:37:20
   |
37 |     let res = data.execute(
   |                    ^^^^^^^ expected `()`, found struct `context::GraphQLContext`
```

As far as I understood, this is because the I have no Subscription Schema? How can I create an Empty Subscription with the Context. Thank you!

**Comment by divy-work** [comment]
I fixed the issue by creating a dummy Subscription. But still POST requests are not working with CURL or wrk.

**Comment by LegNeato** [comment]
I put up https://github.com/nestdotland/api/pull/11. Haven't tested it but it compiles.

**Comment by LegNeato** [comment]
Using the above change, this `curl` command worked for me:

`curl -d '{"query":"{\n  package(name: \"sass\") {\n    name,\n    owner,\n    normalizedName,\n    latestVersion,\n    latestStableVersion,\n    packageUploadNames\n  }\n}","variables":{}}' http://127.0.0.1:8080/graphql -v -H 'Content-Type: application/json'`

**Comment by divy-work** [comment]
@LegNeato Yes! It worked for me too! Thank you so much for your time and effort.

**Comment by LegNeato** [comment]
@divy-work when benchmarking make sure you compile in release mode and use LTO.
