### ISSUE TITLE
Move rocket and iron integrations to separate crates

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#70]
Since breaking changes in iron/rocket can force a major version bump to juniper, which is the case right now with the Rocket update (https://github.com/mhallin/juniper/pull/67), we'd like to pull out the integrations into separate crates.

This also makes the testing setup a bit easier to handle.

Tasks

- [x] Rocket
  - [x] Move code to `juniper_rocket` crate
  - [x] Move example to new crate
  - [x] Update travis/appveyor specs
  - [x] Documentation
  - [x] Publish crate

- [x] Iron
  - [x] Move code to `juniper_iron` crate
  - [x] Move example to new crate
  - [x] Update travis/appveyor specs
  - [x] Documentation
  - [x] Publish crate

**Comment by theduke** [comment]
All that is left here is writing a guide about rocket for the book.

**Comment by shuaizhiwen** [comment]
I have been waiting for a better example of the rocket, so I really put juniper used in my project, I now use rocker + juniper + Mongo to build my blog, but it seems that juniper and Mongo are not very good in my project, and look forward to a better Rocket + Mongo the example
