### ISSUE TITLE
Subscriptions, Warp and stream of events

### ISSUE THREAD

**Issue by dodomorandi** [graphql-rust/juniper#718]
I am trying to understand how a non-trivial subscription system should be handled.

The idea is pretty simple: multiple client can perform a subscription, and whenever a client performs a `mutation`, all subscribed clients should receive a message.

Initially, I just used a `tokio::sync::broadcast::channel`: whenever the subscription function is called (through graphql), a new tokio receiver is obtained using `Sender::subscribe` (the sender is stored in the  `Context`), then the receiver is transformed into a stream and, after some chaining, it is `Box::pin`ned and returned.

Unfortunately this approach does not work as expected, multiple repeated messages are sent to the same stream. It looks like the number of "copies" are equal to the number of subscriptions.

Could you help me a bit to understand where the problem could be? I started thinking that I should use the `Coordinator` and/or the `Connector`, but I am not sure how. Maybe a slightly more complex example in the `warp_subscription` could help as well.

Thank you in advance!

**Comment by LegNeato** [comment]
@nWacky wrote the current implementation

**Comment by LegNeato** [comment]
@ccbrown just revamped some of this stuff and may be of help. You will likely want to check out and update to the latest master.

**Comment by ccbrown** [comment]
Check out this gist: https://gist.github.com/ccbrown/d2a3a26093c749e31338a944721b2e60

It's a modification of the "warp_subscriptions" example that I believe does what you're describing: When someone performs the "send" mutation, all subscribers get the message exactly once:

<img width="1792" alt="Screen Shot 2020-07-29 at 5 23 49 AM" src="https://user-images.githubusercontent.com/1731074/88784868-86633100-d15e-11ea-994e-4722591e2542.png">

**Comment by dodomorandi** [comment]
Thank you so much @LegNeato, @ccbrown and everyone else! I just tried to follow the new way of handling the subscription showed in the example, and it looks like the messages are perfect now! Indeed, the code I have is pretty similar to the gist provided by @ccbrown (tiny difference: I am using directly the `tokio::Sender` instead of an `Arc` because, AFAIK, `Sender` should be already reference counted).

I am still struggling a bit with the correct behavior because the toy I am implementing is using [ReasonML](https://reasonml.org/), [ReasonReact](https://reasonml.github.io/reason-react/) and [reason-apollo](https://github.com/apollographql/reason-apollo), and I am pretty new with ReasonML and its ecosystem. I am quite convinced that, until WASM reaches a zero overhead when interacting with JS and DOM, ReasonML could be one of the best solution when working with web frontend. I wanted to share this information because, maybe, you can find it interesting as well.

Thank you again for all your efforts, your work is astonishing! :heart:
