### ISSUE TITLE
Registry should reject types with invalid names

### ISSUE THREAD

**Issue by mhallin** [graphql-rust/juniper#72]
While the spec doesn't explicitly specify what a valid name of a type is, it's reasonable to assume that they should be valid GraphQL name tokens, i.e. `/[_A-Za-z][_0-9A-Za-z]*/` since they're written as identifiers in e.g. fragment type conditions. This seems to be in line with what the [reference implementation](https://github.com/graphql/graphql-js/blob/7ddd8dd44cb7f8a3a9f7a760d5ab76ac91802931/src/utilities/assertValidName.js) does. This causes tools like GraphiQL to stop working if an invalid type name is exposed.

Since Juniper's macros use `stringify!`, invalid names can be generated by using e.g. multiple modules:

```rust
// Generates a GraphQL type named "auth::User"
graphql_object!(auth::User: () |&self| {
});
```

It's probably not possible to do this validation check at compile time, but the registry could probably panic on invalid names.

**Comment by srijs** [comment]
I'd be happy to tackle this one!

**Comment by theduke** [comment]
@srijs go for it!
