### ISSUE TITLE
Subscription messages contain both `data` and `errors`

### ISSUE THREAD

**Issue by mihai-dinculescu** [graphql-rust/juniper#729]
**Describe the bug**
Successful messages contain an empty array `errors` property, while error messages contain a null `data` property.

```
{
  "data": {
    "users": {
      "name": "stream user"
    }
  },
  "errors": []
}
```

```
{
  "data": {
    "users": null
  },
  "errors": [
    {
      "message": "some field error from handler",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ],
      "extensions": "some additional string"
    }
  ]
}
```

**To Reproduce**
Run the warp_subscriptions example

**Expected behavior**
Succesful messages should contain only `data`. Error messages should contain only `errors`.

**Additional context**
Introduced by https://github.com/graphql-rust/juniper/pull/721

**Comment by ccbrown** [comment]
This isn't a bug. The result of executing a GraphQL operation is not binary "success" or "error". You can have data present _and_ have errors. In fact, the spec requires that the `data` key is always present if execution occurs (as opposed to an error happening during parsing or validation, in which case a different message type is sent back altogether):

It probably makes sense to omit the empty errors array in your first example, and just emit this:

```
{
  "data": {
    "users": {
      "name": "stream user"
    }
  }
}
```

But your second example is correct, and removing the `data` key would violate the spec.

**Comment by ccbrown** [comment]
PR to omit empty errors from serialization: https://github.com/graphql-rust/juniper/pull/732

The spec does say:

> If no errors were encountered during the requested operation, the errors entry should not be present in the result.

So that's definitely worth changing.

**Comment by mihai-dinculescu** [comment]
> 
> 
> PR to omit empty errors from serialization: #732
> 
> The spec does say:
> 
> > If no errors were encountered during the requested operation, the errors entry should not be present in the result.
> 
> It says "should" and not "must", so clients should be fine either way, but it's definitely worth changing.

That looks like an inconsistency in the spec. Just above that, under [Response Format](http://spec.graphql.org/June2018/#sec-Response-Format), the spec takes a more prescriptive approach:

> If the operation encountered any errors, the response map must contain an entry with key errors. The value of this entry is described in the “Errors” section. **If the operation completed without encountering any errors, this entry must not be present.**

> If the operation included execution, the response map must contain an entry with key data. The value of this entry is described in the “Data” section. **If the operation failed before execution, due to a syntax error, missing information, or validation error, this entry must not be present.**

**Comment by mihai-dinculescu** [comment]
> But your second example is correct, and removing the `data` key would violate the spec.

The caveat here is if the operation started executing or not.

[Data spec](http://spec.graphql.org/draft/#sec-Data)
> If an error was encountered before execution begins, the data entry should not be present in the result.

[Response Format spec](http://spec.graphql.org/draft/#sec-Response-Format) is even more prescriptive
> If the operation included execution, the response map must contain an entry with key data. The value of this entry is described in the “Data” section. **If the operation failed before execution, due to a syntax error, missing information, or validation error, this entry must not be present.**

**Comment by ccbrown** [comment]
The message type you're referring to is only used if execution has started. If execution has not started, an entirely different message type is used. That's the difference between the graphql-ws "data" and "error" messages:

https://github.com/graphql-rust/juniper/blob/6788ef20c85fe5fbe8bbd47b4264788c7a6ad77a/juniper_graphql_ws/src/server_message.rs#L109-L123

**Comment by ccbrown** [comment]
Looks like you're right about the success case. That fix has been merged though, so I think we're now 100% spec compliant. Let me know if anything else looks off.

**Comment by mihai-dinculescu** [comment]
> 
> 
> The message type this issue is about is only used if execution has started. If execution has not started, an entirely different message type is used (which does not contain a "data" field). That's the difference between the graphql-ws "data" and "error" messages:
> 
> https://github.com/graphql-rust/juniper/blob/6788ef20c85fe5fbe8bbd47b4264788c7a6ad77a/juniper_graphql_ws/src/server_message.rs#L109-L123

Right! I've got the two confused. All good!
