### ISSUE TITLE
juniper_graphql_ws: serde deserialization error with null values

### ISSUE THREAD

**Issue by lightdiscord** [graphql-rust/juniper#735]
**Describe the bug**
When a client start a subscription it sends a payload which can contain optional variables. Currently, serde `default` field attribute [is being used](https://github.com/graphql-rust/juniper/blob/master/juniper_graphql_ws/src/client_message.rs#L13).
It works if the key is not present or if it is an empty object (`{}`) but yield a serde error if it's `null` (`invalid type: null, expected a map`).

**To Reproduce**
* Launch the `actix_subscriptions` example.
* Launch a client (graphiql for example) and send a payload with `"variables": null` (with graphiql it should send `null` if no variable are specified)

**Expected behavior**
Treating the field as if it were absent.

**Additional context**
This kind of problem was already discussed on [this issue](https://github.com/serde-rs/serde/issues/1098).

**Potential fix**
One way to solve the issue is to use the `default` attribute and `deserialize_with` for example:
```rust
fn unwrap_or_default<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: Deserializer<'de>,
    T: Deserialize<'de> + Default
{
    Ok(Option::<T>::deserialize(deserializer)?.unwrap_or_default())
}

#[derive(Debug, Deserialize, PartialEq)]
#[serde(bound(deserialize = "S: ScalarValue"))]
#[serde(rename_all = "camelCase")]
pub struct StartPayload<S: ScalarValue> {
    pub query: String,
    #[serde(default, deserialize_with = "unwrap_or_default")]
    pub variables: Variables<S>,
    pub operation_name: Option<String>,
}
```

**Comment by LegNeato** [comment]
Sounds great, thank you for the report and the suggested fix! Would you be willing to put a PR up?

**Comment by lightdiscord** [comment]
No problem. I'll open a PR.
