### ISSUE TITLE
Do a crates.io release with Websockets / Subscriptions support

### ISSUE THREAD

**Issue by leebenson** [graphql-rust/juniper#737]
@LegNeato, thanks for the excellent library. We're currently experimenting with it for Vector (https://vector.dev/).

Do you have an expectation for when a release may be cut with 'official' subscriptions / Websockets support, please? Our use-case is primarily streaming data, so this would be perfect.

I saw [your warning](https://github.com/graphql-rust/juniper/issues/669#issuecomment-640105347) about not using master in production, so I was curious if you had an ETA for the next release?

Thanks!

**Comment by LegNeato** [comment]
Awesome, love vector and suggested work should use it 😄 .

Waiting for async interfaces (https://github.com/graphql-rust/juniper/pull/682) to firm up land and then intend to cut a new release.

If @tyranron can't get back to it soon I will likely pick it up.

**Comment by tyranron** [comment]
@LegNeato I haven't recently budget to work on interfaces, but I hope during next month I'll finish them.

There is also some work with refactoring existing macros to have them all consistent and play well with `ScalarValue` defaults, but I think this can be postponed to next major release.

**Comment by leebenson** [comment]
Are either of you available for commercial support?

We're keen on implementing Juniper in Vector ASAP. We're building an awesome new visualization UI for Vector, with Juniper as the GraphQL provider between a deployed instance, and the browser.

Websockets and subscription support is what we're after right now. Beyond that, there may be other issues or bug fixes that may make sense to prioritize.

I appreciate your time on the library and know it's hard to juggle between day jobs. If you have any available bandwidth to get the next release over the line, and tackle other issues ad hoc, we'd love to compensate your time.

Feel free to reach out to me by e-mail if that's more appropriate -- lee@timber.io.

Thanks!

**Comment by tyranron** [comment]
@leebenson just because I think Vector is such an amazing piece of software, I've rescheduled my priorities for you and will finish #682 as soon as I'm capable to.

Regarding the commercial support, thank you very much for this offer, however, I can't accept it due to several reasons (including personal opinions about collaboration in open source).  
I'll help as much as I'll able to, but for no money.

**Comment by leebenson** [comment]
@tyranron, that's an incredible gesture - thanks so much for your support.

I know how difficult it can be juggling multiple priorities. The offer for commercial support remains if it helps remove external pressure, but I certainly respect your position on open source. Thanks so much!

**Comment by kunjee17** [comment]
#682 is in master. It's time to update the world. 😎

**Comment by kunjee17** [comment]
Please pardon my excitement but @LegNeato  and @tyranron if there is no issues left, can we bump the crate version ? 


Diwali is around the corner, lets have some fire crackers, shall we?

**Comment by cfvescovo** [comment]
I definitely need a new release with the great features available on master! Looking forward to using async Juniper in production!

**Comment by danbruder** [comment]
We’ve been using master in prod with async for many months now with no issues 🙂

**Comment by Alfriadox** [comment]
Also looking forward to the release -- need it for the uuid version to go up to 8 and match diesel on one of my projects.

**Comment by LegNeato** [comment]
@tyranron Do you have more work you want to do with interfaces before we cut a release or is this a good release point?

**Comment by tyranron** [comment]
@LegNeato using interfaces recently I've found a little inconvinience I'd like to fix:
```
#[graphql_object]
impl Object {
    #[graphql(name = "fancy")]
    fn fancy_field() -> i32 { 0 }
}

#[graphql_interface]
trait Interface {
    #[graphql_interface(name = "fancy")]  // <-- should be renamed as `#[graphql]`
    fn fancy_field() -> i32 { 0 }
}
```

but except that I think it's OK to roll out a new release.

**Comment by tyranron** [comment]
@LegNeato I'll submit the RP shortly.

**Comment by Alfriadox** [comment]
Anything left holding back this release?

**Comment by LegNeato** [comment]
Crates.io has been updated, sorry for the delay.
