### ISSUE TITLE
juniper_hyper example code doesn't work

### ISSUE THREAD

**Issue by samuela** [graphql-rust/juniper#741]
**Describe the bug**
The juniper_hyper example code doesn't work with the currently published juniper/juniper_hyper crates. Here's a reproduction: https://github.com/samuela/juniper_hyper_broken/.

```
juniper_hyper_broken on  main is 📦 v0.0.0 via 🦀 v1.45.2 on ☁️  us-west-2
❯ cargo build
   Compiling juniper v0.14.2
   Compiling h2 v0.2.6
error[E0463]: can't find crate for `serde_json`
  --> /Users/skainswo/.cargo/registry/src/github.com-1ecc6299db9ec823/juniper-0.14.2/src/lib.rs:98:1
   |
98 | extern crate serde_json;
   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `juniper`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**To Reproduce**
Steps to reproduce the behavior: clone the example code and try `cargo check`ing it.

**Expected behavior**
The example code to work.

**Additional context**
I'm running rust stable v1.45.2 on macOS 10.15.4.

**Comment by LegNeato** [comment]
Hello! I have put up a PR to make your example project work:

https://github.com/samuela/juniper_hyper_broken/pull/1

The gist is you need to point at `master` until we do another release.

**Comment by LegNeato** [comment]
Let me know if that doesn't fix it!
