### ISSUE TITLE
Enum interfaces don't seem to work when using juniper::object

### ISSUE THREAD

**Issue by stijnfrishert** [graphql-rust/juniper#744]
I'm building an interface using the enum pattern as [per the book](https://graphql-rust.github.io/juniper/current/types/interfaces.html#enums).

This works when I use `#[derive(juniper::GraphQLObject)]` for my cases. However, as soon as I switch over to using `#[juniper::object(Context = Context)]`, I get a compilation error:

```
the trait bound `graph::Graph: juniper::GraphQLType<S>` is not satisfied
required because of the requirements on the impl of `juniper::GraphQLType<S>` for `&graph::Graph`
```

What's up with that? Does anyone know how to solve this?

Here's my interface implementation:

```
#[derive(juniper::GraphQLObject)]
pub struct Timeline {
    pub id: ID,
    pub name: String,
}

pub struct Graph {
    pub id: ID,
    pub name: String,
}

#[juniper::object(
    Context = Context,
)]
impl Graph {
    fn id(&self) -> &ID {
        &self.id
    }

    fn name(&self) -> &str {
        &self.name
    }
}

pub enum Event {
    Graph(Graph),
    Timeline(Timeline),
}

juniper::graphql_interface!(Event: () where Scalar = <S> |&self| {
    field id() -> &str {
        match *self {
            Event::Graph(Graph { ref id, .. }) |
            Event::Timeline(Timeline { ref id, .. }) => id,
        }
    }

    field name() -> &str {
        match *self {
            Event::Graph(Graph { ref name, .. }) |
            Event::Timeline(Timeline { ref name, .. }) => name,
        }
    }

    instance_resolvers: |_| {
        &Graph => match *self { Event::Graph(ref g) => Some(g), _ => None },
        &Timeline => match *self { Event::Timeline(ref t) => Some(t), _ => None },
    }
});

```

**Comment by LegNeato** [comment]
Apologies, interfaces are broken in master until https://github.com/graphql-rust/juniper/pull/682 lands.

**Comment by stijnfrishert** [comment]
But I’m using 0.14.2, not master. Is it broken there too? @LegNeato

**Comment by tyranron** [comment]
@stijnfrishert well, that's the №1 "wut?"-problem in Juniper with deriving macros.

The problem is that `#[juniper::object()]` macro generates code which is not generic over `S: ScalarValue`, but just uses `DefaultScalarValue`.  
As the result, your `juniper::graphql_interface!` implementation cannot be generic over `S: ScalarValue` too.

We're going to fix this soon before the next release.

**Comment by stijnfrishert** [comment]
@tyranron, thanks for the explanation, that makes sense.

So if this is broken in 0.14.2 as well, is there a work-around?
Use the old `juniper::graphql_object` macro?
Use an even older version of Juniper?

Hope you don't mind the questions, but I'd like to continue development and this is a bottleneck now :)

**Comment by tyranron** [comment]
@stijnfrishert just try not implement GraphQL interface generically over `S: ScalarValue`.

Instead:
```rust
juniper::graphql_interface!(Event: () where Scalar = <S> |&self| {
```

Try:
```rust
juniper::graphql_interface!(Event: () |&self| {
```
or
```rust
juniper::graphql_interface!(Event: () where Scalar = DefaultScalarValue |&self| {
```

**Comment by stijnfrishert** [comment]
Ah, right. That works! Thanks 👍 

Was running into issues trying to do that on master, but it works on 0.14.2.
