### ISSUE TITLE
Get context in interface field resolvers

### ISSUE THREAD

**Issue by stijnfrishert** [graphql-rust/juniper#748]
One of my interface's fields resolves to another type. I'd like to store that field as an `ID` and retrieve it from my context upon resolution. Whenever I try this, I get an error saying the trait bound `FromInputValue` is not satisfied for my context.

```
struct Event {
    parent: Option<ID>,
}

juniper::graphql_interface!(Event: Context |&self| {
    field parent(context: &Context) -> Option<Event> { ... }

    // ...
}
```

This leads me to believe this is simply not supported in the current 0.14.2 release. Is this something I should also wait for in the new interface release that's coming up, or am I missing something?

**Comment by LegNeato** [comment]
Hmm, I think something similar should work but haven't looked at release version in a long time. After https://github.com/graphql-rust/juniper/pull/682 lands this should be fixed on master.

**Comment by davidpdrsn** [comment]
I don't exactly remember but I don't think you should specify the context argument on the field itself:

```rust
juniper::graphql_interface!(Event: Context |&self| {
    field parent() -> Option<Event> { ... }

    // ...
}
```

That is at least what I do in juniper-from-schema [here](https://github.com/davidpdrsn/juniper-from-schema/blob/master/juniper-from-schema-code-gen/src/ast_pass/code_gen_pass.rs#L285) and [here](https://github.com/davidpdrsn/juniper-from-schema/blob/master/juniper-from-schema-code-gen/src/ast_pass/code_gen_pass.rs#L297).

**Comment by stijnfrishert** [comment]
Oh nice, thanks, @davidpdrsn! I'll give that a try :)

**Comment by tyranron** [comment]
This is now possible in `master`. See [description in Book](https://graphql-rust.github.io/juniper/master/types/interfaces.html#custom-context).
