### ISSUE TITLE
Expose the fields of GraphQLRequest

### ISSUE THREAD

**Issue by sessionboy** [graphql-rust/juniper#750]
**Describe the solution you'd like**

My database is [dgraph](https://github.com/dgraph-io/dgraph), which is a native graphql database.
I need to query the data of `dgraph graphql database` in the juniper server. This is not as easy as restful.

So i want to get `query`, `operation_name` and `variables` because I want to request data from `dgraph graphql database` based on them. But now they are private.

In addition, how can I obtain resolveInfo? Maybe I need it.

**Comment by LegNeato** [comment]
Hmm, I thought operation name was public, perhaps it got dropped:

https://github.com/graphql-rust/juniper/pull/265/commits

**Comment by sessionboy** [comment]
@LegNeato  I checked the source code, they are private and I cannot get them. Can you update and publish it ?

**Comment by mkpankov** [comment]
I think I need this too. Say user wants a subfield `{ details { foo, bar } }`. I need a different query for PostgreSQL to fetch details. Right now I have a query argument `detail: bool`, but I really should determine if user asked for details and change logic automatically.
