### ISSUE TITLE
Juniper/Rocket/MySQL integration

### ISSUE THREAD

**Issue by bostontrader** [graphql-rust/juniper#752]
I'm having a difficult time getting Rust, Juniper/GraphQL, and MySQL to all work together.  This problem is compounded by the fact that each piece is working just fine, it's the integration that is a problem.  So who shall I beg insight from?

As Rocketeers know, Rocket has a method for connecting to MySQL. It involves creating an object, in my example I'll call it MyRocketSQLConn, and feeding said object to any route handlers that need a connection to MySQL.  This part works just fine.

As Junipeters know, Juniper defines a query, schema, and context that are also fed to any Rocket route handlers that need them.  The route handler will invoke query.execute(schema, context) to do its thing. This part also works just fine.

I can successfully deliver MyRocketSQLConn, Query, Schema, and Context into a route handler, but get stuck shortly thereafter.

In the examples that I've seen Context has been used to hold a toy database but it looks like an obvious place to inject MyRocketSQLConn into the Juniper works. Unfortunately this is trouble.  The basic reason for this is that the context is [immutable for reasons of thread safety](https://github.com/graphql-rust/juniper/issues/5) and I would need to use inner mutability to inject MyRocketSQLConn into this.

I have come tantalizingly close to a solution by adding a field to the Juniper Context object, which I call JunDatabase:

```
pub struct JunDatabase {
    pub conn: Arc<Mutex<Option<MyRocketSQLConn>>>,
}
```

The Arc and Mutex deal with the thread safety issues.  I need Option because I must create the Juniper Context before I have instantiated MyRocketSQLConn.

So the route handler that I have is:

```
#[rocket::post("/graphql", data = "<request>")]
fn post_graphql_handler(
    context: State<M::JunDatabase>,
    request: juniper_rocket::GraphQLRequest,
    schema: State<Schema>,
    mut conn: MyRocketSQLConn
) -> juniper_rocket::GraphQLResponse {

    {
        let m = &*context.conn;
        let mut m1 = m.lock().unwrap();
        *m1 = Some(conn);
    }

    request.execute(&schema, &context)

}
```

This part works just fine and execution will eventually get to:

```
fn helloJuniper(database: &JunDatabase) -> i32 {
    let m1 = &*database.conn;
    let m2 = m1.lock().unwrap().as_ref().unwrap();

    ...
}
```

At this point the code compiles and upon execution m2 is a &MyRocketSQLConn.  This is where I'm stumped.

The basic issue is that, depending upon which of the 99,000 subsequent variations I try, the error messages generally complain about moves, borrows, mutability, and lifetimes.  I have a general understanding of these issues individually, but undoubtedly have more to learn about these topics.

Given one particular guess yields:
```
let m3 = (*m2).prep_exec(...);
^^^^^ `m2` is a `&` reference, so the data it refers to cannot be borrowed as mutable

```
I'll spare you the loooong list of guesses that I've made about this as I thrash hopelessly hoping that the infinite monkey battalion can succeed in the absence of divine insight.  If I'm missing a magic * somewhere, I'd be happy to have my nose rubbed in that fact.  But I'd **really** like to hear some ideas for a general purpose approach to dealing with this issue.

Thank you.

**Comment by LegNeato** [comment]
Is your WIP code open source? Happy to take a look.

**Comment by bostontrader** [comment]
Howdy @LegNeato ,

Thanks for the offer.  The code is indeed open source and you can find it [here](https://github.com/bostontrader/bookwerx-core-rust)

The route handler named post_graphql_handler can be found starting at line 257 in src/bin/server.rs

The function that I'm trying to feed the MySQL connection into is named currencies and can be found starting at line 18 in src/schema.rs.  This is a method of the Query type that Juniper user and Juniper is responsible for invoking this function.

The MySQL connection object is of type MyRocketSQLConn, defined in src/db.rs

The code as-is will compile and it will deliver a MyRocketSQLConn into the currencies function, but subsequent usage is hampered by whatever mysterious issues are presently stumping me.

My first choice is to figure out how to get a mut MyRocketSQLConn into said currencies function.

My secondary choice is to figure out how to retrieve a suitable connection object from MyRocketSQLConn using a function call to it.  I have an impl block for MyRocketSQLConn with a commented out attempt at doing so.

Hope you can find the "doh!" issue that I'm missing.  Thanks again for the help.

**Comment by bostontrader** [comment]
P.S. When the server is running...
`curl -X POST -H "Content-Type: application/json" -d '{"query": "{ currencies }"}' http://localhost:3003/graphql`

**Comment by LegNeato** [comment]
https://github.com/bostontrader/bookwerx-core-rust/pull/1 allows it to compile but don't know if it is the right thing to do for rocket. Let me know if it is still an issue or if that solves it!
