### ISSUE TITLE
juniper_hyper in cartes.io needs to be updated?!

### ISSUE THREAD

**Issue by seunghunee** [graphql-rust/juniper#753]
I'm very very a newbie in rust and juniper.
I've installed juniper_hyper using cargo.
The problem was I get an compile error with this code.
```rust
juniper_hyper::playground("/graphql").await
// Error: the trait bound `impl futures::future::Future: std::future::Future` is not satisfied
// required by `std::future::Future::poll`rustc(E0277)
```

Maybe, I think because this juniper_hyper uses futueres 0.1.29, so it can't use async/await syntax.
[juniper_hyper 0.5.2 in Crates.io has futures^0.1 dependency](https://crates.io/crates/juniper_hyper/0.5.2)
So, juniper_hyper needs to be updated to use futures 0.3^ which can use async/await syntax.

And also, I'm wondering why [Cargo.toml of juniper_hyper 0.5.2](https://github.com/graphql-rust/juniper/blob/master/juniper_hyper/Cargo.toml) has futures 0.3.1 dependency, while juniper_hyper in Crates.io has futures^0.1.

Thank you.

**Comment by LegNeato** [comment]
Hello! Yes, the crates.io release is only compatible with an older hyper unless you use the compat layer of the futures crate. I would suggest using master of `juniper` and `juniper_hyper` until we do another release (soon, see https://github.com/graphql-rust/juniper/issues/737).

For version numbers on master, we only bump when doing a release so what is on master is not what is on crates.io even though the version numbers appear to be the same.
