### ISSUE TITLE
Using Cloud Events with Juniper

### ISSUE THREAD

**Issue by simongottschlag** [graphql-rust/juniper#764]
Hi!

I'm new to Rust and gotten Juniper to work with actix-web. Now I'm trying to use the types from Cloud Events Rust SDK to work with GraphQL without much success.

Now, this may not be a limitation with Juniper and I'm just bad at Rust - but thought it may be worth asking.

Is an external type supposed to be able to work with a Struct for Juniper?

More info about cloud events here: https://github.com/cloudevents/sdk-rust/blob/master/example-projects/actix-web-example/src/main.rs

Thanks!

Edit with more info:

The following works as expected:
```Rust
#[derive(GraphQLObject)]
#[graphql(description = "A simple message with content")]
struct Event {
    id: String,
    content: String,
}
```

If I change it to the following:
```Rust
use cloudevents::Event as CloudEvent;

#[derive(GraphQLObject)]
#[graphql(description = "A simple message with content")]
struct Event {
    id: String,
    content: CloudEvent,
}
```

I get the following error:
```text
error[E0277]: the trait bound `cloudevents::Event: juniper::GraphQLType<__S>` is not satisfied
 --> src/schema.rs:8:10
  |
8 | #[derive(GraphQLObject)]
  |          ^^^^^^^^^^^^^ the trait `juniper::GraphQLType<__S>` is not implemented for `cloudevents::Event`
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `cloudevents::Event: juniper::GraphQLType<__S>` is not satisfied
 --> src/schema.rs:8:10
  |
8 | #[derive(GraphQLObject)]
  |          ^^^^^^^^^^^^^ the trait `juniper::GraphQLType<__S>` is not implemented for `cloudevents::Event`
  |
  = note: required because of the requirements on the impl of `juniper::GraphQLType<__S>` for `&cloudevents::Event`
  = note: required because of the requirements on the impl of `juniper::IntoResolvable<'_, __S, &cloudevents::Event, _>` for `&cloudevents::Event`
  = note: required by `juniper::IntoResolvable::into`
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by davidpdrsn** [comment]
No that isn't possible unfortunately. The `#[derive(GraphQLObject)]` can only implement the required juniper traits for the type its put on. It isn't able to figure out which fields `CloudEvent` has and then make that Juniper compatible as well. That would also be a violation of the [orphan rule](https://doc.rust-lang.org/book/ch10-02-traits.html).

I think in this case you'd have to wrap `cloudevents::Event` in your own struct and then make that juniper compatible.

**Comment by simongottschlag** [comment]
@davidpdrsn thank you! I'll wrap it. 👍
