### ISSUE TITLE
Field type not found on type Mutation

### ISSUE THREAD

**Issue by dwgeneral** [graphql-rust/juniper#766]
I defined a struct which has a `type` field

```rust
#[derive(Debug, Serialize, Deserialize, Clone, juniper::GraphQLObject, Default)]
pub struct A {
    no: i32,
    name: String,
    type: String,
}
```

and the compiler tell me, it can't accept this, so I changed to fix it.

```rust
580 |     type: String,
    |     ^^^^ expected identifier, found keyword
    |
help: you can escape reserved keywords to use them as identifiers
    |
580 |     r#type: String,
    |     ^^^^^^
```

```rust
#[derive(Debug, Serialize, Deserialize, Clone, juniper::GraphQLObject, Default)]
pub struct NewA {
    no: i32,
    name: String,
    r#type: String,
}
```

and the graphiQL is printed well. 

<img width="167" alt="Screen Shot 2020-09-19 at 12 27 08 PM" src="https://user-images.githubusercontent.com/8654993/93659064-09747980-fa74-11ea-9303-d9d500c87849.png">

but when I requested this Object, I got this error 

```rust
thread 'actix-web' panicked at 'Field type not found on type Mutation', src/model/response_models.rs:576:48
```

it looks like the juniper::GraphQLObject doesn't identify this keyword field, and I wanna know the specified reason and the possible solutions.

thx all~

**Comment by LegNeato** [comment]
Which version are you using? Crates.io or master?

**Comment by dwgeneral** [comment]
> Which version are you using? Crates.io or master?

name = "juniper"
version = "0.14.2"
source = "registry+https://github.com/rust-lang/crates.io-index"

**Comment by LegNeato** [comment]
Ah, this should be fixed on master. We are cutting a new release soon!
