### ISSUE TITLE
impl Display for ID

### ISSUE THREAD

**Issue by stijnfrishert** [graphql-rust/juniper#781]
In my `FieldResult` error I very often want to say something like `format!("object with id {} wasn't found", id)`, but `ID` doesn't have `fmt::Display` implemented.

Since `ID` is nothing but a `String` newtype, seems like a valid thing to do, right? Sure, I could use `{:?}`, but implementing Display seems like the right thing to do here.

**Comment by LegNeato** [comment]
Sounds good, happy to take a PR with the change and a test to make sure it does not regress.

**Comment by stijnfrishert** [comment]
At your service!

**Comment by LegNeato** [comment]
Thank you so much!
