### ISSUE TITLE
Ability to produce a graphql schema file for use in other clients

### ISSUE THREAD

**Issue by DusterTheFirst** [graphql-rust/juniper#784]
Basically what the title says. juniper is very good at merging rust and graphql together so strictly, but outside of the server, there is no way to ensure the types match those defined in the server. It would be useful if there was a way to produce a .graphql file with the schema (possibly at build time) so that other clients could verify and type the requests at compile time or runtime.

**Comment by DusterTheFirst** [comment]
You can use the `juniper::introspect` method

**Comment by LegNeato** [comment]
Actually, on master we have been better support:

https://graphql-rust.github.io/juniper/master/schema/schemas_and_mutations.html#converting-a-rust-schema-to-the-a-hrefhttpsgraphqlorglearnschematype-languagegraphql-schema-languagea

**Comment by john-consumable** [comment]
Is it possible to get a json schema like `introspect` provides in a similar fashion (i.e. without setting up an entire context)?  The schema language doesn't quite do everything that the question poses.

**Comment by LegNeato** [comment]
What is missing from the .graphql file that is generated?

**Comment by john-consumable** [comment]
`introspect` gives back the `GraphQLObject` response of from introspection in json form.
