### ISSUE TITLE
Is there any way to control the output of the DateTime scalar?

### ISSUE THREAD

**Issue by siyopao** [graphql-rust/juniper#787]
Hello 👋 I would like to use the DateTime scalar in my service but I need the output with milliseconds and with Z (i.e., I want to use `to_rfc3339_opts(SecondsFormat::Millis, true)` on a `DateTime`). Given this it seems that I cannot use the built-in one, so I am trying to `impl<S> GraphQLScalar for DateTime<Utc>` by myself, but then I get a conflicting implementations error.

At the moment I am wrapping `DateTime<Utc>` in a `MyDateTime(DateTime<Utc>)` then implementing `GraphQLScalar` on that, but it is not the best as it shows up as `MyDateTime` in the schema and then everyone asks me what that is 😆 . Is there anything else I can do? Or perhaps hide the current implementation behind a feature flag?

Thank you! Love using Juniper.

Edit: I do realize that I can use `graphql_scalar(name = "DateTimeUtc")` so it is not really all that bad.

**Comment by tyranron** [comment]
@siyopao 

> At the moment I am wrapping DateTime<Utc> in a MyDateTime(DateTime<Utc>)

This is the right and idiomatic way to go. Each scalar shoud have a stable and concrete value representation. So if you need a different one - you need a different scalar.

> it shows up as MyDateTime in the schema and then everyone asks me what that is 😆 .

>  I do realize that I can use graphql_scalar(name = "DateTimeUtc") so it is not really all that bad.

Or even `Rfc3339DateTime`. The naming is a hard problem 🙃, but not critical one.

> Is there anything else I can do? 

Yep, you can also disable `chrono` feature in `juniper` crate, and then just declare your own `DateTime` as you've done. This way there won't be any name conflicts.

-------------------------------

As this is none an issue, I'm closing this for now. Feel free to reopen if you have further questions or good ideas.

Cheers! 🍻

**Comment by siyopao** [comment]
Thank you @tyranron. I didn't realize that I could disable `chrono` in the `juniper`! That, and hearing that wrapping is the right and idiomatic way to go make me happy. So many things still so new to me.

Anyway, thanks again!
