### ISSUE TITLE
juniper_actix not present on docs.rs

### ISSUE THREAD

**Issue by pbartyik** [graphql-rust/juniper#799]
**Describe the bug**
https://github.com/graphql-rust/juniper/tree/master/juniper_actix readme API reference points to https://docs.rs/juniper_actix

**Expected behavior**
API reference is found on docs.rs

**Comment by davidpdrsn** [comment]
That’s is because that crate isn’t released yet. A release shouldn’t be that far away however https://github.com/graphql-rust/juniper/issues/737

You can use it as a git dependency until then.

**Comment by pbartyik** [comment]
thanks, looking forward to the release!
