### ISSUE TITLE
session with actix-web

### ISSUE THREAD

**Issue by nebnes** [graphql-rust/juniper#828]
Hi, 
I am trying to set a session user in a login mutation. 
But I don't find how access by the context to the session.. 
Is it possible ? 
Thanks

**Comment by tyranron** [comment]
@nebnes you make a `HttpRequest` your `Context`. Or roll out a custom context containg your session.

**Comment by nebnes** [comment]
I try to pass the session in the context but I have this error : 
``` 
`std::rc::Rc<std::cell::RefCell<actix_session::SessionInner>>` cannot be shared between threads safely
```
Code : 
```
 let context = &Context {
        app_data: data.into_inner().clone(),
        pool: pool.get_ref().to_owned(),
        session : session
    };
   

    let res = request.execute(&schema, context).await;
```

The context :  
```
pub struct Context {
    pub app_data: AppState,
    pub pool: PgPool,
    pub session :Session
}

impl juniper::Context for Context {}
```

**Comment by tyranron** [comment]
@nebnes yup [`SendWrapper`](https://docs.rs/send_wrapper/0.5.0/send_wrapper/) will do here, as long a you're using `actix-web` (it doesn't send `Future`s between threads).

See the [example I use](https://github.com/ALLATRA-IT/ephyr/blob/3e48d46f4ccc29d1acffa7b1011d652c45ee2c58/components/restreamer/src/api/graphql/mod.rs#L18-L52).

**Comment by nebnes** [comment]
thanks @tyranron
