### ISSUE TITLE
GraphQL Playground scrolling issue

### ISSUE THREAD

**Issue by NickGeek** [graphql-rust/juniper#830]
**Describe the bug**
Subscriptions in the included GraphQL Playground UI will not be scrollable in Chrome when there are more events than the height of the results pane. This has been fixed in an newer version of the playground: https://github.com/graphql/graphql-playground/issues/1021

**To Reproduce**
1. Include graphql playground
2. Go to the playground and open a subscription
3. When enough events occur to overflow the pane, it isn't scrollable.

**Expected behavior**
The playground should be updated to the latest version without the scrolling bug

**Comment by LegNeato** [comment]
This is released to crates.io, thanks for the report!

**Comment by NickGeek** [comment]
Thanks!

**Comment by NickGeek** [comment]
https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.27/build/static/js/middleware.js seems to 404 for me, so now the entire playground doesn't load.
