### ISSUE TITLE
Minor project related issue. 

### ISSUE THREAD

**Issue by kunjee17** [graphql-rust/juniper#832]
This is not bug. But it would be great if things can be improved on right side of project. 

<img width="350" alt="Screenshot 2020-12-21 at 12 32 23 PM" src="https://user-images.githubusercontent.com/960605/102748897-119cc780-4389-11eb-9d28-9c47217e1693.png">

It is still showing old release from 2017. While are we did have many releases after that. Nothing related to working for the project but it would be great to update setting if there are any.

**Comment by LegNeato** [comment]
Because we push tags I think we can fix this with https://daniellockyer.com/automated-rust-releases/.

**Comment by tyranron** [comment]
Seems to be OK now, and is considered by new release machinery in #1113.
