### ISSUE TITLE
Implement GraphQLType trait for NaiveTime

### ISSUE THREAD

**Issue by EfraimLA** [graphql-rust/juniper#841]
**Is your feature request related to a problem? Please describe.**
Yes, i wanted to use NaiveTime with GraphQLInputObject but i get this error
```
error[E0277]: the trait bound `NaiveTime: GraphQLType<__S>` is not satisfied
 --> src/models/transaction.rs:7:10
  |
7 | #[derive(juniper::GraphQLInputObject, Insertable)]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `GraphQLType<__S>` is not implemented for `NaiveTime`
  |
  = note: required because of the requirements on the impl of `GraphQLType<__S>` for `std::option::Option<NaiveTime>`
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Describe the solution you'd like**
Implement trait for chrono NaiveTime

**Describe alternatives you've considered**

**Additional context**

**Comment by tyranron** [comment]
@EfraimLA this is supported already behind the `scalar-naivetime` feature flag in `juniper`.
