### ISSUE TITLE
Union with Boxed enum variants

### ISSUE THREAD

**Issue by Guara92** [graphql-rust/juniper#845]
Hi, 

Upgrading from 0.14 to 0.15 is giving me some problems with unions that have some boxed enum variant, i.e.:
```
#[derive(GraphQLUnion)]
pub enum GqlResult {
    Ok(Box<Data>),
    Err(Error),
}
```

the docs specifies that container types are supported but the compiler complains about a missing impl of the trait `GraphQLObjectType`  for Box, I'm doing something wrong?

**Comment by tyranron** [comment]
Seems to be a major hole in type-level stuff 🙀

Will try to submit the PR shortly.

**Comment by LegNeato** [comment]
This is released to crates.io. Thanks for the report @Guara92 and for the PR @tyranron !
