### ISSUE TITLE
GraphQLObject with an interface as a field

### ISSUE THREAD

**Issue by Guara92** [graphql-rust/juniper#846]
Hi, 

Upgrading from 0.14 to 0.15 is giving me some problems with `GraphQLObject` that expose an interface in one of the field, such type is not present in any of the examples so I'm trying with something like that:
```
#[derive(GraphQLObject)]
pub enum GqlResult {
    field: Box<dyn MyInterfaceTrait + Sync + Send>,
}
```

with the old version I used enums to rappresent Interfaces, I have migrated to traits but the compiler complains about a missing `GraphQLValue` impl for `dyn MyInterfaceTrait + Sync + Send`, have you any advice to expose this?

**Comment by tyranron** [comment]
@Guara92 please, recheck ["Interfaces" chapter](https://graphql-rust.github.io/juniper/current/types/interfaces.html) of the Book. The info there should help you to understand and fix the problem.

**Comment by Guara92** [comment]
> @Guara92 please, recheck ["Interfaces" chapter](https://graphql-rust.github.io/juniper/current/types/interfaces.html) of the Book. The info there should help you to understand and fix the problem.
> 
> If you're using trait objects for holding interface values (but I don't think you really want that), then the underneath trait object type is rather complex and it would be difficult to write it via raw `dyn` syntax. Instead [macro generates for you a convenient type alias](https://graphql-rust.github.io/juniper/current/types/interfaces.html#trait-object-values) to use.
> 
> But, again, you should prefer using enums. They have less friction.

If I'm not wrong `#[graphql_interface]` is no more applicable to enums

**Comment by tyranron** [comment]
@Guara92 just read the chapter 🙃

It's not applicable to enums, but is applicable to trait implementations of the enum.

**Comment by Guara92** [comment]
@tyranron can you please provide a working example of an object exposing an interface inside? Reading the interface chapters is not clear what you are try to explain here. I'm trying with the `dyn` macro argument but I'm facing strange lifetime errors.

**Comment by tyranron** [comment]
@Guara92 

```rust
use juniper::{graphql_interface, GraphQLObject};

#[graphql_interface(for = [Human, Droid])]
trait Character {
    fn id(&self) -> &str;
}

#[derive(GraphQLObject)]
#[graphql(impl = CharacterValue)]
struct Human {
    id: String,
    home_planet: String,
}
#[graphql_interface]
impl Character for Human {
    fn id(&self) -> &str {
        &self.id
    }
}

#[derive(GraphQLObject)]
#[graphql(impl = CharacterValue)]
struct Droid {
    id: String,
    primary_function: String,
}
#[graphql_interface]
impl Character for Droid {
    fn id(&self) -> &str {
        &self.id
    }
}

#[derive(GraphQLObject)]
struct Plot {
    antagonist: CharacterValue,
    protagonist: CharacterValue,
}
```

**Comment by tyranron** [comment]
See also [integration tests for more examples](https://github.com/graphql-rust/juniper/blob/juniper-0.15.1/integration_tests/juniper_tests/src/codegen/interface_attr.rs).

**Comment by Guara92** [comment]
@tyranron thanks, got it! 

It is possible to add some derive to the autogenerated enum?

**Comment by tyranron** [comment]
@Guara92 no, but you can write `impl fmt::Debug for CharacterValue` manually.
