### ISSUE TITLE
Support for `hyper 0.14` and `tokio 1.0` in `juniper_hyper`

### ISSUE THREAD

**Issue by alvskar** [graphql-rust/juniper#851]
`juniper_hyper` seems tied to the older versions of `hyper` and `tokio` at this time. Are there plans to update it? As I can see it now we'd need to fork it if we want to use the newer tokio (older hyper seems to rely on older tokio).

**Comment by LegNeato** [comment]
https://github.com/graphql-rust/juniper/pull/849

**Comment by Alexx-G** [comment]
@LegNeato @theduke @mhallin Is there a chance you'll have some bandwidth to take a look at this one? There are 2 open PRs ( #888 , #912 ) that close it.
In case you have concerns over stability, it's always possible to have a few "beta" versions to test the upgrade and collect feedback.

**Comment by LegNeato** [comment]
This has now been pushed to crates.io
