### ISSUE TITLE
Can't compile juniper_actix project.

### ISSUE THREAD

**Issue by kunjee17** [graphql-rust/juniper#858]
**Describe the bug**
While I m trying to build project I m getting below error
```rs
 no variant or associated item named `__Nonexhaustive` found for enum `syn::Type` in the current scope
   --> juniper_codegen/src/common/parse/mod.rs:199:18
```

**To Reproduce**
(code example preferred)
Clone the latest code and try `cargo build` in `juniper_actix` folder.

**Expected behavior**
It should build without errors.

**Additional context**
Getting similar issue in project while pointing to git repo in cargo file.

**Comment by kunjee17** [comment]
UPDATE: This commit `4f3939075a9e6c0da8fa138591e657153f27764c` is working for me.

**Comment by trevyn** [comment]
Looks like this might be caused by the `syn` 1.0.60 release, it just broke for me in a daily CI run that ran fine yesterday.

**Comment by kunjee17** [comment]
And it blocked my Custom Scalar implementations. As it is in latest code. I guess I have to disturb Juniper Gods now. 
@trevyn @LegNeato  and others. Need some help over here.

**Comment by kunjee17** [comment]
Thanks @obmarg for quick PR.

**Comment by Binero** [comment]
I already posted this on the PR, but I figured it might be useful here too!

For now this can be worked around by adding an explicit dependency to `syn = "=1.0.59"` in your `Cargo.toml`. 

```toml
[dependencies]
actix-web = "3.3"
juniper = "0.15.2"
syn = "=1.0.59"
```

**Comment by kunjee17** [comment]
@Binero It did the trick. Build is working now. I am keeping the issue open until latest get merged. Hope that is OK.
