### ISSUE TITLE
Feature request: lexicographic schema sort

### ISSUE THREAD

**Issue by mrtnzlml** [graphql-rust/juniper#865]
**Is your feature request related to a problem? Please describe.**

GraphQL reference implementation has support for `lexicographicSortSchema`: https://github.com/graphql/graphql-js/search?q=lexicographicSortSchema. This is useful when printing the schema. Unfortunately, Juniper doesn't seem to support this feature when using `as_schema_language()` (correct me if I am wrong) which sometimes results in a [complicated diff](https://github.com/adeira/universe/commit/2b5c947f399f19cbc6fdc5ec7f78112e1927cbcb#diff-373c155962eb6f2b87cb0138b7775e2d20dea1f9459ff64431945a7dd1b85e10) when doing some changes in the schema - the elements seems to be in a random order (?). It would be nice, if Juniper could sort the schema as well.

**Describe the solution you'd like**
_none_

**Describe alternatives you've considered**

I am not aware of any alternative (apart from _not_ sorting the schema at all).

**Additional context**
_none_

**Comment by LegNeato** [comment]
Great idea! This should actually be the default.

**Comment by AlexPikalov** [comment]
Is there anybody on it or I can try to tackle this one?

**Comment by AlexPikalov** [comment]
`lexicographicSortSchema` is one of many utilities provided by [GraphQL](https://github.com/graphql/graphql-js/tree/a546aca77922beb2fee949ea0ad7c9234f7006fd/src/utilities).
Question: @LegNeato do you plan to add all or some of those utilities from the list (so I would need to make a public mod with this utility and other ones could be added later) or no plans for that and only one thing needed is to implement sorting for `as_schema_language()`?

**Comment by mrtnzlml** [comment]
I'd like to propose to make it ready for further extensions because for example `findBreakingChanges` and `findDangerousChanges` are also super useful.

**Comment by mrtnzlml** [comment]
> Is there anybody on it or I can try to tackle this one?

@AlexPikalov I don't think anyone is working on this issue. Would you like to take care of it? It would be much appreciated! 😊

**Comment by audunhalland** [comment]
I believe this was fixed in #1237 ..?
