### ISSUE TITLE
Implement GraphQLType for chrono::DateTime

### ISSUE THREAD

**Issue by theduke** [graphql-rust/juniper#87]
Since the chrono crate is so popular, it's a pain not to have it implement GraphQLType.

We should optionally implement it behind a feature flag, representing DateTime with a string representation.

**Comment by Mange** [comment]
Might I suggest a float representation (UNIX timestamp with optonally fractional second) instead? It's smaller on the wire and trivial to "parse" (as there is no parsing).

If you are worried about different float representations or limits to 64-bit numbers, the number could be stringified first, letting clients pick a precision. Still easier to parse and validate.

**Comment by LegNeato** [comment]
I noticed you did this for `uuid` as well...is this process scalable? Should there perhaps be a different subcrate with these integrations or instead encourage others to publish crates with GraphQL types for their specific dep rather than `juniper` maintaining them?

**Comment by theduke** [comment]
It is not scalable, but I think we should do it for the most important / most widely used types.

The problem is how trait implementation orphan rules work in Rust.

You can only implement a trait for a type in a crate that defines the trait or defines the type.

So the definitions have to live in the main Juniper crate, which defines the GraphQLType trait.

The only other option is to use wrapper types and implement the trait on those wrappers, which is awkward.

**Comment by theduke** [comment]
@Mange good point, and I personally also always prefer to use floats.

If we implement this, floats should probably be the default.

BUT, the current convention in JS land I seem to see is to mostly use iso8601 strings.

Is there a need for both to be available? (as in both floats and string representations)

**Comment by LegNeato** [comment]
@theduke ah, totally forgot about the trait stuff! Makes sense to me.

**Comment by passcod** [comment]
Chrono's DateTime includes a timezone, so representing it as a number loses information.

**Comment by Mange** [comment]
@passcod that settles it for me.

**Comment by LegNeato** [comment]
@theduke I hope you don't mind that I put up a PR for this. Feel free to discard it if you were thinking of something different.
