### ISSUE TITLE
Undeprecate select_child / has_child helpers? 

### ISSUE THREAD

**Issue by urkle** [graphql-rust/juniper#878]
**Is your feature request related to a problem? Please describe.**
Related to the change made in #662 

In that PR the select_child and has_child methods were deprecated, and the comments suggest using "children()" instead.
However that adds a lot more work to the application as each time I want to lookup children I have to walk the children() nodes myself.  Thus repeating lots of code throughout my application.

**Describe the solution you'd like**
Undeprecate them and/or make children() return a vector reference.

**Describe alternatives you've considered**
I tried creating my own helper methods for select_child & has_child however ran into numerous issues due to the temporary returned from the children() method. (the "native" select_child is accessing the vec directly so it can return a Option(&) without issue).

I also tried using a macro and that also had issues (again related to the temporary).

**Additional context**

**Comment by LegNeato** [comment]
Please submit a PR and we will continue to support them!
