### ISSUE TITLE
Any plan for implementing the new graphql-over-websocket protocol? 

### ISSUE THREAD

**Issue by pranaypratyush** [graphql-rust/juniper#896]
https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md

^Seems really promising.

**Comment by tyranron** [comment]
@pranaypratyush https://docs.rs/juniper_graphql_ws works like a charm for us.

**Comment by pranaypratyush** [comment]
Does it allow me to do query and mutation over websocket at well?

**Comment by tyranron** [comment]
@pranaypratyush yes.
