### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by ja573** [graphql-rust/juniper#913]
**Is your feature request related to a problem? Please describe.**

I haven't been able to find a log with the different changes between versions.

**Describe the solution you'd like**
If such a log exists it'd be great to link to it more prominently (maybe in the readme), otherwise creating one down the line would be ideal.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by LegNeato** [comment]
There are changelogs in each crate. Happy to take a PR to make the location easier to find!

**Comment by roy-work** [comment]
@LegNeato I also would like a changelog for this project. What do you mean by "in each crate"? (I've checked the crates.io page, and the docs, and the repo, and none of those have a changelog in an obvious place.)

**Comment by tyranron** [comment]
@roy-work we'll make it a little more obvious to find before releasing 0.16.
