### ISSUE TITLE
Does not GraphQLObject support [u8; N] slice?

### ISSUE THREAD

**Issue by uuhan** [graphql-rust/juniper#918]
I have a struct with field of [u8; 5], but seems juniper does not support this type of data:

```rust
#[derive(GraphQLObject)]
pub struct Test {
    demo: [u8; 5]
}
```

the trait `GraphQLValue<__S>` is not implemented for `[u8; 9]`

**Comment by LegNeato** [comment]
It appears we do not support that style yet. I started a patch, will hopefully get time to polish it up by this weekend.

**Comment by LegNeato** [comment]
I have the field side of this done, just wrestling with some input object stuff

**Comment by tyranron** [comment]
@LegNeato I'll take it from here, if you don't mind.
