### ISSUE TITLE
FieldErrors lose their extensions while being implicitly converted from user defined subscription errors

### ISSUE THREAD

**Issue by xDarksome** [graphql-rust/juniper#925]
**Describe the bug**
Using question marks inside `graphql_subscription` macro causes user defined errors to be implicitly converted to `FieldError`s via `std::convert::Into` instead of `juniper::IntoFieldError`.    

Default `std::convert::From` implementation for `FieldError` populates only `FieldError::message` but not `FieldError::extensions`.

**To Reproduce**
- impl some error type which converts into `FieldError` with extensions
- define a subscription with `graphql_subscription` macro using the implemented error type
- use `?` inside the subscription body for short circuiting
- say 'goodbye' to your extensions

```rust
struct Error;

impl<S: ScalarValue> IntoFieldError<S> for Error {
    fn into_field_error(self) -> FieldError<S> {
        let mut extensions = Object::with_capacity(1);
        let _ = extensions.add_field("a",  Value::int(42));
        FieldError::new("oops", Value::Object(extensions))
    }
}

fn users_stream() -> Result<BoxStream<'static, User>, Error> {
    Err(Error)
}

#[graphql_subscription(name = "Subscription")]
impl SubscriptionsRoot {
    async fn users() -> Result<BoxStream<'static, User>, Error> {
        Ok(users_stream()?)
    }
}
```
You'll get something like:
```json
{
   "payload":{
      "errors":[
         {
            "message":"oops"
         }
      ]
   }
}
```

**Expected behavior**
Subscription returning error extensions:
```json
{
   "payload":{
      "errors":[
         {
            "message":"oops",
            "extensions": {
               "a": 42
            }
         }
      ]
   }
}
```

**Comment by tyranron** [comment]
@LegNeato ping. Would you be kind to release a new `juniper` version with recent fixes?
