### ISSUE TITLE
what I can do to use  the jupiter-actix with  actix web 4.0.0.beta*?

### ISSUE THREAD

**Issue by vidyli** [graphql-rust/juniper#929]
I am evaluating the jupiter-actix with actix web version 4.0.0.beta*, what I can do to use  it with  actix web 4.0.0.beta*?  I'd like to create a PR,  but is this suitable for the development plan?  I mean actix web 4.0 is not stable yet.

**Comment by engylemure** [comment]
https://github.com/graphql-rust/juniper/pull/912
