### ISSUE TITLE
Consider making inner GraphQLRequest public or implement Display

### ISSUE THREAD

**Issue by knutin** [graphql-rust/juniper#930]
Hello team,

We're using `juniper_rocket_async` and it all works great, but I can't find a way of accessing the inner graphql request object. I would like to log it, either as just a string or as json.

 
Specifically, it would be convenient if this inner type was public https://github.com/graphql-rust/juniper/blob/9c9639e8f0da0337880759c6fde469f863f74841/juniper_rocket_async/src/lib.rs#L64

However, that maybe is an API change you're not very interested in. Any ideas for a better solution? I would be happy to provide a PR.

Best,
Knut

**Comment by LegNeato** [comment]
I think either route is reasonable!

**Comment by tyranron** [comment]
@knutin would be `AsRef` + `AsMut` enough for your purposes?
