### ISSUE TITLE
what is the correct way to use IntoFieldError trait please?

### ISSUE THREAD

**Issue by videni** [graphql-rust/juniper#937]
```
impl<S: ScalarValue> IntoFieldError<S> for ValidationError
{
    fn into_field_error(self) -> FieldError<S>
    {
       FieldError::new(
            self.0,
            graphql_value!({
                "type": "validation_error"
        }))
    }
}

```
But it seems I need to call into_field_error method explicitly in a resolver, Since we need to call it manually, what is the point of existence of this trait?  do I did wrong please? 

```
match response {
            Ok(token) => Ok(CustomerToken { token }),
            Err(error) => {
                match error {
                    LoginError::InvalidPassword => Err(ValidationError(
                        translator.trans_simple("credential-not-correct"),
                    ).into_field_error()),
                    LoginError::UserNotFound => Err(user_not_exist(&email, translator).into_field_error())
                }
            }
        }
```
The example in juniper book doesn't work.

**Comment by tyranron** [comment]
@videni hi, would you be so kind to provide your function signature? It's not clear why you're doing exlicit conversion.

In our codebase we have our custom `graphql::Error` which impls `IntoFieldError<S: ScalarValue>`. All our fallible resolver signatures have type `-> Result<OkType, graphql::Error>`, and... that's all. We do not call `.into_field_error()` explicitly anywhere, while it's required on our custom `graphql::Error` to integrate naturally into `juniper`.

**Comment by tyranron** [comment]
Closing this, feel free to reopen if further assistance is needed.
