### ISSUE TITLE
Panic when spreading untyped union fragment

### ISSUE THREAD

**Issue by imintz** [graphql-rust/juniper#945]
**Describe the bug**
Updated my project from `0.15.3` to `0.15.5` and started observing the following sort of panic when spreading an untyped union fragment. Note that the specified concrete type is actually the union type.
`panicked at 'Concrete type <UnionType> is not handled by instance resolvers on GraphQL union <UnionType>`

**To Reproduce**
Example schema:

```graphql
union Character = Human | Droid
type Droid {
  id: ID!
  sensorColor: String!
}
type Human {
  id: ID!
  eyeColor: String!
}

type Query {
  mainCharacter: Character!
}
```

with the following query:

```graphql
query Query {
  mainCharacter {
    ...CharacterFragment
  }
}

fragment CharacterFragment on Character {
  __typename
  ... on Human {
    id
    eyeColor
  }
  ... on Droid {
    id
    sensorColor
  }
}
```

**Expected behavior**
No panic. And some result like:
```json
{
  "mainCharacter": { "__typename": "Droid", "id": 1, "sensorColor": "red" }
}
```

**Additional context**
I have an incoming PR that seems to fix this issue while still passing the tests for #922. Looks like it should be as simple as using the `concrete_type_name` when invoking `instance.resolve_into_type_async`.

**Comment by LegNeato** [comment]
Thank you for the issue and patch! I'll land after CI goes green

**Comment by imintz** [comment]
No prob! It looks like ci breakage was unrelated to the changes, but I've added a patch to the PR that fixes the issue.
