### ISSUE TITLE
Cannot use lifetimes in GraphQL object definitions

### ISSUE THREAD

**Issue by Diggsey** [graphql-rust/juniper#95]
When trying to declare a GraphQL object with a lifetime, as in the example from the documentation, the compiler gives the error:
```
error: expected type, found `'a`
```

**Comment by mhallin** [comment]
Hello!

This sounds weird. Could you please post the code you're trying to compile? Also, are you running version 0.8.1 or from the master branch of this repository?

**Comment by Diggsey** [comment]
I'm running the master branch of this repository.

The code looked like this:
```rust
struct SmsRecipient<'a>(&'a Recipient);

graphql_object!(<'a> SmsRecipient<'a>: DatabaseWrapper |&self| {
    description: "A recipient to be contacted via SMS"

    field id(&executor) -> Uuid {
        self.0.id
    }
    field name(&executor) -> &str {
        &self.0.name
    }

    interfaces: [Recipient]
});
```

I was trying to expose a struct containing a rust enum as a graphql interface. (On the rust side, a `Recipient` has a `contact_method` field).

I couldn't get the macro to accept lifetimes at all - I have had to resort to cloning the `Recipient` and storing it by value.

**Comment by mhallin** [comment]
I see. We're unfortunately a bit limited in terms of error messages when it comes to the macros, but in this case, it should be because an explicit type name is missing. This should work:

```rust
graphql_object(<'a> SmsRecipient<'a>: DatabaseWrapper as "SmsRecipient" |&self| {
    ...
});
```

The reason you need to specify a name is because we can't reliably derive a GraphQL type name from "SmsRecipient<'a>".

**Comment by Diggsey** [comment]
Ah, thanks!
