### ISSUE TITLE
Integration with Shio framework.

### ISSUE THREAD

**Issue by thedodd** [graphql-rust/juniper#96]
Shio is a promising framework which has cropped up over the last few months. It has some immense throughput potential with async I/O distributed across a threadpool of event loops. It would be awesome to build out an integration with this framework, perhaps as a pre-built integration, or in a separate crate.

**Integration with a framework that can achieve async I/O level throughput is critical for production adoption of Juniper in my case.** 

Currently I'm using a nodejs implementation, and being able to use Rust for this would be a huge win 🙌 . I use a lot of Go as well, but I greatly prefer Rust and use it where I can, and the Go graphql libs are not so awesome, IMHO.

I've looked at the discussion going on in the #2 `interop with async` issue. Being able to take a stab at it, to see where the walls are, may be beneficial. **I would love to spike this, but I definitely wanted to get some discussion going around this.**

Any and all feedback is welcome.

----

Great work on this lib so far. Once the async I/O story is g2g, I can definitely see this as being the most solid, convenient, productive, and powerful GraphQL option across the field of languages to chose from.

**Comment by theduke** [comment]
The iron and rocket integrations were initially part of the library, but were extracted into their own crates, so all other framework integrations also should live in their own crates. 

These crates are mostly some small glue code, so I think we'd definitely accept a `juniper_shio` crate if someone wants to step up and write it up. I'll create a new repo and development can happen there.

Regarding async, I have a lengthy comment regarding my vision for async which I haven't posted yet, but I'm very interested in async as will, and think it's crucial for scalable production grade GraphQL!

**Comment by theduke** [comment]
@thedodd would you find it sensible to release a `juniper_gotham` crate which contains the integration?

We'd be happy to accept it into the repo.

**Comment by theduke** [comment]
Otherwise, just a link to some open source example code would probably help users a lot.

**Comment by kamek-pf** [comment]
@theduke did you ever post that lengthy comment regarding async IO ? Really curious how this can be dealt with.
