### ISSUE TITLE
Query `Arc<RWLock<_>>` without cloning

### ISSUE THREAD

**Issue by omegablitz** [graphql-rust/juniper#969]
Hi all, thanks for the great library :)

Is there a way I can resolve a `FieldResult` to a reference when my state is contained in a `Arc<RWLock<_>>`? All the examples I could find either [used immutable state](https://graphql-rust.github.io/juniper/master/types/objects/using_contexts.html) or [cloned the internal state](https://github.com/http-rs/tide/blob/main/examples/graphql.rs#L41-L56).

A concrete example:
```rust
#[derive(Clone)]
pub struct Shared(pub Arc<RwLock<State>>);

#[derive(Clone)]
pub struct State {
    pub substate: HashMap<String, SubState>,
}

#[derive(Clone, GraphQLObject)]
pub struct SubState {
    a: String,
    b: String,
    // ...
}

#[derive(Clone)]
pub struct Context;

#[graphql_object(context = Context)]
impl State {
    fn substate(&self, k: String) -> FieldResult<&SubState> {
        Ok(self.substate.get(&k).ok_or("invalid key")?)
    }
}
```

I want to build a `RootNode<'static, State, EmptyMutation<Context>, EmptySubscription<Context>>`, but I can't get a `State` from a `Arc<RwLock<State>>`.

Conceptually, I'd like to do this by taking a read lock on every query.

Any suggestions would be much appreciated!

**Comment by tyranron** [comment]
@omegablitz 

> Conceptually, I'd like to do this by taking a read lock on every query.

This requires a `RwLockReadGuard<'_, T>` to be passed out of the function scope and implement `GraphQLValue`/`GraphQLType` (and similar) traits. We unlikely will support all guard types out-of-the-box in `juniper`, so you should go with a newtype:

```rust
pub struct MyReadGuard<'e, T>(pub RwLockReadGuard<'e, T>);

impl<'e, S, T> GraphQLType<S> for MyReadGuard<'e, T>
where
    T: GraphQLType<S> + ?Sized,
    S: ScalarValue,
{
    fn name(info: &Self::TypeInfo) -> Option<&str> {
        T::name(info)
    }

    fn meta<'r>(info: &Self::TypeInfo, registry: &mut Registry<'r, S>) -> MetaType<'r, S>
    where
        S: 'r,
    {
        T::meta(info, registry)
    }
}

impl<'e, S, T> GraphQLValue<S> for MyReadGuard<'e, T>
where
    S: ScalarValue,
    T: GraphQLValue<S> + ?Sized,
{
    type Context = T::Context;
    type TypeInfo = T::TypeInfo;

    fn type_name<'i>(&self, info: &'i Self::TypeInfo) -> Option<&'i str> {
        (**self).type_name(info)
    }

    fn resolve_into_type(
        &self,
        info: &Self::TypeInfo,
        name: &str,
        selection_set: Option<&[Selection<S>]>,
        executor: &Executor<Self::Context, S>,
    ) -> ExecutionResult<S> {
        (**self).resolve_into_type(info, name, selection_set, executor)
    }

    fn resolve_field(
        &self,
        info: &Self::TypeInfo,
        field: &str,
        args: &Arguments<S>,
        executor: &Executor<Self::Context, S>,
    ) -> ExecutionResult<S> {
        (**self).resolve_field(info, field, args, executor)
    }

    fn resolve(
        &self,
        info: &Self::TypeInfo,
        selection_set: Option<&[Selection<S>]>,
        executor: &Executor<Self::Context, S>,
    ) -> ExecutionResult<S> {
        (**self).resolve(info, selection_set, executor)
    }
}

impl<'e, S, T> GraphQLValueAsync<S> for MyReadGuard<'e, T>
where
    T: GraphQLValueAsync<S> + ?Sized,
    T::TypeInfo: Sync,
    T::Context: Sync,
    S: ScalarValue + Send + Sync,
{
    fn resolve_field_async<'b>(
        &'b self,
        info: &'b Self::TypeInfo,
        field_name: &'b str,
        arguments: &'b Arguments<S>,
        executor: &'b Executor<Self::Context, S>,
    ) -> BoxFuture<'b, ExecutionResult<S>> {
        (**self).resolve_field_async(info, field_name, arguments, executor)
    }

    fn resolve_async<'a>(
        &'a self,
        info: &'a Self::TypeInfo,
        selection_set: Option<&'a [Selection<S>]>,
        executor: &'a Executor<Self::Context, S>,
    ) -> BoxFuture<'a, ExecutionResult<S>> {
        (**self).resolve_async(info, selection_set, executor)
    }
}

impl<'e, T, S> ToInputValue<S> for MyReadGuard<'e, T>
where
    S: fmt::Debug,
    T: ToInputValue<S>,
{
    fn to_input_value(&self) -> InputValue<S> {
        (**self).to_input_value()
    }
}

impl<'e, S, T> IsOutputType<S> for MyReadGuard<'e, T>
where
    T: IsOutputType<S> + ?Sized,
    S: ScalarValue,
{
    #[inline]
    fn mark() {
        T::mark()
    }
}
```

See details in [pointers](https://github.com/graphql-rust/juniper/blob/juniper-v0.15.7/juniper/src/types/pointers.rs) and [markers](https://github.com/graphql-rust/juniper/blob/juniper-v0.15.7/juniper/src/types/marker.rs#L85-L116) implementations.

After that you will be able to do the following:
```rust
#[graphql_object(context = Context)]
impl State {
    fn substate(&self, k: String) -> FieldResult<MyReadGuard<'e, State>> {
        Ok(MyReadGuard(self.substate.get(&k).ok_or("invalid key")?.read()))
    }
}
```

**Comment by omegablitz** [comment]
Thanks for the quick response!

Will this still work given that `std::sync::RwLockReadGuard` is `!Send`? Both the pointers and markers implementations seem to work on `Send` types, unless I'm missing something.

I'm getting the following error:
```rust
error[E0277]: `std::sync::RwLockReadGuard<'_, State>` cannot be sent between threads safely
   --> src/main.rs:147:1
    |
147 | #[graphql_object]
    | ^^^^^^^^^^^^^^^^^ `std::sync::RwLockReadGuard<'_, State>` cannot be sent between threads safely
    | 
   ::: /Users/aashish.welling/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:61:43
    |
61  | pub const fn from_generator<T>(gen: T) -> impl Future<Output = T::Return>
    |                                           ------------------------------- within this `impl warp::Future`
    |
    = help: within `impl warp::Future`, the trait `std::marker::Send` is not implemented for `std::sync::RwLockReadGuard<'_, State>`
note: required because it appears within the type `MyReadGuard<'_, State>`
   --> src/main.rs:1:12
    |
1   | pub struct MyReadGuard<'e, T: ?Sized>(pub RwLockReadGuard<'e, T>);
    |            ^^^^^^^^^^^
    = note: required because it appears within the type `(&(), MyReadGuard<'_, State>)`
    = note: required because it appears within the type `std::option::Option<(&(), MyReadGuard<'_, State>)>`
    = note: required because it appears within the type `Result<std::option::Option<(&(), MyReadGuard<'_, State>)>, FieldError<__S>>`
    = note: required because it appears within the type `[static generator@src/main.rs:147:1: 147:18 _]`
    = note: required because it appears within the type `from_generator::GenFuture<[static generator@src/main.rs:147:1: 147:18 _]>`
    = note: required because it appears within the type `impl warp::Future`
    = note: required by `juniper::futures::FutureExt::boxed`
    = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

```

When I try to derive on:
```rust
#[graphql_object]
impl Shared {
    fn state(&self) -> FieldResult<MyReadGuard<State>> {
        Ok(MyReadGuard(self.0.read().unwrap()))
    }
}
```

**Comment by tyranron** [comment]
@omegablitz whoops! Haven't even thought about that!

No, the `Send` requirement is hard and is not something that can be lifted at the moment due to Rust type system restrictions: trait objects are not transparent over `Send`/`Sync`, but we should use trait object for `#[async_trait]`s. This possibly can be lifted in future when GATs and real async traits (without boxing) will be landed into stable Rust.

However, if you DO use single-threaded runtime like `actix-web`. You may overcome this by additionally wraping your guard into [`SendWrapper`](https://docs.rs/send_wrapper/0.5.0/send_wrapper/struct.SendWrapper.html):
```rust
pub struct MyReadGuard<'e, T>(pub SendWrapper<RwLockReadGuard<'e, T>>);
```
This will make your guard `Send` and due to the fact that it won't be passed to another thread in reality, this would work, without breaking invariants of `std::sync::RwLockReadGuard` (we only stisfy the type checker here).

However, if you're using multi-threaded `tokio` runtime (or `async_std`) with work stealing, this is impossible by design, because in `.await` points the current async task can really be passed to another thread, which totally breaks the invariant of `std::sync::RwLockReadGuard`.

Another way to try [`tokio::sync::RwLock`](https://docs.rs/tokio/1.8.2/tokio/sync/struct.RwLock.html), because [its `RwLockReadGuard` is `Send`](https://docs.rs/tokio/1.8.2/tokio/sync/struct.RwLockReadGuard.html#impl-Send) and [it's much better in read/write fairness handling](https://www.reddit.com/r/rust/comments/f4zldz/i_audited_3_different_implementation_of_async/). Additionally, you won't accidentially block your async runtime as you may with `std::sync::RwLock`.

**Comment by omegablitz** [comment]
Thanks so much, I just went with a `tokio::sync::RwLock` and that worked beautifully :)
