### ISSUE TITLE
What is the current recommended solution to the N+1 problem while using Juniper?

### ISSUE THREAD

**Issue by brochington** [graphql-rust/juniper#970]
Hello! I'm currently working on a new Actix-web/Juniper/Postgres application, and I'm trying to work through the best way to solve the infamous N+1 problem. So far in my research I've come across two ways that this has been solves with Juniper:

1. Using a Dataloader (as described in the "juniper book"
2. Using "Lookahead", which is not in the "book"

I am learning about both techniques now, but I'm still learning. Since they both seem to involve some heavy lifting, I'm curious which technique (or other) that I should be using and learning about. Any examples or docs for any of the above would also be very helpful. Thank you!

**Comment by tyranron** [comment]
@brochington you're right, that's all about it.

We're using Dataloader in our codebase. It does pretty well at the moment. However, the codebase is closed, but the [`dataloader` crate provides an example for `juniper`](https://github.com/cksac/dataloader-rs/blob/f5d12557a344e25cbd46256ccf048e05c1f49528/examples/juniper.rs).

As alternative approach, there is also an excellent crate [`juniper-eager-loading`](https://docs.rs/juniper-eager-loading). Its documentation is quite explanatory and has links to examples too.

As this issue doesn't imply any work done by `juniper` maintainers, I'm closing this for now. Feel free to reopen if further assistance is needed.
