### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by visortelle** [graphql-rust/juniper#974]
I got 404 after clicking the link:

<img width="403" alt="Screen Shot 2021-08-12 at 1 57 14 PM" src="https://user-images.githubusercontent.com/9302460/129185771-bb4902bd-6bf4-40a9-a862-b769eda4e0ac.png">

**Comment by insprac** [comment]
I'm looking at the repo for the first time and the book link is broken like kotx said, which is less than ideal since it's the first link in "Getting Started"

![image](https://user-images.githubusercontent.com/33383194/144763269-0a166906-753d-48ef-9565-684186264084.png)
