### ISSUE TITLE
axum exemple with websockets

### ISSUE THREAD

**Issue by mathroc** [graphql-rust/juniper#986]
**Is your feature request related to a problem? Please describe.**

I'm trying to build a small graphql server on top of [Axum](https://github.com/tokio-rs/axum) but can't figure out how to get websockets working with it

**Describe the solution you'd like**

I'd like an example similar to https://github.com/graphql-rust/juniper/tree/master/examples/warp_subscriptions

**Describe alternatives you've considered**

async-graphql does have an [Axum integration](https://github.com/async-graphql/async-graphql/tree/master/integrations/axum) but it does not support implementing dynamic schemas (and they don't plan to)

**Comment by btielen** [comment]
Working on it.

**Comment by tyranron** [comment]
The examples may be found [in `juniper_axum/examples`](https://github.com/graphql-rust/juniper/tree/761710205a5a928ce1d7be69894650059f91e877/juniper_axum/examples) and [in API docs of `subscriptions` module](https://github.com/graphql-rust/juniper/blob/761710205a5a928ce1d7be69894650059f91e877/juniper_axum/src/subscriptions.rs) (not released yet, however).
