### ISSUE TITLE
Duplicate field definitions are no longer allowed

### ISSUE THREAD

**Issue by alvra** [graphql-rust/juniper#999]
In the latest released version (0.15.7), the field definitions for a GraphQL object do not interfere with "regular methods", however, on the master branch this is no longer the case.

This code worked previously:
```rust
struct Value;

impl Value {
    // Imagine this is the common interface defined elsewhere.
    fn name(&self) -> &'static str {
        "ham"
    }
}

#[juniper::graphql_object]
impl Value {
    // This is the GraphQL field which differs from the method above.
    fn name(&self) -> &'static str {
        "spam"
    }
}
```

...but on the current latest commit `811c90486da28caae98f12691dba2237c292`, it fails:
```
error[E0592]: duplicate definitions with name `name`
  --> src/main.rs:4:5
   |
4  |     fn name(&self) -> &'static str {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ duplicate definitions for `name`
...
11 |     fn name(&self) -> &'static str {
   |     ------------------------------ other definition for `name`

For more information about this error, try `rustc --explain E0592`.
error: could not compile `juniper-enum-optional-arg` due to previous error
```

**Comment by tyranron** [comment]
@alvra that's not a bug, but rather the intended breaking change. New proc macro implementations follows the principle, that the user-written Rust code should represent a valid Rust code and should not magically disappear during proc macro expansion, but remains exactly as user has declared it.

Now, you may declare just 
```rust
#[juniper::graphql_object]
impl Value {
    // This is the GraphQL field which differs from the method above.
    fn name(&self) -> &'static str {
        "spam"
    }
}
```
and reuse it naturally in other Rust code (even not related to GraphQL), no need to factor out it into a separate common interface.
